#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate_sft_delivery.o
#$ -pe smp 8          # Specify parallel environment and legal core size
#$ -N evaluate_sft_delivery     # Specify job name

conda activate llmstl

# 生成测试问题
python3 delivery/convert_pddl3.py delivery/all_problems/testing delivery/testing_problems3

python3 script/evaluate_llm_solver.py --model sft_model/sft_model_pddl_mistral_7b_delivery  --problems-dir delivery/all_problems3/testing --domain-file delivery/domain3.pddl --max-problems 100 --output delivery_test_results.json  --results-dir planning_results/sft_model_pddl_mistral_7b/delivery/baseline

