#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_sft_ferry.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_sft_ferry # Specify job name

conda activate llmstl



python3 script/evaluate_llm_solver.py --model /home/ubuntu/sft_models/mistral_7b/ferry/base  --problems-dir ferry/all_problems3/testing --domain-file ferry/domain3.pddl --max-problems 100 --output ferry_test_results.json  --results-dir planning_results/sft_mistral_7b/ferry/baseline


