#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate/mistral/blocksworld/pddl3-500.o
#$ -pe smp 8
#$ -N evaluate_mistral_blocksworld_pddl3-500_all_testing

conda activate llmstl

# Evaluate PDDL3 fine-tuned model

python3 script/evaluate_llm_solver.py \
  --model "/groups/fkong/jfan5/dpo_models/mistral_7b/blocksworld/dpo-variant-V2" \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_dpo-variant-V2.json \
  --results-dir planning_results/mistral-7b-dpo-variant-blocksworld-V2/  --max-problems 50

