#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate_dpo_models/mistral_7b/blocksworld/pddl3_crc.o
#$ -pe smp 8
#$ -N evaluate_dpo_mistral_blocksworld_pddl3

conda activate llmstl

# Evaluate DPO fine-tuned model (PDDL3)
MODEL_PATH="/groups/fkong/jfan5/dpo_models/mistral_7b/blocksworld/pddl3_500"
RESULTS_DIR="planning_results/mistral_7b-blocksworld-dpo/"

python3 script/evaluate_llm_solver.py \
  --model "$MODEL_PATH" \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_dpo_pddl3-500.json \
  --results-dir "$RESULTS_DIR" --max-problems 50 --no-load-in-4bit

