#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate/mistral/blocksworld/pddl3_crc.o
#$ -pe smp 8
#$ -N evaluate_mistral_blocksworld_pddl3_all_testing

conda activate llmstl

# Evaluate PDDL3 fine-tuned model
MODEL_PATH="/groups/fkong/jfan5/sft_models/mistral_7b/blocksworld/pddl3"

python3 script/evaluate_llm_solver.py \
  --model "$MODEL_PATH" \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_pddl3.json \
  --results-dir planning_results/sft_mistral_7b/blocksworld/pddl3
  --max-problems 50

