#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate/mistral/multi_scenarios/pddl3_spanner.o
#$ -pe smp 8
#$ -N eval_mistral_spanner_pddl3-500

set -euo pipefail


conda activate llmstl

echo "=========================================="
echo "Model path: /groups/fkong/jfan5/sft_models/mistral_7b/multi_scenarios500/pddl3"
echo "Scenario: spanner"
echo "Problems dir: spanner/all_problems3/testing"
echo "Domain file: spanner/domain3.pddl"
echo "Results dir: planning_results/sft_mistral_7b_multi/spanner/pddl3-500/50"
echo "=========================================="

python3 script/evaluate_llm_solver.py \
  --model "/groups/fkong/jfan5/sft_models/mistral_7b/multi_scenarios500/pddl3-spanner" \
  --problems-dir "spanner/all_problems3/testing" \
  --domain-file "spanner/domain3.pddl" \
  --max-problems 50 \
  --output "spanner_multi_pddl3_50-500.json" \
  --results-dir "planning_results/sft_mistral_7b_multi/spanner/pddl3-500/50"
