; Domain designed by Yannis Dimopoulos, Alfonso Gerevini and Alessandro Saetti
; This file has been automatically generated by the generator available from
; http://zeus.ing.unibs.it/ipc-5/generators/index.html

(define (problem truck-450)
(:domain Trucks)
(:objects
	truck1 - truck
	package1 - package
	package2 - package
	l1 - location
	l2 - location
	t0 - time
	t1 - time
	t2 - time
	a1 - truckarea
	a2 - truckarea
	a3 - truckarea)

(:init
	(at truck1 l1)
	(free a1 truck1)
	(free a2 truck1)
	(free a3 truck1)
	(closer a1 a2)
	(closer a1 a3)
	(closer a2 a3)
	(at package1 l1)
	(at package2 l1)
	(connected l1 l2)
	(connected l2 l1)
	(time-now t0)
	(le t1 t1)
	(le t1 t2)
	(le t2 t2)
	(next t0 t1)
	(next t1 t2))

(:goal (and 
	(at-destination package1 l2)
	(at-destination package2 l2)))



)
