#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate_mistral_spanner.o
#$ -pe smp 8          # Specify parallel environment and legal core size
#$ -N evaluate_mistral_spanner     # Specify job name

conda activate llmstl
BASE_MODEL="unsloth/mistral-7b-instruct-v0.3-bnb-4bit"

PROBLEMS_DIR="spanner/all_problems3/testing"
DOMAIN_FILE="spanner/domain3.pddl"
RESULTS_DIR="planning_results/mistral_7b/spanner/baseline"
OUTPUT_NAME="spanner_test_results.json"

python3 script/evaluate_llm_solver.py --model $BASE_MODEL --problems-dir $PROBLEMS_DIR --domain-file $DOMAIN_FILE --max-problems 100 --output $OUTPUT_NAME  --results-dir $RESULTS_DIR
