


(define (problem gripper-14)
(:domain gripper-strips)
(:objects rooma roomb room3 room4 left ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 )
(:init
(room rooma)
(room roomb)
(room room3)
(room room4)
(gripper left)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(ball ball9)
(ball ball10)
(ball ball11)
(ball ball12)
(ball ball13)
(ball ball14)
(free left)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 roomb)
(at ball6 roomb)
(at ball7 room3)
(at ball8 room3)
(at ball9 room3)
(at ball10 room3)
(at ball11 room3)
(at ball12 room3)
(at ball13 room4)
(at ball14 room4)
(at-robby rooma)
)
(:goal
(and
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 rooma)
(at ball6 rooma)
(at ball7 roomb)
(at ball8 roomb)
(at ball9 roomb)
(at ball10 roomb)
(at ball11 room3)
(at ball12 room3)
(at ball13 room3)
(at ball14 room3)
)
)
)


