


(define (problem gripper-11)
(:domain gripper-strips)
(:objects rooma roomb room3 room4 room5 room6 left right ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 )
(:init
(room rooma)
(room roomb)
(room room3)
(room room4)
(room room5)
(room room6)
(gripper left)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(ball ball9)
(ball ball10)
(ball ball11)
(free left)
(free right)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 room4)
(at ball5 room4)
(at ball6 room5)
(at ball7 room5)
(at ball8 room5)
(at ball9 room5)
(at ball10 room5)
(at ball11 room6)
(at-robby rooma)
)
(:goal
(and
(at ball1 rooma)
(at ball2 rooma)
(at ball3 roomb)
(at ball4 roomb)
(at ball5 room3)
(at ball6 room4)
(at ball7 room4)
(at ball8 room4)
(at ball9 room5)
(at ball10 room6)
(at ball11 room6)
)
)
)


