


(define (problem gripper-15)
(:domain gripper-strips)
(:objects rooma roomb room3 left right ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 ball13 ball14 ball15 )
(:init
(room rooma)
(room roomb)
(room room3)
(gripper left)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(ball ball9)
(ball ball10)
(ball ball11)
(ball ball12)
(ball ball13)
(ball ball14)
(ball ball15)
(free left)
(free right)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 rooma)
(at ball6 rooma)
(at ball7 rooma)
(at ball8 roomb)
(at ball9 roomb)
(at ball10 roomb)
(at ball11 roomb)
(at ball12 room3)
(at ball13 room3)
(at ball14 room3)
(at ball15 room3)
(at-robby rooma)
)
(:goal
(and
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 rooma)
(at ball6 rooma)
(at ball7 rooma)
(at ball8 roomb)
(at ball9 roomb)
(at ball10 roomb)
(at ball11 roomb)
(at ball12 roomb)
(at ball13 room3)
(at ball14 room3)
(at ball15 room3)
)
)
)


