


(define (problem gripper-12)
(:domain gripper-strips)
(:objects rooma roomb room3 room4 room5 left right ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 ball12 )
(:init
(room rooma)
(room roomb)
(room room3)
(room room4)
(room room5)
(gripper left)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(ball ball9)
(ball ball10)
(ball ball11)
(ball ball12)
(free left)
(free right)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 rooma)
(at ball6 rooma)
(at ball7 rooma)
(at ball8 rooma)
(at ball9 rooma)
(at ball10 rooma)
(at ball11 rooma)
(at ball12 rooma)
(at-robby rooma)
)
(:goal
(and
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 roomb)
(at ball5 roomb)
(at ball6 room3)
(at ball7 room3)
(at ball8 room3)
(at ball9 room4)
(at ball10 room4)
(at ball11 room5)
(at ball12 room5)
)
)
)


