


(define (problem gripper-8)
(:domain gripper-strips)
(:objects rooma roomb room3 room4 room5 room6 left right ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 )
(:init
(room rooma)
(room roomb)
(room room3)
(room room4)
(room room5)
(room room6)
(gripper left)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(free left)
(free right)
(at ball1 rooma)
(at ball2 roomb)
(at ball3 roomb)
(at ball4 room3)
(at ball5 room4)
(at ball6 room6)
(at ball7 room6)
(at ball8 room6)
(at-robby rooma)
)
(:goal
(and
(at ball1 roomb)
(at ball2 roomb)
(at ball3 roomb)
(at ball4 roomb)
(at ball5 roomb)
(at ball6 roomb)
(at ball7 roomb)
(at ball8 roomb)
)
)
)


