#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_gpt_ferry.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_gpt_ferry # Specify job name

conda activate llmstl
BASE_MODEL="unsloth/gpt-oss-20b-unsloth-bnb-4bit"

PROBLEMS_DIR="ferry/all_problems3/testing"
DOMAIN_FILE="ferry/domain3.pddl"
RESULTS_DIR="planning_results/unsloth_gpt-oss-20b-unsloth-bnb-4bit/ferry/baseline"
OUTPUT_NAME="ferry_test_results.json"

python3 script/evaluate_llm_solver.py --model $BASE_MODEL --problems-dir $PROBLEMS_DIR --domain-file $DOMAIN_FILE --max-problems 100 --output $OUTPUT_NAME  --results-dir $RESULTS_DIR


