#!/bin/bash

# SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_sft_logistics.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_sft_logistics # Specify job name


# 生成测试问题
# python3 logistcs/convert_to_pddl3.py logistics/all_problems/tes logistics/testing_problems3


python3 script/evaluate_llm_solver.py --model sft_model/mistral_7b/logistics/base  --problems-dir logistics/testing_problems3 --domain-file logistics/domain3.pddl --max-problems 100 --output logistics_test_results.json  --results-dir sft_results/mistral_7b/logistics/base
