#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_mistral_grippers.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_mistral_grippers # Specify job name

conda activate llmstl
BASE_MODEL="unsloth/mistral-7b-instruct-v0.3-bnb-4bit"

PROBLEMS_DIR="grippers/testing_problems3"
DOMAIN_FILE="grippers/domain3.pddl"
RESULTS_DIR="planning_results/grippers_mistral_planning_results"
OUTPUT_NAME="grippers_test_results.json"

python3 script/evaluate_llm_solver.py --model $BASE_MODEL --problems-dir $PROBLEMS_DIR --domain-file $DOMAIN_FILE --max-problems 100 --output $OUTPUT_NAME  --results-dir $RESULTS_DIR


