#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_sft_grippers.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_sft_grippers # Specify job name

conda activate llmstl



python3 script/evaluate_llm_solver.py --model sft_model/mistral_7b/grippers/base  --problems-dir grippers/testing_problems3 --domain-file grippers/domain3.pddl --max-problems 100 --output grippers_test_results.json  --results-dir sft_results/mistral_7b/grippers/base


