#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate/qwen3_1_7b/rovers/baseline_crc.o
#$ -pe smp 28
#$ -N evaluate_qwen3_1_7b_rovers_baseline_all_testing

conda activate llmstl

# Evaluate baseline unsloth model
BASE_MODEL="unsloth/Qwen3-1.7B-unsloth-bnb-4bit"

python3 script/evaluate_llm_solver.py \
  --model "$BASE_MODEL" \
  --problems-dir rovers/all_problems3/testing \
  --domain-file rovers/domain3.pddl \
  --output rovers_all_testing_baseline.json \
  --results-dir planning_results/qwen3_1_7b/rovers/baseline
