#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate_llama_blocksworld_baseline_all_testing.o
#$ -pe smp 8
#$ -N evaluate_llama_blocksworld_baseline_all_testing

conda activate llmstl

# Evaluate baseline unsloth model
BASE_MODEL="unsloth/llama-3-8b-bnb-4bit"

python3 script/evaluate_llm_solver.py \
  --model "$BASE_MODEL" \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_baseline.json \
  --results-dir planning_results/llama/blocksworld/baseline
