
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1951744388)
    (:domain delivery)

    (:objects
        obj_08 obj_10 obj_04 obj_11 obj_09 obj_01 obj_07 obj_05 obj_03 - type_2
        obj_06 - type_4
        obj_02 - type_3
    )

    (:init
        (pred_3 obj_09 obj_11)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_10 obj_08)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_11 obj_07)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_10 obj_09)
        (pred_3 obj_08 obj_10)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_06 obj_04)
        (pred_5 obj_02)
    )

    (:goal
        (pred_1 obj_06 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_02 obj_10) (pred_1 obj_02 obj_09))) (not (and (pred_4 obj_02 obj_09) (pred_1 obj_02 obj_10)))))
  )
)

