
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1124060556)
    (:domain delivery)

    (:objects
        obj_02 obj_12 obj_19 obj_08 obj_05 obj_06 obj_14 obj_13 obj_11 obj_09 obj_18 obj_07 obj_01 obj_17 obj_03 obj_15 - type_4
        obj_10 obj_16 - type_3
        obj_04 - type_1
    )

    (:init
        (pred_2 obj_19 obj_12)
        (pred_2 obj_14 obj_06)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_18 obj_14)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_18 obj_03)
        (pred_2 obj_18 obj_07)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_19 obj_08)
        (pred_2 obj_07 obj_18)
        (pred_2 obj_17 obj_03)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_01 obj_17)
        (pred_2 obj_17 obj_01)
        (pred_2 obj_19 obj_14)
        (pred_2 obj_07 obj_13)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_09 obj_18)
        (pred_2 obj_15 obj_07)
        (pred_2 obj_12 obj_19)
        (pred_2 obj_03 obj_18)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_07 obj_15)
        (pred_2 obj_15 obj_03)
        (pred_2 obj_12 obj_02)
        (pred_2 obj_14 obj_18)
        (pred_2 obj_14 obj_19)
        (pred_2 obj_09 obj_17)
        (pred_2 obj_13 obj_08)
        (pred_2 obj_03 obj_17)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_08 obj_19)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_14 obj_13)
        (pred_2 obj_02 obj_12)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_06 obj_14)
        (pred_2 obj_13 obj_14)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_18 obj_09)
        (pred_2 obj_13 obj_07)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_03 obj_15)
        (pred_2 obj_08 obj_13)
        (pred_2 obj_12 obj_06)
        (pred_2 obj_17 obj_09)
        (pred_1 obj_10 obj_09)
        (pred_1 obj_16 obj_09)
        (pred_1 obj_04 obj_05)
        (pred_5 obj_04)
    )

    (:goal
        (and (pred_1 obj_10 obj_01) (pred_1 obj_16 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_11) (pred_1 obj_04 obj_01))) (not (and (pred_3 obj_04 obj_01) (pred_1 obj_04 obj_11)))))
  )
)

