
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-48758094)
    (:domain delivery)

    (:objects
        obj_11 obj_06 obj_02 obj_03 obj_04 obj_12 obj_07 obj_10 obj_01 - type_1
        obj_09 obj_05 - type_2
        obj_08 - type_3
    )

    (:init
        (pred_5 obj_12 obj_01)
        (pred_5 obj_01 obj_10)
        (pred_5 obj_07 obj_03)
        (pred_5 obj_02 obj_12)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_12 obj_02)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_02 obj_06)
        (pred_5 obj_03 obj_11)
        (pred_5 obj_11 obj_06)
        (pred_5 obj_07 obj_10)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_10 obj_07)
        (pred_5 obj_06 obj_11)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_06 obj_02)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_11 obj_03)
        (pred_5 obj_01 obj_12)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_08 obj_01)
        (pred_3 obj_05 obj_06)
        (pred_4 obj_08)
    )

    (:goal
        (and (pred_3 obj_09 obj_06) (pred_3 obj_05 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_08 obj_04) (pred_3 obj_08 obj_10))) (not (and (pred_2 obj_08 obj_10) (pred_3 obj_08 obj_04)))))
  )
)

