
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1999294160)
    (:domain delivery)

    (:objects
        obj_09 obj_10 obj_11 obj_03 obj_08 obj_02 obj_05 obj_01 obj_06 - type_4
        obj_07 - type_1
        obj_04 - type_2
    )

    (:init
        (pred_5 obj_08 obj_03)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_03 obj_05)
        (pred_5 obj_01 obj_05)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_06 obj_02)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_01 obj_08)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_02 obj_06)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_02 obj_08)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_08 obj_01)
        (pred_5 obj_03 obj_09)
        (pred_5 obj_05 obj_03)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_10 obj_08)
        (pred_5 obj_09 obj_10)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_04 obj_02)
        (pred_2 obj_04)
    )

    (:goal
        (pred_4 obj_07 obj_08)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_10) (pred_4 obj_04 obj_08))) (not (and (pred_3 obj_04 obj_08) (pred_4 obj_04 obj_10)))))
  )
)

