
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-1642490853)
    (:domain delivery)

    (:objects
        obj_04 obj_05 obj_07 obj_03 - type_3
        obj_06 obj_01 - type_4
        obj_02 - type_2
    )

    (:init
        (pred_2 obj_03 obj_05)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_04 obj_07)
        (pred_1 obj_06 obj_07)
        (pred_1 obj_01 obj_05)
        (pred_1 obj_02 obj_03)
        (pred_5 obj_02)
    )

    (:goal
        (and (pred_1 obj_06 obj_07) (pred_1 obj_01 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_02 obj_04) (pred_1 obj_02 obj_05))) (not (and (pred_4 obj_02 obj_05) (pred_1 obj_02 obj_04)))))
  )
)

