
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1455727457)
    (:domain delivery)

    (:objects
        obj_02 obj_18 obj_01 obj_09 obj_10 obj_15 obj_03 obj_07 obj_11 obj_08 obj_04 obj_16 obj_13 obj_06 obj_17 obj_14 - type_2
        obj_12 - type_3
        obj_05 - type_1
    )

    (:init
        (pred_1 obj_04 obj_08)
        (pred_1 obj_11 obj_08)
        (pred_1 obj_08 obj_15)
        (pred_1 obj_16 obj_07)
        (pred_1 obj_16 obj_14)
        (pred_1 obj_16 obj_04)
        (pred_1 obj_08 obj_11)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_07 obj_03)
        (pred_1 obj_06 obj_17)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_01 obj_18)
        (pred_1 obj_18 obj_02)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_13 obj_11)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_04 obj_03)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_17 obj_06)
        (pred_1 obj_09 obj_01)
        (pred_1 obj_15 obj_08)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_03 obj_04)
        (pred_1 obj_07 obj_16)
        (pred_1 obj_17 obj_04)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_02 obj_18)
        (pred_1 obj_18 obj_01)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_15 obj_18)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_18 obj_15)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_14 obj_16)
        (pred_1 obj_04 obj_17)
        (pred_1 obj_11 obj_13)
        (pred_1 obj_04 obj_16)
        (pred_4 obj_05 obj_16)
        (pred_4 obj_12 obj_10)
        (pred_5 obj_05)
    )

    (:goal
        (pred_4 obj_12 obj_14)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_05 obj_03) (pred_4 obj_05 obj_07))) (not (and (pred_2 obj_05 obj_07) (pred_4 obj_05 obj_03)))))
  )
)

