
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1559295073)
    (:domain delivery)

    (:objects
        obj_06 obj_05 obj_13 obj_17 obj_16 obj_03 obj_10 obj_12 obj_02 obj_04 obj_08 obj_15 obj_09 obj_07 obj_18 obj_11 - type_1
        obj_01 - type_2
        obj_14 - type_4
    )

    (:init
        (pred_4 obj_08 obj_04)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_04 obj_03)
        (pred_4 obj_15 obj_12)
        (pred_4 obj_15 obj_11)
        (pred_4 obj_15 obj_08)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_12 obj_10)
        (pred_4 obj_07 obj_18)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_16 obj_06)
        (pred_4 obj_13 obj_05)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_04 obj_08)
        (pred_4 obj_09 obj_02)
        (pred_4 obj_10 obj_13)
        (pred_4 obj_13 obj_10)
        (pred_4 obj_02 obj_16)
        (pred_4 obj_12 obj_17)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_10 obj_03)
        (pred_4 obj_18 obj_07)
        (pred_4 obj_17 obj_13)
        (pred_4 obj_03 obj_04)
        (pred_4 obj_13 obj_17)
        (pred_4 obj_10 obj_08)
        (pred_4 obj_12 obj_15)
        (pred_4 obj_18 obj_08)
        (pred_4 obj_18 obj_11)
        (pred_4 obj_10 obj_12)
        (pred_4 obj_16 obj_03)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_05 obj_13)
        (pred_4 obj_16 obj_02)
        (pred_4 obj_03 obj_05)
        (pred_4 obj_17 obj_12)
        (pred_4 obj_05 obj_03)
        (pred_4 obj_03 obj_16)
        (pred_4 obj_06 obj_16)
        (pred_4 obj_11 obj_18)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_11 obj_15)
        (pred_4 obj_08 obj_18)
        (pred_4 obj_02 obj_09)
        (pred_4 obj_08 obj_15)
        (pred_2 obj_14 obj_05)
        (pred_2 obj_01 obj_17)
        (pred_1 obj_14)
    )

    (:goal
        (pred_2 obj_01 obj_10)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_14 obj_13) (pred_2 obj_14 obj_17))) (not (and (pred_5 obj_14 obj_17) (pred_2 obj_14 obj_13)))))
  )
)

