
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1817699194)
    (:domain delivery)

    (:objects
        obj_06 obj_07 obj_05 obj_11 obj_02 obj_10 obj_09 obj_03 obj_08 - type_1
        obj_04 - type_3
        obj_01 - type_4
    )

    (:init
        (pred_2 obj_02 obj_11)
        (pred_2 obj_10 obj_05)
        (pred_2 obj_07 obj_06)
        (pred_2 obj_06 obj_11)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_03 obj_08)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_02 obj_10)
        (pred_2 obj_05 obj_10)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_10 obj_02)
        (pred_2 obj_08 obj_03)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_11 obj_06)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_06 obj_07)
        (pred_5 obj_01 obj_03)
        (pred_5 obj_04 obj_11)
        (pred_4 obj_01)
    )

    (:goal
        (pred_5 obj_04 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_06) (pred_5 obj_01 obj_07))) (not (and (pred_1 obj_01 obj_07) (pred_5 obj_01 obj_06)))))
  )
)

