
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-807774238)
    (:domain delivery)

    (:objects
        obj_18 obj_05 obj_11 obj_09 obj_10 obj_12 obj_03 obj_15 obj_02 obj_13 obj_08 obj_01 obj_04 obj_17 obj_07 obj_14 - type_4
        obj_16 - type_3
        obj_06 - type_2
    )

    (:init
        (pred_3 obj_08 obj_13)
        (pred_3 obj_02 obj_13)
        (pred_3 obj_13 obj_12)
        (pred_3 obj_01 obj_15)
        (pred_3 obj_01 obj_14)
        (pred_3 obj_01 obj_08)
        (pred_3 obj_13 obj_02)
        (pred_3 obj_13 obj_17)
        (pred_3 obj_15 obj_03)
        (pred_3 obj_17 obj_07)
        (pred_3 obj_17 obj_04)
        (pred_3 obj_10 obj_18)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_05 obj_18)
        (pred_3 obj_04 obj_17)
        (pred_3 obj_17 obj_13)
        (pred_3 obj_13 obj_08)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_15 obj_09)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_03 obj_12)
        (pred_3 obj_07 obj_17)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_12 obj_13)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_15 obj_01)
        (pred_3 obj_07 obj_08)
        (pred_3 obj_07 obj_14)
        (pred_3 obj_03 obj_15)
        (pred_3 obj_10 obj_12)
        (pred_3 obj_18 obj_05)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_10 obj_02)
        (pred_3 obj_12 obj_05)
        (pred_3 obj_09 obj_15)
        (pred_3 obj_05 obj_12)
        (pred_3 obj_12 obj_10)
        (pred_3 obj_18 obj_10)
        (pred_3 obj_14 obj_07)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_14 obj_01)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_08 obj_01)
        (pred_5 obj_16 obj_08)
        (pred_5 obj_06 obj_13)
        (pred_2 obj_06)
    )

    (:goal
        (pred_5 obj_16 obj_14)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_06 obj_08) (pred_5 obj_06 obj_01))) (not (and (pred_1 obj_06 obj_01) (pred_5 obj_06 obj_08)))))
  )
)

