
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1250958270)
    (:domain delivery)

    (:objects
        obj_07 obj_08 obj_06 obj_17 obj_05 obj_03 obj_10 obj_02 obj_19 obj_04 obj_13 obj_16 obj_18 obj_01 obj_09 obj_12 - type_3
        obj_15 obj_11 - type_4
        obj_14 - type_2
    )

    (:init
        (pred_3 obj_06 obj_08)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_19 obj_18)
        (pred_3 obj_13 obj_10)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_13 obj_09)
        (pred_3 obj_13 obj_16)
        (pred_3 obj_18 obj_19)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_16 obj_13)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_18 obj_01)
        (pred_3 obj_01 obj_18)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_16 obj_02)
        (pred_3 obj_04 obj_19)
        (pred_3 obj_04 obj_13)
        (pred_3 obj_12 obj_16)
        (pred_3 obj_08 obj_06)
        (pred_3 obj_09 obj_13)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_16 obj_12)
        (pred_3 obj_12 obj_09)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_10 obj_13)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_02 obj_17)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_03 obj_04)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_19 obj_04)
        (pred_3 obj_10 obj_02)
        (pred_3 obj_07 obj_08)
        (pred_3 obj_05 obj_19)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_19 obj_05)
        (pred_3 obj_13 obj_04)
        (pred_3 obj_02 obj_16)
        (pred_3 obj_04 obj_03)
        (pred_3 obj_09 obj_12)
        (pred_3 obj_17 obj_02)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_01 obj_04)
        (pred_2 obj_15 obj_18)
        (pred_2 obj_14 obj_16)
        (pred_2 obj_11 obj_17)
        (pred_4 obj_14)
    )

    (:goal
        (and (pred_2 obj_15 obj_09) (pred_2 obj_11 obj_09))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_14 obj_06) (pred_2 obj_14 obj_10))) (not (and (pred_1 obj_14 obj_10) (pred_2 obj_14 obj_06)))))
  )
)

