
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1853022673)
    (:domain delivery)

    (:objects
        obj_05 obj_01 obj_15 obj_11 obj_09 obj_06 obj_19 obj_12 obj_16 obj_18 obj_17 obj_14 obj_02 obj_07 obj_08 obj_10 - type_4
        obj_03 obj_04 - type_3
        obj_13 - type_2
    )

    (:init
        (pred_5 obj_15 obj_01)
        (pred_5 obj_19 obj_06)
        (pred_5 obj_16 obj_02)
        (pred_5 obj_17 obj_19)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_17 obj_08)
        (pred_5 obj_17 obj_14)
        (pred_5 obj_02 obj_16)
        (pred_5 obj_15 obj_11)
        (pred_5 obj_14 obj_17)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_09 obj_06)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_15 obj_19)
        (pred_5 obj_14 obj_12)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_18 obj_17)
        (pred_5 obj_10 obj_14)
        (pred_5 obj_01 obj_15)
        (pred_5 obj_08 obj_17)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_14 obj_10)
        (pred_5 obj_10 obj_08)
        (pred_5 obj_01 obj_05)
        (pred_5 obj_19 obj_17)
        (pred_5 obj_19 obj_15)
        (pred_5 obj_18 obj_07)
        (pred_5 obj_12 obj_11)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_06 obj_18)
        (pred_5 obj_11 obj_15)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_19 obj_12)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_09 obj_16)
        (pred_5 obj_06 obj_09)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_06 obj_19)
        (pred_5 obj_12 obj_19)
        (pred_5 obj_16 obj_09)
        (pred_5 obj_17 obj_18)
        (pred_5 obj_12 obj_14)
        (pred_5 obj_18 obj_06)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_11 obj_12)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_07 obj_18)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_03 obj_16)
        (pred_1 obj_13 obj_06)
        (pred_3 obj_13)
    )

    (:goal
        (and (pred_1 obj_03 obj_16) (pred_1 obj_04 obj_16))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_13 obj_09) (pred_1 obj_13 obj_16))) (not (and (pred_2 obj_13 obj_16) (pred_1 obj_13 obj_09)))))
  )
)

