
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1707916834)
    (:domain delivery)

    (:objects
        obj_02 obj_08 obj_06 obj_03 obj_11 obj_01 obj_04 obj_05 obj_12 - type_2
        obj_07 obj_09 - type_3
        obj_10 - type_1
    )

    (:init
        (pred_2 obj_01 obj_12)
        (pred_2 obj_12 obj_05)
        (pred_2 obj_04 obj_03)
        (pred_2 obj_06 obj_01)
        (pred_2 obj_03 obj_11)
        (pred_2 obj_01 obj_06)
        (pred_2 obj_05 obj_12)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_02 obj_08)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_08 obj_11)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_08 obj_02)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_11 obj_03)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_11 obj_08)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_12 obj_01)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_09 obj_12)
        (pred_4 obj_10)
    )

    (:goal
        (and (pred_3 obj_07 obj_08) (pred_3 obj_09 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_10 obj_11) (pred_3 obj_10 obj_05))) (not (and (pred_5 obj_10 obj_05) (pred_3 obj_10 obj_11)))))
  )
)

