
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-688053435)
    (:domain delivery)

    (:objects
        obj_03 obj_07 obj_06 obj_04 - type_4
        obj_02 obj_05 - type_2
        obj_01 - type_3
    )

    (:init
        (pred_3 obj_04 obj_07)
        (pred_3 obj_06 obj_03)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_07 obj_03)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_03 obj_06)
        (pred_2 obj_01 obj_07)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_02 obj_07)
        (pred_5 obj_01)
    )

    (:goal
        (and (pred_2 obj_02 obj_06) (pred_2 obj_05 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_01 obj_03) (pred_2 obj_01 obj_07))) (not (and (pred_4 obj_01 obj_07) (pred_2 obj_01 obj_03)))))
  )
)

