
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1610268059)
    (:domain delivery)

    (:objects
        obj_19 obj_18 obj_13 obj_09 obj_06 obj_15 obj_02 obj_03 obj_16 obj_08 obj_11 obj_10 obj_14 obj_04 obj_07 obj_17 - type_1
        obj_01 obj_05 - type_2
        obj_12 - type_3
    )

    (:init
        (pred_2 obj_13 obj_18)
        (pred_2 obj_02 obj_15)
        (pred_2 obj_16 obj_14)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_19 obj_06)
        (pred_2 obj_11 obj_07)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_14 obj_16)
        (pred_2 obj_13 obj_09)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_06 obj_15)
        (pred_2 obj_14 obj_04)
        (pred_2 obj_04 obj_14)
        (pred_2 obj_13 obj_02)
        (pred_2 obj_10 obj_03)
        (pred_2 obj_08 obj_16)
        (pred_2 obj_08 obj_11)
        (pred_2 obj_17 obj_10)
        (pred_2 obj_18 obj_13)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_15 obj_18)
        (pred_2 obj_10 obj_17)
        (pred_2 obj_17 obj_07)
        (pred_2 obj_18 obj_19)
        (pred_2 obj_02 obj_11)
        (pred_2 obj_02 obj_13)
        (pred_2 obj_08 obj_04)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_15 obj_08)
        (pred_2 obj_09 obj_13)
        (pred_2 obj_16 obj_08)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_19 obj_18)
        (pred_2 obj_06 obj_16)
        (pred_2 obj_15 obj_06)
        (pred_2 obj_06 obj_19)
        (pred_2 obj_15 obj_02)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_16 obj_06)
        (pred_2 obj_11 obj_08)
        (pred_2 obj_03 obj_10)
        (pred_2 obj_08 obj_15)
        (pred_2 obj_07 obj_17)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_18 obj_15)
        (pred_2 obj_04 obj_08)
        (pred_3 obj_12 obj_17)
        (pred_3 obj_05 obj_06)
        (pred_3 obj_01 obj_02)
        (pred_1 obj_12)
    )

    (:goal
        (and (pred_3 obj_01 obj_09) (pred_3 obj_05 obj_09))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_12 obj_13) (pred_3 obj_12 obj_02))) (not (and (pred_4 obj_12 obj_02) (pred_3 obj_12 obj_13)))))
  )
)

