
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-219302506)
    (:domain delivery)

    (:objects
        obj_06 obj_01 obj_09 obj_11 obj_04 obj_08 obj_05 obj_02 obj_07 - type_3
        obj_10 - type_4
        obj_03 - type_1
    )

    (:init
        (pred_3 obj_04 obj_11)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_02 obj_05)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_07 obj_08)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_05 obj_02)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_06 obj_01)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_10 obj_05)
        (pred_1 obj_03)
    )

    (:goal
        (pred_2 obj_10 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_03 obj_11) (pred_2 obj_03 obj_05))) (not (and (pred_4 obj_03 obj_05) (pred_2 obj_03 obj_11)))))
  )
)

