
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-104808433)
    (:domain delivery)

    (:objects
        obj_13 obj_17 obj_16 obj_11 obj_15 obj_05 obj_09 obj_18 obj_03 obj_10 obj_07 obj_19 obj_06 obj_12 obj_01 obj_02 - type_1
        obj_08 obj_14 - type_2
        obj_04 - type_3
    )

    (:init
        (pred_5 obj_16 obj_17)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_07 obj_09)
        (pred_5 obj_13 obj_15)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_07 obj_19)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_16 obj_11)
        (pred_5 obj_19 obj_07)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_16 obj_09)
        (pred_5 obj_19 obj_18)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_10 obj_07)
        (pred_5 obj_02 obj_19)
        (pred_5 obj_17 obj_16)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_05 obj_17)
        (pred_5 obj_19 obj_02)
        (pred_5 obj_02 obj_01)
        (pred_5 obj_17 obj_13)
        (pred_5 obj_09 obj_07)
        (pred_5 obj_09 obj_16)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_18 obj_11)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_11 obj_16)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_09 obj_18)
        (pred_5 obj_13 obj_17)
        (pred_5 obj_15 obj_03)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_15 obj_13)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_18 obj_09)
        (pred_5 obj_03 obj_15)
        (pred_5 obj_07 obj_10)
        (pred_5 obj_18 obj_19)
        (pred_5 obj_10 obj_05)
        (pred_5 obj_01 obj_02)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_17 obj_05)
        (pred_5 obj_12 obj_10)
        (pred_3 obj_08 obj_17)
        (pred_3 obj_14 obj_15)
        (pred_3 obj_04 obj_10)
        (pred_4 obj_04)
    )

    (:goal
        (and (pred_3 obj_08 obj_07) (pred_3 obj_14 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_04 obj_16) (pred_3 obj_04 obj_09))) (not (and (pred_2 obj_04 obj_09) (pred_3 obj_04 obj_16)))))
  )
)

