
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1196303403)
    (:domain delivery)

    (:objects
        obj_03 obj_04 obj_08 obj_10 obj_11 obj_02 obj_07 obj_09 obj_06 - type_1
        obj_01 obj_05 - type_4
        obj_12 - type_3
    )

    (:init
        (pred_2 obj_02 obj_06)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_08 obj_02)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_02 obj_08)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_08 obj_04)
        (pred_2 obj_10 obj_03)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_04 obj_11)
        (pred_2 obj_09 obj_07)
        (pred_2 obj_04 obj_03)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_04 obj_08)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_02 obj_11)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_11 obj_04)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_03 obj_10)
        (pred_2 obj_06 obj_02)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_01 obj_11)
        (pred_4 obj_12)
    )

    (:goal
        (and (pred_3 obj_01 obj_07) (pred_3 obj_05 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_12 obj_10) (pred_3 obj_12 obj_07))) (not (and (pred_1 obj_12 obj_07) (pred_3 obj_12 obj_10)))))
  )
)

