
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-806253592)
    (:domain delivery)

    (:objects
        obj_06 obj_02 obj_07 obj_09 obj_08 obj_11 obj_10 obj_03 obj_12 - type_3
        obj_01 obj_05 - type_2
        obj_04 - type_1
    )

    (:init
        (pred_5 obj_11 obj_12)
        (pred_5 obj_12 obj_03)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_09 obj_08)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_03 obj_12)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_09 obj_06)
        (pred_5 obj_06 obj_02)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_02 obj_08)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_02 obj_06)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_08 obj_09)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_08 obj_11)
        (pred_5 obj_11 obj_08)
        (pred_5 obj_08 obj_03)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_06 obj_09)
        (pred_5 obj_12 obj_11)
        (pred_3 obj_01 obj_12)
        (pred_3 obj_04 obj_03)
        (pred_3 obj_05 obj_09)
        (pred_2 obj_04)
    )

    (:goal
        (and (pred_3 obj_01 obj_12) (pred_3 obj_05 obj_12))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_04 obj_11) (pred_3 obj_04 obj_12))) (not (and (pred_1 obj_04 obj_12) (pred_3 obj_04 obj_11)))))
  )
)

