
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-492774995)
    (:domain delivery)

    (:objects
        obj_07 obj_11 obj_17 obj_01 obj_08 obj_10 obj_05 obj_13 obj_14 obj_03 obj_15 obj_06 obj_16 obj_02 obj_12 obj_18 - type_3
        obj_09 - type_1
        obj_04 - type_4
    )

    (:init
        (pred_4 obj_15 obj_03)
        (pred_4 obj_14 obj_03)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_06 obj_13)
        (pred_4 obj_06 obj_18)
        (pred_4 obj_06 obj_15)
        (pred_4 obj_03 obj_14)
        (pred_4 obj_03 obj_02)
        (pred_4 obj_13 obj_05)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_02 obj_16)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_17 obj_11)
        (pred_4 obj_11 obj_07)
        (pred_4 obj_16 obj_02)
        (pred_4 obj_02 obj_03)
        (pred_4 obj_03 obj_15)
        (pred_4 obj_16 obj_14)
        (pred_4 obj_05 obj_17)
        (pred_4 obj_17 obj_05)
        (pred_4 obj_14 obj_08)
        (pred_4 obj_13 obj_01)
        (pred_4 obj_15 obj_05)
        (pred_4 obj_05 obj_10)
        (pred_4 obj_12 obj_02)
        (pred_4 obj_01 obj_17)
        (pred_4 obj_10 obj_03)
        (pred_4 obj_17 obj_01)
        (pred_4 obj_05 obj_15)
        (pred_4 obj_13 obj_06)
        (pred_4 obj_12 obj_15)
        (pred_4 obj_12 obj_18)
        (pred_4 obj_05 obj_13)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_07 obj_11)
        (pred_4 obj_11 obj_17)
        (pred_4 obj_08 obj_14)
        (pred_4 obj_10 obj_11)
        (pred_4 obj_01 obj_13)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_10 obj_08)
        (pred_4 obj_07 obj_08)
        (pred_4 obj_18 obj_12)
        (pred_4 obj_10 obj_05)
        (pred_4 obj_18 obj_06)
        (pred_4 obj_15 obj_12)
        (pred_4 obj_14 obj_16)
        (pred_4 obj_15 obj_06)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_04 obj_01)
        (pred_3 obj_04)
    )

    (:goal
        (pred_5 obj_09 obj_17)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_04 obj_10) (pred_5 obj_04 obj_03))) (not (and (pred_2 obj_04 obj_03) (pred_5 obj_04 obj_10)))))
  )
)

