
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-662957416)
    (:domain delivery)

    (:objects
        obj_02 obj_01 obj_03 obj_05 - type_3
        obj_06 - type_4
        obj_04 - type_1
    )

    (:init
        (pred_4 obj_02 obj_03)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_03 obj_02)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_03 obj_05)
        (pred_4 obj_05 obj_03)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_01 obj_05)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_06 obj_01)
        (pred_2 obj_04)
    )

    (:goal
        (pred_3 obj_06 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_04 obj_02) (pred_3 obj_04 obj_01))) (not (and (pred_5 obj_04 obj_01) (pred_3 obj_04 obj_02)))))
  )
)

