
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-904036921)
    (:domain delivery)

    (:objects
        obj_01 obj_06 obj_02 obj_04 - type_1
        obj_05 - type_4
        obj_03 - type_3
    )

    (:init
        (pred_1 obj_01 obj_02)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_06 obj_04)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_03 obj_04)
        (pred_5 obj_03)
    )

    (:goal
        (pred_2 obj_05 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_03 obj_06) (pred_2 obj_03 obj_04))) (not (and (pred_4 obj_03 obj_04) (pred_2 obj_03 obj_06)))))
  )
)

