
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1943180671)
    (:domain delivery)

    (:objects
        obj_06 obj_03 obj_11 obj_05 obj_18 obj_13 obj_12 obj_04 obj_16 obj_08 obj_09 obj_07 obj_15 obj_01 obj_10 obj_02 - type_3
        obj_14 - type_2
        obj_17 - type_1
    )

    (:init
        (pred_2 obj_09 obj_08)
        (pred_2 obj_16 obj_08)
        (pred_2 obj_08 obj_13)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_08 obj_16)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_04 obj_12)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_01 obj_15)
        (pred_2 obj_18 obj_06)
        (pred_2 obj_11 obj_03)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_15 obj_01)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_08 obj_09)
        (pred_2 obj_15 obj_16)
        (pred_2 obj_12 obj_11)
        (pred_2 obj_11 obj_12)
        (pred_2 obj_16 obj_18)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_12 obj_13)
        (pred_2 obj_10 obj_01)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_13 obj_08)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_10 obj_09)
        (pred_2 obj_10 obj_02)
        (pred_2 obj_12 obj_04)
        (pred_2 obj_18 obj_13)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_03 obj_11)
        (pred_2 obj_18 obj_16)
        (pred_2 obj_13 obj_03)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_03 obj_13)
        (pred_2 obj_13 obj_18)
        (pred_2 obj_06 obj_18)
        (pred_2 obj_02 obj_10)
        (pred_2 obj_13 obj_12)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_09 obj_10)
        (pred_2 obj_16 obj_15)
        (pred_2 obj_09 obj_07)
        (pred_3 obj_17 obj_02)
        (pred_3 obj_14 obj_01)
        (pred_4 obj_17)
    )

    (:goal
        (pred_3 obj_14 obj_16)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_17 obj_08) (pred_3 obj_17 obj_01))) (not (and (pred_1 obj_17 obj_01) (pred_3 obj_17 obj_08)))))
  )
)

