
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1413204420)
    (:domain delivery)

    (:objects
        obj_10 obj_03 obj_01 obj_11 obj_09 obj_08 obj_05 obj_02 obj_06 - type_1
        obj_04 - type_3
        obj_07 - type_2
    )

    (:init
        (pred_2 obj_09 obj_11)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_03 obj_10)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_09 obj_08)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_02 obj_09)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_08 obj_09)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_09 obj_02)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_10 obj_03)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_07 obj_01)
        (pred_4 obj_07)
    )

    (:goal
        (pred_5 obj_04 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_07 obj_11) (pred_5 obj_07 obj_05))) (not (and (pred_1 obj_07 obj_05) (pred_5 obj_07 obj_11)))))
  )
)

