
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-442447574)
    (:domain delivery)

    (:objects
        obj_02 obj_11 obj_12 obj_05 obj_09 obj_03 obj_06 obj_08 obj_10 - type_2
        obj_07 obj_01 - type_3
        obj_04 - type_4
    )

    (:init
        (pred_4 obj_03 obj_10)
        (pred_4 obj_10 obj_08)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_11 obj_09)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_09 obj_08)
        (pred_4 obj_09 obj_11)
        (pred_4 obj_08 obj_09)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_10 obj_03)
        (pred_2 obj_04 obj_08)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_01 obj_08)
        (pred_1 obj_04)
    )

    (:goal
        (and (pred_2 obj_07 obj_05) (pred_2 obj_01 obj_05))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_04 obj_09) (pred_2 obj_04 obj_08))) (not (and (pred_5 obj_04 obj_08) (pred_2 obj_04 obj_09)))))
  )
)

