
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1459766130)
    (:domain delivery)

    (:objects
        obj_12 obj_07 obj_10 obj_09 obj_04 obj_06 obj_02 obj_08 obj_01 - type_4
        obj_03 obj_11 - type_2
        obj_05 - type_1
    )

    (:init
        (pred_1 obj_06 obj_01)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_09 obj_12)
        (pred_1 obj_12 obj_07)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_07 obj_12)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_12 obj_09)
        (pred_1 obj_01 obj_06)
        (pred_5 obj_05 obj_08)
        (pred_5 obj_03 obj_02)
        (pred_5 obj_11 obj_10)
        (pred_4 obj_05)
    )

    (:goal
        (and (pred_5 obj_03 obj_02) (pred_5 obj_11 obj_02))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_05 obj_09) (pred_5 obj_05 obj_02))) (not (and (pred_2 obj_05 obj_02) (pred_5 obj_05 obj_09)))))
  )
)

