
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-722079790)
    (:domain delivery)

    (:objects
        obj_10 obj_16 obj_18 obj_07 obj_17 obj_19 obj_08 obj_04 obj_01 obj_05 obj_15 obj_13 obj_09 obj_06 obj_12 obj_03 - type_4
        obj_02 obj_11 - type_2
        obj_14 - type_3
    )

    (:init
        (pred_5 obj_18 obj_16)
        (pred_5 obj_08 obj_19)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_15 obj_08)
        (pred_5 obj_10 obj_17)
        (pred_5 obj_15 obj_12)
        (pred_5 obj_15 obj_13)
        (pred_5 obj_09 obj_01)
        (pred_5 obj_18 obj_07)
        (pred_5 obj_13 obj_15)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_17 obj_19)
        (pred_5 obj_09 obj_06)
        (pred_5 obj_06 obj_09)
        (pred_5 obj_18 obj_08)
        (pred_5 obj_13 obj_04)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_03 obj_13)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_12 obj_15)
        (pred_5 obj_19 obj_16)
        (pred_5 obj_13 obj_03)
        (pred_5 obj_03 obj_12)
        (pred_5 obj_16 obj_10)
        (pred_5 obj_08 obj_15)
        (pred_5 obj_08 obj_18)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_19 obj_05)
        (pred_5 obj_07 obj_18)
        (pred_5 obj_01 obj_05)
        (pred_5 obj_08 obj_04)
        (pred_5 obj_10 obj_16)
        (pred_5 obj_17 obj_01)
        (pred_5 obj_19 obj_17)
        (pred_5 obj_17 obj_10)
        (pred_5 obj_19 obj_08)
        (pred_5 obj_04 obj_08)
        (pred_5 obj_01 obj_17)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_04 obj_13)
        (pred_5 obj_05 obj_19)
        (pred_5 obj_12 obj_03)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_16 obj_19)
        (pred_5 obj_06 obj_05)
        (pred_3 obj_14 obj_12)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_11 obj_09)
        (pred_2 obj_14)
    )

    (:goal
        (and (pred_3 obj_02 obj_19) (pred_3 obj_11 obj_19))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_14 obj_16) (pred_3 obj_14 obj_19))) (not (and (pred_4 obj_14 obj_19) (pred_3 obj_14 obj_16)))))
  )
)

