
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1638679614)
    (:domain delivery)

    (:objects
        obj_08 obj_14 obj_11 obj_19 obj_02 obj_15 obj_06 obj_05 obj_10 obj_09 obj_12 obj_16 obj_13 obj_07 obj_18 obj_01 - type_4
        obj_17 obj_03 - type_1
        obj_04 - type_2
    )

    (:init
        (pred_5 obj_11 obj_14)
        (pred_5 obj_06 obj_15)
        (pred_5 obj_10 obj_13)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_12 obj_18)
        (pred_5 obj_12 obj_16)
        (pred_5 obj_13 obj_10)
        (pred_5 obj_11 obj_19)
        (pred_5 obj_16 obj_12)
        (pred_5 obj_07 obj_18)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_13 obj_07)
        (pred_5 obj_07 obj_13)
        (pred_5 obj_11 obj_06)
        (pred_5 obj_16 obj_05)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_09 obj_12)
        (pred_5 obj_01 obj_16)
        (pred_5 obj_14 obj_11)
        (pred_5 obj_18 obj_12)
        (pred_5 obj_15 obj_14)
        (pred_5 obj_16 obj_01)
        (pred_5 obj_01 obj_18)
        (pred_5 obj_14 obj_08)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_06 obj_11)
        (pred_5 obj_09 obj_07)
        (pred_5 obj_05 obj_19)
        (pred_5 obj_18 obj_07)
        (pred_5 obj_15 obj_09)
        (pred_5 obj_19 obj_11)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_08 obj_14)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_02 obj_08)
        (pred_5 obj_15 obj_06)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_12 obj_09)
        (pred_5 obj_05 obj_16)
        (pred_5 obj_09 obj_15)
        (pred_5 obj_18 obj_01)
        (pred_5 obj_19 obj_05)
        (pred_5 obj_14 obj_15)
        (pred_5 obj_07 obj_09)
        (pred_4 obj_04 obj_01)
        (pred_4 obj_17 obj_12)
        (pred_4 obj_03 obj_09)
        (pred_2 obj_04)
    )

    (:goal
        (and (pred_4 obj_17 obj_14) (pred_4 obj_03 obj_14))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_15) (pred_4 obj_04 obj_09))) (not (and (pred_3 obj_04 obj_09) (pred_4 obj_04 obj_15)))))
  )
)

