
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-834604113)
    (:domain delivery)

    (:objects
        obj_04 obj_13 obj_06 obj_14 obj_07 obj_10 obj_12 obj_17 obj_11 obj_18 obj_15 obj_16 obj_09 obj_02 obj_05 obj_01 - type_3
        obj_03 - type_4
        obj_08 - type_1
    )

    (:init
        (pred_5 obj_15 obj_18)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_18 obj_10)
        (pred_5 obj_16 obj_17)
        (pred_5 obj_16 obj_01)
        (pred_5 obj_16 obj_15)
        (pred_5 obj_18 obj_11)
        (pred_5 obj_18 obj_02)
        (pred_5 obj_17 obj_12)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_06 obj_13)
        (pred_5 obj_13 obj_04)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_02 obj_18)
        (pred_5 obj_18 obj_15)
        (pred_5 obj_09 obj_11)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_17 obj_14)
        (pred_5 obj_15 obj_12)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_05 obj_02)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_10 obj_18)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_12 obj_15)
        (pred_5 obj_17 obj_16)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_12 obj_17)
        (pred_5 obj_07 obj_10)
        (pred_5 obj_04 obj_13)
        (pred_5 obj_13 obj_06)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_10 obj_13)
        (pred_5 obj_14 obj_17)
        (pred_5 obj_13 obj_10)
        (pred_5 obj_10 obj_07)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_01 obj_05)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_01 obj_16)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_11 obj_09)
        (pred_5 obj_15 obj_16)
        (pred_2 obj_03 obj_13)
        (pred_2 obj_08 obj_18)
        (pred_4 obj_08)
    )

    (:goal
        (pred_2 obj_03 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_08 obj_12) (pred_2 obj_08 obj_15))) (not (and (pred_3 obj_08 obj_15) (pred_2 obj_08 obj_12)))))
  )
)

