
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-383045595)
    (:domain delivery)

    (:objects
        obj_02 obj_04 obj_06 obj_01 - type_4
        obj_07 obj_05 - type_3
        obj_03 - type_2
    )

    (:init
        (pred_1 obj_01 obj_04)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_02 obj_06)
        (pred_4 obj_03 obj_04)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_07 obj_04)
        (pred_5 obj_03)
    )

    (:goal
        (and (pred_4 obj_07 obj_06) (pred_4 obj_05 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_02) (pred_4 obj_03 obj_04))) (not (and (pred_3 obj_03 obj_04) (pred_4 obj_03 obj_02)))))
  )
)

