
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1049833474)
    (:domain delivery)

    (:objects
        obj_08 obj_01 obj_17 obj_16 obj_02 obj_14 obj_09 obj_11 obj_04 obj_10 obj_05 obj_03 obj_18 obj_12 obj_15 obj_13 - type_1
        obj_07 - type_2
        obj_06 - type_4
    )

    (:init
        (pred_3 obj_05 obj_10)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_10 obj_14)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_03 obj_13)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_10 obj_12)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_12 obj_15)
        (pred_3 obj_12 obj_18)
        (pred_3 obj_02 obj_08)
        (pred_3 obj_17 obj_01)
        (pred_3 obj_01 obj_08)
        (pred_3 obj_18 obj_12)
        (pred_3 obj_12 obj_10)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_18 obj_04)
        (pred_3 obj_09 obj_17)
        (pred_3 obj_17 obj_09)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_11 obj_16)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_09 obj_14)
        (pred_3 obj_15 obj_12)
        (pred_3 obj_16 obj_17)
        (pred_3 obj_14 obj_10)
        (pred_3 obj_17 obj_16)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_15 obj_05)
        (pred_3 obj_15 obj_13)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_02 obj_14)
        (pred_3 obj_08 obj_01)
        (pred_3 obj_01 obj_17)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_14 obj_01)
        (pred_3 obj_16 obj_11)
        (pred_3 obj_01 obj_14)
        (pred_3 obj_14 obj_02)
        (pred_3 obj_08 obj_02)
        (pred_3 obj_13 obj_15)
        (pred_3 obj_14 obj_09)
        (pred_3 obj_13 obj_03)
        (pred_3 obj_05 obj_15)
        (pred_3 obj_04 obj_18)
        (pred_3 obj_05 obj_03)
        (pred_4 obj_06 obj_16)
        (pred_4 obj_07 obj_02)
        (pred_1 obj_06)
    )

    (:goal
        (pred_4 obj_07 obj_16)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_06 obj_17) (pred_4 obj_06 obj_16))) (not (and (pred_2 obj_06 obj_16) (pred_4 obj_06 obj_17)))))
  )
)

