
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-2000934666)
    (:domain delivery)

    (:objects
        obj_14 obj_10 obj_11 obj_04 obj_19 obj_02 obj_16 obj_12 obj_18 obj_13 obj_05 obj_01 obj_07 obj_03 obj_17 obj_09 - type_1
        obj_08 obj_15 - type_2
        obj_06 - type_4
    )

    (:init
        (pred_2 obj_11 obj_10)
        (pred_2 obj_16 obj_02)
        (pred_2 obj_18 obj_07)
        (pred_2 obj_05 obj_16)
        (pred_2 obj_14 obj_19)
        (pred_2 obj_05 obj_17)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_07 obj_18)
        (pred_2 obj_11 obj_04)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_03 obj_17)
        (pred_2 obj_19 obj_02)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_11 obj_16)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_13 obj_18)
        (pred_2 obj_13 obj_05)
        (pred_2 obj_09 obj_01)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_17 obj_05)
        (pred_2 obj_02 obj_10)
        (pred_2 obj_01 obj_09)
        (pred_2 obj_09 obj_17)
        (pred_2 obj_10 obj_14)
        (pred_2 obj_16 obj_05)
        (pred_2 obj_16 obj_11)
        (pred_2 obj_13 obj_03)
        (pred_2 obj_12 obj_04)
        (pred_2 obj_17 obj_03)
        (pred_2 obj_02 obj_13)
        (pred_2 obj_04 obj_11)
        (pred_2 obj_18 obj_13)
        (pred_2 obj_16 obj_12)
        (pred_2 obj_14 obj_10)
        (pred_2 obj_19 obj_18)
        (pred_2 obj_02 obj_19)
        (pred_2 obj_19 obj_14)
        (pred_2 obj_02 obj_16)
        (pred_2 obj_12 obj_16)
        (pred_2 obj_18 obj_19)
        (pred_2 obj_05 obj_13)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_13 obj_02)
        (pred_2 obj_17 obj_09)
        (pred_2 obj_04 obj_12)
        (pred_2 obj_10 obj_02)
        (pred_2 obj_03 obj_13)
        (pred_3 obj_15 obj_01)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_06 obj_01)
        (pred_4 obj_06)
    )

    (:goal
        (and (pred_3 obj_08 obj_03) (pred_3 obj_15 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_06 obj_10) (pred_3 obj_06 obj_02))) (not (and (pred_1 obj_06 obj_02) (pred_3 obj_06 obj_10)))))
  )
)

