
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-811716294)
    (:domain delivery)

    (:objects
        obj_17 obj_12 obj_08 obj_13 obj_16 obj_01 obj_07 obj_11 obj_15 obj_04 obj_10 obj_18 obj_06 obj_14 obj_09 obj_03 - type_1
        obj_19 obj_02 - type_3
        obj_05 - type_4
    )

    (:init
        (pred_5 obj_08 obj_12)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_15 obj_06)
        (pred_5 obj_10 obj_07)
        (pred_5 obj_17 obj_16)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_10 obj_18)
        (pred_5 obj_06 obj_15)
        (pred_5 obj_08 obj_13)
        (pred_5 obj_18 obj_10)
        (pred_5 obj_14 obj_09)
        (pred_5 obj_16 obj_01)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_18 obj_11)
        (pred_5 obj_04 obj_15)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_03 obj_18)
        (pred_5 obj_12 obj_08)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_18 obj_03)
        (pred_5 obj_03 obj_09)
        (pred_5 obj_12 obj_17)
        (pred_5 obj_07 obj_10)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_04 obj_14)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_09 obj_14)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_13 obj_08)
        (pred_5 obj_15 obj_04)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_17 obj_12)
        (pred_5 obj_16 obj_15)
        (pred_5 obj_01 obj_16)
        (pred_5 obj_16 obj_17)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_15 obj_16)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_14 obj_04)
        (pred_3 obj_19 obj_03)
        (pred_3 obj_05 obj_17)
        (pred_3 obj_02 obj_15)
        (pred_4 obj_05)
    )

    (:goal
        (and (pred_3 obj_19 obj_17) (pred_3 obj_02 obj_17))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_05 obj_13) (pred_3 obj_05 obj_11))) (not (and (pred_1 obj_05 obj_11) (pred_3 obj_05 obj_13)))))
  )
)

