
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1101490552)
    (:domain delivery)

    (:objects
        obj_05 obj_06 obj_16 obj_08 obj_14 obj_11 obj_07 obj_17 obj_10 obj_02 obj_12 obj_03 obj_13 obj_04 obj_18 obj_09 - type_3
        obj_15 - type_4
        obj_01 - type_1
    )

    (:init
        (pred_4 obj_12 obj_02)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_03 obj_17)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_02 obj_10)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_17 obj_07)
        (pred_4 obj_04 obj_18)
        (pred_4 obj_04 obj_13)
        (pred_4 obj_14 obj_05)
        (pred_4 obj_16 obj_06)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_13 obj_04)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_13 obj_10)
        (pred_4 obj_07 obj_16)
        (pred_4 obj_16 obj_07)
        (pred_4 obj_10 obj_14)
        (pred_4 obj_17 obj_08)
        (pred_4 obj_12 obj_07)
        (pred_4 obj_07 obj_11)
        (pred_4 obj_18 obj_04)
        (pred_4 obj_08 obj_16)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_16 obj_08)
        (pred_4 obj_07 obj_12)
        (pred_4 obj_17 obj_03)
        (pred_4 obj_18 obj_12)
        (pred_4 obj_18 obj_09)
        (pred_4 obj_07 obj_17)
        (pred_4 obj_14 obj_11)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_06 obj_16)
        (pred_4 obj_14 obj_10)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_08 obj_17)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_11 obj_14)
        (pred_4 obj_05 obj_14)
        (pred_4 obj_09 obj_18)
        (pred_4 obj_11 obj_07)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_12 obj_18)
        (pred_4 obj_10 obj_13)
        (pred_4 obj_12 obj_03)
        (pred_2 obj_15 obj_05)
        (pred_2 obj_01 obj_14)
        (pred_3 obj_01)
    )

    (:goal
        (pred_2 obj_15 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_01 obj_08) (pred_2 obj_01 obj_17))) (not (and (pred_5 obj_01 obj_17) (pred_2 obj_01 obj_08)))))
  )
)

