
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-984798736)
    (:domain delivery)

    (:objects
        obj_03 obj_08 obj_02 obj_01 obj_06 obj_05 obj_09 obj_07 obj_11 - type_3
        obj_04 - type_4
        obj_10 - type_2
    )

    (:init
        (pred_4 obj_06 obj_01)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_08 obj_03)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_07 obj_11)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_01 obj_06)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_11 obj_07)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_03 obj_08)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_10 obj_02)
        (pred_1 obj_10)
    )

    (:goal
        (pred_3 obj_04 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_10 obj_08) (pred_3 obj_10 obj_06))) (not (and (pred_5 obj_10 obj_06) (pred_3 obj_10 obj_08)))))
  )
)

