
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1322940333)
    (:domain delivery)

    (:objects
        obj_19 obj_17 obj_09 obj_02 obj_07 obj_08 obj_01 obj_05 obj_06 obj_12 obj_15 obj_13 obj_04 obj_16 obj_18 obj_10 - type_3
        obj_11 obj_14 - type_1
        obj_03 - type_4
    )

    (:init
        (pred_5 obj_09 obj_17)
        (pred_5 obj_01 obj_08)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_15 obj_01)
        (pred_5 obj_19 obj_07)
        (pred_5 obj_15 obj_18)
        (pred_5 obj_15 obj_13)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_13 obj_15)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_04 obj_16)
        (pred_5 obj_16 obj_04)
        (pred_5 obj_09 obj_01)
        (pred_5 obj_13 obj_05)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_12 obj_15)
        (pred_5 obj_10 obj_13)
        (pred_5 obj_17 obj_09)
        (pred_5 obj_18 obj_15)
        (pred_5 obj_08 obj_17)
        (pred_5 obj_13 obj_10)
        (pred_5 obj_10 obj_18)
        (pred_5 obj_17 obj_19)
        (pred_5 obj_01 obj_15)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_12 obj_16)
        (pred_5 obj_05 obj_02)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_01 obj_05)
        (pred_5 obj_19 obj_17)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_07 obj_19)
        (pred_5 obj_08 obj_01)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_15 obj_12)
        (pred_5 obj_05 obj_13)
        (pred_5 obj_12 obj_08)
        (pred_5 obj_18 obj_10)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_17 obj_08)
        (pred_5 obj_16 obj_12)
        (pred_2 obj_11 obj_13)
        (pred_2 obj_14 obj_04)
        (pred_2 obj_03 obj_08)
        (pred_1 obj_03)
    )

    (:goal
        (and (pred_2 obj_11 obj_12) (pred_2 obj_14 obj_12))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_06) (pred_2 obj_03 obj_04))) (not (and (pred_3 obj_03 obj_04) (pred_2 obj_03 obj_06)))))
  )
)

