
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1982598746)
    (:domain delivery)

    (:objects
        obj_16 obj_12 obj_09 obj_01 obj_18 obj_08 obj_05 obj_10 obj_02 obj_15 obj_03 obj_04 obj_14 obj_13 obj_11 obj_06 - type_3
        obj_07 - type_1
        obj_17 - type_4
    )

    (:init
        (pred_4 obj_03 obj_15)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_15 obj_08)
        (pred_4 obj_04 obj_10)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_04 obj_03)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_15 obj_13)
        (pred_4 obj_10 obj_05)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_13 obj_14)
        (pred_4 obj_18 obj_16)
        (pred_4 obj_09 obj_12)
        (pred_4 obj_12 obj_16)
        (pred_4 obj_14 obj_13)
        (pred_4 obj_13 obj_15)
        (pred_4 obj_15 obj_03)
        (pred_4 obj_14 obj_02)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_02 obj_18)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_03 obj_05)
        (pred_4 obj_05 obj_08)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_08 obj_15)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_05 obj_03)
        (pred_4 obj_10 obj_04)
        (pred_4 obj_11 obj_03)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_05 obj_10)
        (pred_4 obj_18 obj_08)
        (pred_4 obj_16 obj_12)
        (pred_4 obj_12 obj_09)
        (pred_4 obj_18 obj_02)
        (pred_4 obj_08 obj_12)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_12 obj_08)
        (pred_4 obj_08 obj_18)
        (pred_4 obj_16 obj_18)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_08 obj_05)
        (pred_4 obj_06 obj_04)
        (pred_4 obj_03 obj_11)
        (pred_4 obj_02 obj_14)
        (pred_4 obj_03 obj_04)
        (pred_5 obj_17 obj_11)
        (pred_5 obj_07 obj_09)
        (pred_2 obj_17)
    )

    (:goal
        (pred_5 obj_07 obj_13)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_17 obj_12) (pred_5 obj_17 obj_08))) (not (and (pred_3 obj_17 obj_08) (pred_5 obj_17 obj_12)))))
  )
)

