
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-155445047)
    (:domain delivery)

    (:objects
        obj_16 obj_03 obj_02 obj_09 obj_14 obj_06 obj_08 obj_18 obj_12 obj_11 obj_15 obj_10 obj_07 obj_05 obj_04 obj_01 - type_1
        obj_13 - type_4
        obj_17 - type_3
    )

    (:init
        (pred_3 obj_15 obj_11)
        (pred_3 obj_12 obj_11)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_10 obj_18)
        (pred_3 obj_10 obj_01)
        (pred_3 obj_10 obj_15)
        (pred_3 obj_11 obj_12)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_18 obj_08)
        (pred_3 obj_05 obj_04)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_14 obj_16)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_03 obj_16)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_11 obj_15)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_08 obj_02)
        (pred_3 obj_02 obj_08)
        (pred_3 obj_12 obj_14)
        (pred_3 obj_18 obj_09)
        (pred_3 obj_15 obj_08)
        (pred_3 obj_08 obj_06)
        (pred_3 obj_04 obj_05)
        (pred_3 obj_09 obj_02)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_02 obj_09)
        (pred_3 obj_08 obj_15)
        (pred_3 obj_18 obj_10)
        (pred_3 obj_04 obj_15)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_08 obj_18)
        (pred_3 obj_14 obj_06)
        (pred_3 obj_16 obj_03)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_14 obj_12)
        (pred_3 obj_06 obj_03)
        (pred_3 obj_09 obj_18)
        (pred_3 obj_03 obj_06)
        (pred_3 obj_06 obj_14)
        (pred_3 obj_16 obj_14)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_06 obj_08)
        (pred_3 obj_01 obj_10)
        (pred_3 obj_15 obj_04)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_15 obj_10)
        (pred_1 obj_17 obj_11)
        (pred_1 obj_13 obj_02)
        (pred_5 obj_17)
    )

    (:goal
        (pred_1 obj_13 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_17 obj_12) (pred_1 obj_17 obj_07))) (not (and (pred_2 obj_17 obj_07) (pred_1 obj_17 obj_12)))))
  )
)

