
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-16547142)
    (:domain delivery)

    (:objects
        obj_11 obj_12 obj_17 obj_15 obj_13 obj_04 obj_10 obj_09 obj_08 obj_06 obj_01 obj_03 obj_18 obj_14 obj_02 obj_07 - type_3
        obj_05 - type_2
        obj_16 - type_4
    )

    (:init
        (pred_5 obj_01 obj_06)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_03 obj_09)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_03 obj_01)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_14 obj_02)
        (pred_5 obj_14 obj_18)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_17 obj_12)
        (pred_5 obj_12 obj_11)
        (pred_5 obj_18 obj_14)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_18 obj_08)
        (pred_5 obj_10 obj_17)
        (pred_5 obj_17 obj_10)
        (pred_5 obj_08 obj_13)
        (pred_5 obj_09 obj_15)
        (pred_5 obj_01 obj_10)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_02 obj_14)
        (pred_5 obj_15 obj_17)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_17 obj_15)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_02 obj_01)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_13 obj_04)
        (pred_5 obj_11 obj_12)
        (pred_5 obj_12 obj_17)
        (pred_5 obj_13 obj_08)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_15 obj_09)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_04 obj_13)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_07 obj_03)
        (pred_5 obj_01 obj_02)
        (pred_5 obj_08 obj_18)
        (pred_5 obj_01 obj_03)
        (pred_2 obj_16 obj_04)
        (pred_2 obj_05 obj_18)
        (pred_3 obj_16)
    )

    (:goal
        (pred_2 obj_05 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_16 obj_08) (pred_2 obj_16 obj_18))) (not (and (pred_4 obj_16 obj_18) (pred_2 obj_16 obj_08)))))
  )
)

