
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1422912272)
    (:domain delivery)

    (:objects
        obj_17 obj_03 obj_19 obj_08 obj_15 obj_05 obj_11 obj_07 obj_18 obj_02 obj_04 obj_06 obj_14 obj_13 obj_12 obj_10 - type_3
        obj_01 obj_16 - type_1
        obj_09 - type_4
    )

    (:init
        (pred_5 obj_19 obj_03)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_18 obj_14)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_17 obj_15)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_14 obj_18)
        (pred_5 obj_19 obj_08)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_13 obj_12)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_14 obj_13)
        (pred_5 obj_13 obj_14)
        (pred_5 obj_19 obj_11)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_02 obj_18)
        (pred_5 obj_02 obj_04)
        (pred_5 obj_10 obj_06)
        (pred_5 obj_03 obj_19)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_05 obj_03)
        (pred_5 obj_06 obj_10)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_03 obj_17)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_11 obj_19)
        (pred_5 obj_02 obj_13)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_12 obj_13)
        (pred_5 obj_05 obj_02)
        (pred_5 obj_08 obj_19)
        (pred_5 obj_18 obj_02)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_17 obj_03)
        (pred_5 obj_15 obj_18)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_15 obj_17)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_18 obj_15)
        (pred_5 obj_04 obj_02)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_03 obj_05)
        (pred_5 obj_13 obj_02)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_16 obj_18)
        (pred_2 obj_09)
    )

    (:goal
        (and (pred_1 obj_01 obj_02) (pred_1 obj_16 obj_02))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_09 obj_05) (pred_1 obj_09 obj_02))) (not (and (pred_3 obj_09 obj_02) (pred_1 obj_09 obj_05)))))
  )
)

