
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1033420020)
    (:domain delivery)

    (:objects
        obj_06 obj_05 obj_11 obj_01 obj_02 obj_03 obj_12 obj_07 obj_08 - type_4
        obj_09 obj_04 - type_2
        obj_10 - type_3
    )

    (:init
        (pred_5 obj_03 obj_08)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_11 obj_03)
        (pred_5 obj_01 obj_02)
        (pred_5 obj_03 obj_11)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_12 obj_07)
        (pred_5 obj_05 obj_02)
        (pred_5 obj_07 obj_12)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_02 obj_01)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_02 obj_03)
        (pred_5 obj_03 obj_02)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_08 obj_03)
        (pred_4 obj_09 obj_11)
        (pred_4 obj_04 obj_12)
        (pred_4 obj_10 obj_05)
        (pred_3 obj_10)
    )

    (:goal
        (and (pred_4 obj_09 obj_08) (pred_4 obj_04 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_10 obj_11) (pred_4 obj_10 obj_03))) (not (and (pred_1 obj_10 obj_03) (pred_4 obj_10 obj_11)))))
  )
)

