
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1461441017)
    (:domain delivery)

    (:objects
        obj_09 obj_12 obj_10 obj_05 obj_07 obj_11 obj_06 obj_03 obj_01 - type_1
        obj_08 obj_02 - type_4
        obj_04 - type_3
    )

    (:init
        (pred_2 obj_11 obj_01)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_12 obj_07)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_11 obj_07)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_07 obj_12)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_01 obj_11)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_04 obj_03)
        (pred_1 obj_04)
    )

    (:goal
        (and (pred_4 obj_08 obj_07) (pred_4 obj_02 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_12) (pred_4 obj_04 obj_07))) (not (and (pred_3 obj_04 obj_07) (pred_4 obj_04 obj_12)))))
  )
)

