
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1635402819)
    (:domain delivery)

    (:objects
        obj_09 obj_08 obj_06 obj_10 obj_03 obj_02 obj_04 obj_12 obj_11 - type_3
        obj_07 obj_05 - type_2
        obj_01 - type_4
    )

    (:init
        (pred_3 obj_02 obj_11)
        (pred_3 obj_11 obj_12)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_06 obj_02)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_02 obj_06)
        (pred_3 obj_12 obj_11)
        (pred_3 obj_06 obj_08)
        (pred_3 obj_10 obj_09)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_08 obj_06)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_03 obj_12)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_11 obj_02)
        (pred_4 obj_01 obj_06)
        (pred_4 obj_07 obj_10)
        (pred_4 obj_05 obj_03)
        (pred_2 obj_01)
    )

    (:goal
        (and (pred_4 obj_07 obj_06) (pred_4 obj_05 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_01 obj_08) (pred_4 obj_01 obj_03))) (not (and (pred_5 obj_01 obj_03) (pred_4 obj_01 obj_08)))))
  )
)

