
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-2089990452)
    (:domain delivery)

    (:objects
        obj_13 obj_04 obj_06 obj_17 obj_01 obj_14 obj_05 obj_18 obj_07 obj_15 obj_10 obj_11 obj_12 obj_08 obj_02 obj_03 - type_1
        obj_09 - type_4
        obj_16 - type_2
    )

    (:init
        (pred_3 obj_10 obj_15)
        (pred_3 obj_07 obj_15)
        (pred_3 obj_15 obj_14)
        (pred_3 obj_11 obj_18)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_15 obj_07)
        (pred_3 obj_15 obj_08)
        (pred_3 obj_18 obj_05)
        (pred_3 obj_08 obj_02)
        (pred_3 obj_08 obj_12)
        (pred_3 obj_01 obj_13)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_04 obj_13)
        (pred_3 obj_12 obj_08)
        (pred_3 obj_08 obj_15)
        (pred_3 obj_15 obj_10)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_05 obj_06)
        (pred_3 obj_06 obj_05)
        (pred_3 obj_07 obj_01)
        (pred_3 obj_18 obj_17)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_05 obj_14)
        (pred_3 obj_02 obj_08)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_14 obj_15)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_05 obj_10)
        (pred_3 obj_18 obj_11)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_05 obj_18)
        (pred_3 obj_01 obj_14)
        (pred_3 obj_13 obj_04)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_17 obj_18)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_14 obj_01)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_14 obj_05)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_10 obj_02)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_10 obj_11)
        (pred_2 obj_16 obj_02)
        (pred_2 obj_09 obj_13)
        (pred_4 obj_16)
    )

    (:goal
        (pred_2 obj_09 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_16 obj_13) (pred_2 obj_16 obj_04))) (not (and (pred_5 obj_16 obj_04) (pred_2 obj_16 obj_13)))))
  )
)

