
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1132460923)
    (:domain delivery)

    (:objects
        obj_01 obj_04 obj_12 obj_06 obj_03 obj_10 obj_11 obj_07 obj_08 - type_4
        obj_02 obj_05 - type_1
        obj_09 - type_3
    )

    (:init
        (pred_5 obj_10 obj_08)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_11 obj_06)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_06 obj_11)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_07 obj_03)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_08 obj_10)
        (pred_3 obj_05 obj_08)
        (pred_3 obj_09 obj_12)
        (pred_3 obj_02 obj_03)
        (pred_2 obj_09)
    )

    (:goal
        (and (pred_3 obj_02 obj_01) (pred_3 obj_05 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_09 obj_04) (pred_3 obj_09 obj_03))) (not (and (pred_4 obj_09 obj_03) (pred_3 obj_09 obj_04)))))
  )
)

