
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-690958005)
    (:domain delivery)

    (:objects
        obj_10 obj_12 obj_04 obj_01 obj_09 obj_06 obj_03 obj_07 obj_11 - type_3
        obj_08 obj_05 - type_2
        obj_02 - type_4
    )

    (:init
        (pred_4 obj_06 obj_11)
        (pred_4 obj_11 obj_07)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_06 obj_04)
        (pred_4 obj_07 obj_11)
        (pred_4 obj_04 obj_12)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_10 obj_12)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_12 obj_09)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_12 obj_10)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_12 obj_04)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_09 obj_12)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_11 obj_06)
        (pred_5 obj_02 obj_04)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_05 obj_04)
        (pred_1 obj_02)
    )

    (:goal
        (and (pred_5 obj_08 obj_11) (pred_5 obj_05 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_02 obj_10) (pred_5 obj_02 obj_12))) (not (and (pred_2 obj_02 obj_12) (pred_5 obj_02 obj_10)))))
  )
)

