
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-15527977)
    (:domain delivery)

    (:objects
        obj_11 obj_03 obj_02 obj_10 obj_04 obj_12 obj_06 obj_01 obj_08 - type_3
        obj_07 obj_09 - type_2
        obj_05 - type_4
    )

    (:init
        (pred_1 obj_12 obj_08)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_10 obj_04)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_11 obj_03)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_03 obj_04)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_03 obj_11)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_04 obj_10)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_04 obj_12)
        (pred_1 obj_12 obj_04)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_04 obj_03)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_08 obj_12)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_09 obj_01)
        (pred_4 obj_05)
    )

    (:goal
        (and (pred_2 obj_07 obj_03) (pred_2 obj_09 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_05 obj_04) (pred_2 obj_05 obj_01))) (not (and (pred_5 obj_05 obj_01) (pred_2 obj_05 obj_04)))))
  )
)

