
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-37796718)
    (:domain delivery)

    (:objects
        obj_05 obj_04 obj_14 obj_07 obj_17 obj_12 obj_01 obj_18 obj_09 obj_11 obj_10 obj_08 obj_13 obj_15 obj_02 obj_03 - type_4
        obj_06 - type_2
        obj_16 - type_3
    )

    (:init
        (pred_3 obj_10 obj_11)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_11 obj_12)
        (pred_3 obj_08 obj_18)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_08 obj_10)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_11 obj_15)
        (pred_3 obj_18 obj_01)
        (pred_3 obj_15 obj_02)
        (pred_3 obj_15 obj_13)
        (pred_3 obj_17 obj_05)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_04 obj_05)
        (pred_3 obj_13 obj_15)
        (pred_3 obj_15 obj_11)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_13 obj_09)
        (pred_3 obj_01 obj_14)
        (pred_3 obj_14 obj_01)
        (pred_3 obj_09 obj_17)
        (pred_3 obj_18 obj_07)
        (pred_3 obj_10 obj_01)
        (pred_3 obj_01 obj_12)
        (pred_3 obj_02 obj_15)
        (pred_3 obj_07 obj_14)
        (pred_3 obj_12 obj_11)
        (pred_3 obj_14 obj_07)
        (pred_3 obj_01 obj_10)
        (pred_3 obj_18 obj_08)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_01 obj_18)
        (pred_3 obj_17 obj_12)
        (pred_3 obj_05 obj_04)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_17 obj_09)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_07 obj_18)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_12 obj_17)
        (pred_3 obj_05 obj_17)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_12 obj_01)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_10 obj_02)
        (pred_3 obj_09 obj_13)
        (pred_3 obj_10 obj_08)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_16 obj_04)
        (pred_4 obj_16)
    )

    (:goal
        (pred_2 obj_06 obj_11)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_16 obj_10) (pred_2 obj_16 obj_08))) (not (and (pred_1 obj_16 obj_08) (pred_2 obj_16 obj_10)))))
  )
)

