
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1558051475)
    (:domain delivery)

    (:objects
        obj_09 obj_05 obj_01 obj_12 obj_06 obj_02 obj_08 obj_04 obj_07 - type_3
        obj_10 obj_03 - type_2
        obj_11 - type_1
    )

    (:init
        (pred_2 obj_02 obj_07)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_08 obj_12)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_12 obj_06)
        (pred_2 obj_02 obj_01)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_08 obj_04)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_04 obj_08)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_12 obj_08)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_06 obj_04)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_04 obj_06)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_07 obj_02)
        (pred_4 obj_03 obj_08)
        (pred_4 obj_11 obj_09)
        (pred_4 obj_10 obj_06)
        (pred_5 obj_11)
    )

    (:goal
        (and (pred_4 obj_10 obj_07) (pred_4 obj_03 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_11 obj_06) (pred_4 obj_11 obj_02))) (not (and (pred_3 obj_11 obj_02) (pred_4 obj_11 obj_06)))))
  )
)

