
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-123250076)
    (:domain delivery)

    (:objects
        obj_08 obj_09 obj_17 obj_14 obj_11 obj_12 obj_02 obj_03 obj_01 obj_05 obj_07 obj_13 obj_04 obj_18 obj_10 obj_15 - type_4
        obj_06 - type_3
        obj_16 - type_1
    )

    (:init
        (pred_1 obj_07 obj_05)
        (pred_1 obj_01 obj_05)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_13 obj_03)
        (pred_1 obj_13 obj_15)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_05 obj_01)
        (pred_1 obj_05 obj_18)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_18 obj_10)
        (pred_1 obj_18 obj_04)
        (pred_1 obj_11 obj_08)
        (pred_1 obj_17 obj_09)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_04 obj_18)
        (pred_1 obj_18 obj_05)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_02 obj_17)
        (pred_1 obj_17 obj_02)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_03 obj_14)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_10 obj_18)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_03 obj_13)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_12 obj_09)
        (pred_1 obj_14 obj_03)
        (pred_1 obj_09 obj_12)
        (pred_1 obj_12 obj_11)
        (pred_1 obj_08 obj_11)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_15 obj_13)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_07 obj_13)
        (pred_3 obj_16 obj_02)
        (pred_3 obj_06 obj_10)
        (pred_4 obj_16)
    )

    (:goal
        (pred_3 obj_06 obj_11)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_16 obj_11) (pred_3 obj_16 obj_12))) (not (and (pred_2 obj_16 obj_12) (pred_3 obj_16 obj_11)))))
  )
)

