
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-478393716)
    (:domain delivery)

    (:objects
        obj_10 obj_09 obj_01 obj_06 obj_04 obj_11 obj_03 obj_08 obj_05 - type_2
        obj_02 obj_07 - type_1
        obj_12 - type_4
    )

    (:init
        (pred_5 obj_11 obj_05)
        (pred_5 obj_05 obj_08)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_01 obj_11)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_11 obj_01)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_06 obj_10)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_09 obj_04)
        (pred_5 obj_08 obj_03)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_09 obj_01)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_04 obj_08)
        (pred_5 obj_04 obj_09)
        (pred_5 obj_08 obj_04)
        (pred_5 obj_10 obj_06)
        (pred_5 obj_05 obj_11)
        (pred_4 obj_12 obj_08)
        (pred_4 obj_07 obj_11)
        (pred_4 obj_02 obj_11)
        (pred_3 obj_12)
    )

    (:goal
        (and (pred_4 obj_02 obj_08) (pred_4 obj_07 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_12 obj_04) (pred_4 obj_12 obj_08))) (not (and (pred_2 obj_12 obj_08) (pred_4 obj_12 obj_04)))))
  )
)

