
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-380062698)
    (:domain delivery)

    (:objects
        obj_01 obj_13 obj_10 obj_05 obj_19 obj_18 obj_04 obj_11 obj_15 obj_03 obj_02 obj_12 obj_06 obj_17 obj_14 obj_07 - type_3
        obj_09 obj_08 - type_4
        obj_16 - type_2
    )

    (:init
        (pred_3 obj_10 obj_13)
        (pred_3 obj_04 obj_18)
        (pred_3 obj_15 obj_06)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_01 obj_19)
        (pred_3 obj_02 obj_14)
        (pred_3 obj_02 obj_12)
        (pred_3 obj_06 obj_15)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_12 obj_02)
        (pred_3 obj_17 obj_14)
        (pred_3 obj_19 obj_18)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_12 obj_11)
        (pred_3 obj_03 obj_15)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_13 obj_10)
        (pred_3 obj_14 obj_02)
        (pred_3 obj_18 obj_13)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_07 obj_14)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_03 obj_17)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_14 obj_17)
        (pred_3 obj_18 obj_03)
        (pred_3 obj_05 obj_10)
        (pred_3 obj_15 obj_03)
        (pred_3 obj_04 obj_11)
        (pred_3 obj_01 obj_13)
        (pred_3 obj_19 obj_15)
        (pred_3 obj_18 obj_19)
        (pred_3 obj_19 obj_01)
        (pred_3 obj_18 obj_04)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_15 obj_19)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_11 obj_12)
        (pred_3 obj_03 obj_18)
        (pred_3 obj_14 obj_07)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_13 obj_18)
        (pred_3 obj_17 obj_03)
        (pred_2 obj_09 obj_13)
        (pred_2 obj_16 obj_15)
        (pred_2 obj_08 obj_04)
        (pred_5 obj_16)
    )

    (:goal
        (and (pred_2 obj_09 obj_13) (pred_2 obj_08 obj_13))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_16 obj_10) (pred_2 obj_16 obj_04))) (not (and (pred_4 obj_16 obj_04) (pred_2 obj_16 obj_10)))))
  )
)

