
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1592694632)
    (:domain delivery)

    (:objects
        obj_07 obj_01 obj_09 obj_04 obj_05 obj_06 obj_10 obj_03 obj_12 - type_4
        obj_08 obj_02 - type_2
        obj_11 - type_1
    )

    (:init
        (pred_3 obj_06 obj_12)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_09 obj_06)
        (pred_3 obj_04 obj_05)
        (pred_3 obj_06 obj_09)
        (pred_3 obj_03 obj_12)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_07 obj_01)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_01 obj_05)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_05 obj_04)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_05 obj_06)
        (pred_3 obj_06 obj_05)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_05 obj_01)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_12 obj_06)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_11 obj_01)
        (pred_1 obj_11)
    )

    (:goal
        (and (pred_2 obj_08 obj_03) (pred_2 obj_02 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_11 obj_01) (pred_2 obj_11 obj_05))) (not (and (pred_5 obj_11 obj_05) (pred_2 obj_11 obj_01)))))
  )
)

