
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-85953268)
    (:domain delivery)

    (:objects
        obj_14 obj_08 obj_07 obj_09 obj_02 obj_15 obj_04 obj_06 obj_03 obj_01 obj_16 obj_17 obj_12 obj_18 obj_11 obj_05 - type_1
        obj_13 obj_19 - type_4
        obj_10 - type_3
    )

    (:init
        (pred_4 obj_07 obj_08)
        (pred_4 obj_04 obj_15)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_16 obj_04)
        (pred_4 obj_14 obj_02)
        (pred_4 obj_16 obj_11)
        (pred_4 obj_16 obj_17)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_17 obj_16)
        (pred_4 obj_18 obj_11)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_12 obj_18)
        (pred_4 obj_18 obj_12)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_17 obj_06)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_01 obj_16)
        (pred_4 obj_05 obj_17)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_11 obj_16)
        (pred_4 obj_15 obj_08)
        (pred_4 obj_17 obj_05)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_08 obj_14)
        (pred_4 obj_04 obj_16)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_01 obj_18)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_11 obj_18)
        (pred_4 obj_15 obj_01)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_14 obj_08)
        (pred_4 obj_02 obj_03)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_02 obj_14)
        (pred_4 obj_15 obj_04)
        (pred_4 obj_06 obj_04)
        (pred_4 obj_03 obj_02)
        (pred_4 obj_16 obj_01)
        (pred_4 obj_06 obj_17)
        (pred_4 obj_01 obj_15)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_08 obj_15)
        (pred_4 obj_18 obj_01)
        (pred_2 obj_13 obj_14)
        (pred_2 obj_19 obj_01)
        (pred_2 obj_10 obj_12)
        (pred_3 obj_10)
    )

    (:goal
        (and (pred_2 obj_13 obj_01) (pred_2 obj_19 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_10 obj_08) (pred_2 obj_10 obj_15))) (not (and (pred_1 obj_10 obj_15) (pred_2 obj_10 obj_08)))))
  )
)

