
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1826225914)
    (:domain delivery)

    (:objects
        obj_02 obj_03 obj_07 obj_09 obj_06 obj_04 obj_11 obj_08 obj_10 - type_3
        obj_05 - type_4
        obj_01 - type_1
    )

    (:init
        (pred_2 obj_06 obj_09)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_02 obj_09)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_08 obj_11)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_06 obj_04)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_11 obj_08)
        (pred_2 obj_04 obj_06)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_09 obj_02)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_02 obj_03)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_05 obj_03)
        (pred_4 obj_01)
    )

    (:goal
        (pred_5 obj_05 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_07) (pred_5 obj_01 obj_04))) (not (and (pred_1 obj_01 obj_04) (pred_5 obj_01 obj_07)))))
  )
)

