
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-831661123)
    (:domain delivery)

    (:objects
        obj_01 obj_05 obj_06 obj_09 obj_10 obj_02 obj_07 obj_11 obj_12 - type_1
        obj_03 obj_08 - type_4
        obj_04 - type_3
    )

    (:init
        (pred_4 obj_02 obj_12)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_09 obj_10)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_07 obj_11)
        (pred_4 obj_05 obj_10)
        (pred_4 obj_11 obj_07)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_10 obj_09)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_02 obj_10)
        (pred_4 obj_10 obj_11)
        (pred_4 obj_10 obj_05)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_12 obj_02)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_04 obj_07)
        (pred_5 obj_04)
    )

    (:goal
        (and (pred_1 obj_03 obj_11) (pred_1 obj_08 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_10) (pred_1 obj_04 obj_11))) (not (and (pred_3 obj_04 obj_11) (pred_1 obj_04 obj_10)))))
  )
)

