
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1733610165)
    (:domain delivery)

    (:objects
        obj_05 obj_10 obj_07 obj_09 obj_01 obj_06 obj_08 obj_03 obj_02 - type_4
        obj_11 - type_3
        obj_04 - type_1
    )

    (:init
        (pred_2 obj_01 obj_09)
        (pred_2 obj_06 obj_07)
        (pred_2 obj_10 obj_05)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_09 obj_08)
        (pred_2 obj_03 obj_08)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_01 obj_06)
        (pred_2 obj_07 obj_06)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_09 obj_01)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_08 obj_03)
        (pred_2 obj_06 obj_01)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_08 obj_09)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_10 obj_01)
        (pred_2 obj_05 obj_10)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_11 obj_10)
        (pred_1 obj_04)
    )

    (:goal
        (pred_5 obj_11 obj_08)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_04 obj_09) (pred_5 obj_04 obj_08))) (not (and (pred_4 obj_04 obj_08) (pred_5 obj_04 obj_09)))))
  )
)

