
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-2088995096)
    (:domain delivery)

    (:objects
        obj_09 obj_10 obj_08 obj_03 obj_04 obj_05 obj_01 obj_11 obj_02 - type_4
        obj_06 - type_3
        obj_07 - type_1
    )

    (:init
        (pred_2 obj_04 obj_03)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_10 obj_09)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_08 obj_05)
        (pred_2 obj_11 obj_04)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_02 obj_11)
        (pred_2 obj_04 obj_11)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_09 obj_10)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_06 obj_10)
        (pred_5 obj_07)
    )

    (:goal
        (pred_1 obj_06 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_07 obj_03) (pred_1 obj_07 obj_01))) (not (and (pred_4 obj_07 obj_01) (pred_1 obj_07 obj_03)))))
  )
)

