
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-2007378429)
    (:domain delivery)

    (:objects
        obj_05 obj_02 obj_08 obj_11 obj_04 obj_07 obj_06 obj_10 obj_01 - type_1
        obj_09 - type_2
        obj_03 - type_3
    )

    (:init
        (pred_5 obj_04 obj_11)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_11 obj_06)
        (pred_5 obj_10 obj_06)
        (pred_5 obj_02 obj_08)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_06 obj_10)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_01 obj_10)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_06 obj_11)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_04 obj_02)
        (pred_5 obj_02 obj_04)
        (pred_5 obj_05 obj_02)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_09 obj_01)
        (pred_2 obj_03)
    )

    (:goal
        (pred_3 obj_09 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_03 obj_02) (pred_3 obj_03 obj_08))) (not (and (pred_4 obj_03 obj_08) (pred_3 obj_03 obj_02)))))
  )
)

