
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1602527196)
    (:domain delivery)

    (:objects
        obj_15 obj_11 obj_10 obj_04 obj_02 obj_17 obj_06 obj_07 obj_16 obj_08 obj_03 obj_09 obj_18 obj_12 obj_13 obj_05 - type_1
        obj_01 - type_4
        obj_14 - type_2
    )

    (:init
        (pred_5 obj_03 obj_08)
        (pred_5 obj_16 obj_08)
        (pred_5 obj_08 obj_17)
        (pred_5 obj_09 obj_07)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_08 obj_16)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_12 obj_13)
        (pred_5 obj_12 obj_18)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_11 obj_15)
        (pred_5 obj_18 obj_12)
        (pred_5 obj_12 obj_08)
        (pred_5 obj_08 obj_03)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_06 obj_10)
        (pred_5 obj_10 obj_06)
        (pred_5 obj_16 obj_02)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_06 obj_17)
        (pred_5 obj_13 obj_12)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_17 obj_08)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_07 obj_09)
        (pred_5 obj_13 obj_03)
        (pred_5 obj_13 obj_05)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_02 obj_17)
        (pred_5 obj_15 obj_11)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_02 obj_16)
        (pred_5 obj_17 obj_11)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_11 obj_17)
        (pred_5 obj_17 obj_02)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_05 obj_13)
        (pred_5 obj_17 obj_06)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_03 obj_13)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_03 obj_09)
        (pred_3 obj_14 obj_16)
        (pred_3 obj_01 obj_18)
        (pred_4 obj_14)
    )

    (:goal
        (pred_3 obj_01 obj_13)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_14 obj_18) (pred_3 obj_14 obj_12))) (not (and (pred_2 obj_14 obj_12) (pred_3 obj_14 obj_18)))))
  )
)

