
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1341275381)
    (:domain delivery)

    (:objects
        obj_02 obj_03 obj_04 obj_06 obj_12 obj_01 obj_10 obj_05 obj_09 - type_3
        obj_08 obj_07 - type_2
        obj_11 - type_4
    )

    (:init
        (pred_1 obj_01 obj_09)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_04 obj_03)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_03 obj_12)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_03 obj_04)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_12 obj_03)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_09 obj_01)
        (pred_4 obj_11 obj_04)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_08 obj_01)
        (pred_2 obj_11)
    )

    (:goal
        (and (pred_4 obj_08 obj_02) (pred_4 obj_07 obj_02))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_11 obj_02) (pred_4 obj_11 obj_03))) (not (and (pred_3 obj_11 obj_03) (pred_4 obj_11 obj_02)))))
  )
)

