
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-387365132)
    (:domain delivery)

    (:objects
        obj_04 obj_18 obj_13 obj_03 obj_17 obj_05 obj_14 obj_19 obj_16 obj_07 obj_11 obj_15 obj_10 obj_08 obj_12 obj_01 - type_4
        obj_02 obj_09 - type_2
        obj_06 - type_1
    )

    (:init
        (pred_2 obj_13 obj_18)
        (pred_2 obj_14 obj_05)
        (pred_2 obj_16 obj_10)
        (pred_2 obj_11 obj_14)
        (pred_2 obj_04 obj_17)
        (pred_2 obj_11 obj_12)
        (pred_2 obj_11 obj_15)
        (pred_2 obj_10 obj_16)
        (pred_2 obj_13 obj_03)
        (pred_2 obj_15 obj_11)
        (pred_2 obj_08 obj_12)
        (pred_2 obj_17 obj_05)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_13 obj_14)
        (pred_2 obj_15 obj_19)
        (pred_2 obj_07 obj_16)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_01 obj_15)
        (pred_2 obj_18 obj_13)
        (pred_2 obj_12 obj_11)
        (pred_2 obj_05 obj_18)
        (pred_2 obj_15 obj_01)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_18 obj_04)
        (pred_2 obj_14 obj_11)
        (pred_2 obj_14 obj_13)
        (pred_2 obj_07 obj_08)
        (pred_2 obj_19 obj_03)
        (pred_2 obj_12 obj_08)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_03 obj_13)
        (pred_2 obj_16 obj_07)
        (pred_2 obj_14 obj_19)
        (pred_2 obj_04 obj_18)
        (pred_2 obj_17 obj_16)
        (pred_2 obj_05 obj_17)
        (pred_2 obj_17 obj_04)
        (pred_2 obj_05 obj_14)
        (pred_2 obj_19 obj_14)
        (pred_2 obj_16 obj_17)
        (pred_2 obj_11 obj_07)
        (pred_2 obj_19 obj_15)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_03 obj_19)
        (pred_2 obj_18 obj_05)
        (pred_2 obj_08 obj_07)
        (pred_1 obj_02 obj_17)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_06 obj_11)
        (pred_3 obj_06)
    )

    (:goal
        (and (pred_1 obj_02 obj_01) (pred_1 obj_09 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_06 obj_14) (pred_1 obj_06 obj_19))) (not (and (pred_4 obj_06 obj_19) (pred_1 obj_06 obj_14)))))
  )
)

