
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-2078524936)
    (:domain delivery)

    (:objects
        obj_03 obj_02 obj_01 obj_04 obj_08 obj_05 obj_10 obj_11 obj_09 - type_3
        obj_07 - type_4
        obj_06 - type_1
    )

    (:init
        (pred_3 obj_08 obj_04)
        (pred_3 obj_05 obj_01)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_03 obj_04)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_02 obj_01)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_08 obj_05)
        (pred_3 obj_01 obj_05)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_10 obj_11)
        (pred_3 obj_05 obj_08)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_04 obj_03)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_01 obj_02)
        (pred_3 obj_08 obj_02)
        (pred_3 obj_02 obj_08)
        (pred_3 obj_03 obj_02)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_06 obj_01)
        (pred_4 obj_06)
    )

    (:goal
        (pred_1 obj_07 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_06 obj_02) (pred_1 obj_06 obj_08))) (not (and (pred_5 obj_06 obj_08) (pred_1 obj_06 obj_02)))))
  )
)

