
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1641606917)
    (:domain delivery)

    (:objects
        obj_13 obj_06 obj_12 obj_15 obj_11 obj_10 obj_01 obj_08 obj_16 obj_03 obj_17 obj_07 obj_18 obj_09 obj_05 obj_04 - type_2
        obj_14 - type_4
        obj_02 - type_3
    )

    (:init
        (pred_1 obj_17 obj_03)
        (pred_1 obj_16 obj_03)
        (pred_1 obj_03 obj_10)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_07 obj_17)
        (pred_1 obj_03 obj_16)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_09 obj_18)
        (pred_1 obj_11 obj_13)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_18 obj_09)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_18 obj_16)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_16 obj_11)
        (pred_1 obj_08 obj_15)
        (pred_1 obj_17 obj_01)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_15 obj_12)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_12 obj_15)
        (pred_1 obj_01 obj_17)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_05 obj_17)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_11 obj_16)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_15 obj_08)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_13 obj_11)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_17 obj_05)
        (pred_1 obj_16 obj_18)
        (pred_1 obj_17 obj_07)
        (pred_3 obj_14 obj_06)
        (pred_3 obj_02 obj_08)
        (pred_4 obj_02)
    )

    (:goal
        (pred_3 obj_14 obj_09)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_02 obj_06) (pred_3 obj_02 obj_10))) (not (and (pred_5 obj_02 obj_10) (pred_3 obj_02 obj_06)))))
  )
)

