
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-28544022)
    (:domain delivery)

    (:objects
        obj_18 obj_15 obj_17 obj_04 obj_07 obj_03 obj_08 obj_05 obj_19 obj_02 obj_12 obj_14 obj_09 obj_16 obj_06 obj_11 - type_1
        obj_13 obj_10 - type_3
        obj_01 - type_4
    )

    (:init
        (pred_5 obj_17 obj_15)
        (pred_5 obj_08 obj_03)
        (pred_5 obj_19 obj_09)
        (pred_5 obj_12 obj_08)
        (pred_5 obj_18 obj_07)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_12 obj_14)
        (pred_5 obj_09 obj_19)
        (pred_5 obj_17 obj_04)
        (pred_5 obj_14 obj_12)
        (pred_5 obj_16 obj_06)
        (pred_5 obj_07 obj_03)
        (pred_5 obj_09 obj_16)
        (pred_5 obj_16 obj_09)
        (pred_5 obj_17 obj_08)
        (pred_5 obj_14 obj_05)
        (pred_5 obj_02 obj_19)
        (pred_5 obj_02 obj_12)
        (pred_5 obj_11 obj_14)
        (pred_5 obj_15 obj_17)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_03 obj_15)
        (pred_5 obj_14 obj_11)
        (pred_5 obj_11 obj_06)
        (pred_5 obj_15 obj_18)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_08 obj_17)
        (pred_5 obj_02 obj_16)
        (pred_5 obj_05 obj_04)
        (pred_5 obj_06 obj_16)
        (pred_5 obj_03 obj_02)
        (pred_5 obj_04 obj_17)
        (pred_5 obj_19 obj_02)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_18 obj_15)
        (pred_5 obj_07 obj_19)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_07 obj_18)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_05 obj_08)
        (pred_5 obj_19 obj_07)
        (pred_5 obj_12 obj_02)
        (pred_5 obj_05 obj_14)
        (pred_5 obj_02 obj_03)
        (pred_5 obj_06 obj_11)
        (pred_5 obj_04 obj_05)
        (pred_5 obj_15 obj_03)
        (pred_5 obj_16 obj_02)
        (pred_2 obj_10 obj_06)
        (pred_2 obj_01 obj_14)
        (pred_2 obj_13 obj_06)
        (pred_3 obj_01)
    )

    (:goal
        (and (pred_2 obj_13 obj_04) (pred_2 obj_10 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_17) (pred_2 obj_01 obj_04))) (not (and (pred_1 obj_01 obj_04) (pred_2 obj_01 obj_17)))))
  )
)

