
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-603329360)
    (:domain delivery)

    (:objects
        obj_16 obj_13 obj_05 obj_07 obj_12 obj_11 obj_06 obj_01 obj_10 obj_03 obj_14 obj_04 obj_08 obj_18 obj_15 obj_09 - type_1
        obj_17 obj_19 - type_2
        obj_02 - type_4
    )

    (:init
        (pred_5 obj_05 obj_13)
        (pred_5 obj_06 obj_11)
        (pred_5 obj_10 obj_08)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_16 obj_12)
        (pred_5 obj_14 obj_15)
        (pred_5 obj_14 obj_04)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_05 obj_07)
        (pred_5 obj_04 obj_14)
        (pred_5 obj_18 obj_15)
        (pred_5 obj_12 obj_11)
        (pred_5 obj_08 obj_18)
        (pred_5 obj_18 obj_08)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_03 obj_14)
        (pred_5 obj_09 obj_04)
        (pred_5 obj_13 obj_05)
        (pred_5 obj_15 obj_14)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_04 obj_09)
        (pred_5 obj_09 obj_15)
        (pred_5 obj_13 obj_16)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_03 obj_18)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_15 obj_18)
        (pred_5 obj_11 obj_03)
        (pred_5 obj_07 obj_05)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_16 obj_13)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_11 obj_12)
        (pred_5 obj_12 obj_16)
        (pred_5 obj_11 obj_06)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_14 obj_03)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_03 obj_11)
        (pred_5 obj_15 obj_09)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_18 obj_03)
        (pred_4 obj_19 obj_18)
        (pred_4 obj_17 obj_07)
        (pred_4 obj_02 obj_11)
        (pred_1 obj_02)
    )

    (:goal
        (and (pred_4 obj_17 obj_16) (pred_4 obj_19 obj_16))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_02 obj_11) (pred_4 obj_02 obj_03))) (not (and (pred_3 obj_02 obj_03) (pred_4 obj_02 obj_11)))))
  )
)

