
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1464092249)
    (:domain delivery)

    (:objects
        obj_08 obj_03 obj_11 obj_10 obj_17 obj_18 obj_06 obj_09 obj_02 obj_15 obj_12 obj_01 obj_16 obj_04 obj_14 obj_13 - type_1
        obj_05 - type_4
        obj_07 - type_3
    )

    (:init
        (pred_3 obj_12 obj_15)
        (pred_3 obj_02 obj_15)
        (pred_3 obj_15 obj_18)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_01 obj_13)
        (pred_3 obj_01 obj_12)
        (pred_3 obj_15 obj_02)
        (pred_3 obj_15 obj_04)
        (pred_3 obj_09 obj_06)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_04 obj_16)
        (pred_3 obj_17 obj_08)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_16 obj_04)
        (pred_3 obj_04 obj_15)
        (pred_3 obj_15 obj_12)
        (pred_3 obj_16 obj_02)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_02 obj_17)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_12 obj_06)
        (pred_3 obj_06 obj_18)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_10 obj_11)
        (pred_3 obj_18 obj_15)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_06 obj_12)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_14 obj_12)
        (pred_3 obj_14 obj_13)
        (pred_3 obj_06 obj_09)
        (pred_3 obj_17 obj_18)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_17 obj_02)
        (pred_3 obj_18 obj_03)
        (pred_3 obj_10 obj_09)
        (pred_3 obj_03 obj_18)
        (pred_3 obj_18 obj_17)
        (pred_3 obj_08 obj_17)
        (pred_3 obj_13 obj_14)
        (pred_3 obj_18 obj_06)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_12 obj_14)
        (pred_3 obj_02 obj_16)
        (pred_3 obj_12 obj_01)
        (pred_5 obj_07 obj_09)
        (pred_5 obj_05 obj_04)
        (pred_4 obj_07)
    )

    (:goal
        (pred_5 obj_05 obj_13)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_07 obj_14) (pred_5 obj_07 obj_13))) (not (and (pred_2 obj_07 obj_13) (pred_5 obj_07 obj_14)))))
  )
)

