
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-714606096)
    (:domain delivery)

    (:objects
        obj_02 obj_07 obj_05 obj_01 - type_1
        obj_06 obj_03 - type_2
        obj_04 - type_3
    )

    (:init
        (pred_4 obj_01 obj_07)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_02 obj_07)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_07 obj_01)
        (pred_4 obj_02 obj_05)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_06 obj_05)
        (pred_1 obj_04 obj_01)
        (pred_3 obj_04)
    )

    (:goal
        (and (pred_1 obj_06 obj_07) (pred_1 obj_03 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_04 obj_02) (pred_1 obj_04 obj_07))) (not (and (pred_2 obj_04 obj_07) (pred_1 obj_04 obj_02)))))
  )
)

