
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-45379556)
    (:domain delivery)

    (:objects
        obj_05 obj_03 obj_04 obj_06 - type_4
        obj_02 - type_2
        obj_01 - type_3
    )

    (:init
        (pred_5 obj_05 obj_04)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_04 obj_05)
        (pred_5 obj_05 obj_03)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_03 obj_05)
        (pred_5 obj_03 obj_06)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_01 obj_04)
        (pred_1 obj_01)
    )

    (:goal
        (pred_4 obj_02 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_01 obj_03) (pred_4 obj_01 obj_06))) (not (and (pred_2 obj_01 obj_06) (pred_4 obj_01 obj_03)))))
  )
)

