
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1058075248)
    (:domain delivery)

    (:objects
        obj_10 obj_07 obj_04 obj_03 obj_08 obj_06 obj_01 obj_09 obj_05 - type_3
        obj_11 - type_2
        obj_02 - type_1
    )

    (:init
        (pred_4 obj_08 obj_03)
        (pred_4 obj_06 obj_04)
        (pred_4 obj_07 obj_10)
        (pred_4 obj_10 obj_03)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_09 obj_08)
        (pred_4 obj_03 obj_08)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_08 obj_09)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_07 obj_08)
        (pred_4 obj_10 obj_07)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_11 obj_04)
        (pred_3 obj_02)
    )

    (:goal
        (pred_1 obj_11 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_02 obj_04) (pred_1 obj_02 obj_06))) (not (and (pred_2 obj_02 obj_06) (pred_1 obj_02 obj_04)))))
  )
)

