
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1378558384)
    (:domain delivery)

    (:objects
        obj_03 obj_05 obj_01 obj_06 obj_12 obj_10 obj_07 obj_02 obj_04 obj_17 obj_18 obj_09 obj_15 obj_14 obj_08 obj_19 - type_3
        obj_13 obj_11 - type_1
        obj_16 - type_4
    )

    (:init
        (pred_1 obj_01 obj_05)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_04 obj_15)
        (pred_1 obj_18 obj_07)
        (pred_1 obj_03 obj_12)
        (pred_1 obj_18 obj_08)
        (pred_1 obj_18 obj_09)
        (pred_1 obj_15 obj_04)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_09 obj_18)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_12 obj_10)
        (pred_1 obj_15 obj_14)
        (pred_1 obj_14 obj_15)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_17 obj_04)
        (pred_1 obj_17 obj_18)
        (pred_1 obj_19 obj_09)
        (pred_1 obj_05 obj_01)
        (pred_1 obj_08 obj_18)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_09 obj_19)
        (pred_1 obj_19 obj_08)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_07 obj_18)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_10 obj_17)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_04 obj_17)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_12 obj_04)
        (pred_1 obj_10 obj_12)
        (pred_1 obj_12 obj_03)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_04 obj_12)
        (pred_1 obj_18 obj_17)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_17 obj_10)
        (pred_1 obj_08 obj_19)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_14 obj_17)
        (pred_3 obj_16 obj_06)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_11 obj_17)
        (pred_4 obj_16)
    )

    (:goal
        (and (pred_3 obj_13 obj_15) (pred_3 obj_11 obj_15))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_16 obj_04) (pred_3 obj_16 obj_17))) (not (and (pred_5 obj_16 obj_17) (pred_3 obj_16 obj_04)))))
  )
)

