
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-494703891)
    (:domain delivery)

    (:objects
        obj_03 obj_16 obj_08 obj_11 obj_04 obj_01 obj_14 obj_07 obj_18 obj_13 obj_17 obj_02 obj_10 obj_15 obj_05 obj_09 - type_4
        obj_12 - type_3
        obj_06 - type_1
    )

    (:init
        (pred_5 obj_17 obj_13)
        (pred_5 obj_18 obj_13)
        (pred_5 obj_13 obj_01)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_02 obj_17)
        (pred_5 obj_13 obj_18)
        (pred_5 obj_13 obj_15)
        (pred_5 obj_07 obj_14)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_15 obj_10)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_08 obj_16)
        (pred_5 obj_16 obj_03)
        (pred_5 obj_10 obj_15)
        (pred_5 obj_15 obj_13)
        (pred_5 obj_13 obj_17)
        (pred_5 obj_10 obj_18)
        (pred_5 obj_14 obj_08)
        (pred_5 obj_08 obj_14)
        (pred_5 obj_18 obj_04)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_17 obj_14)
        (pred_5 obj_14 obj_01)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_11 obj_08)
        (pred_5 obj_01 obj_13)
        (pred_5 obj_08 obj_11)
        (pred_5 obj_14 obj_17)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_05 obj_17)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_14 obj_07)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_03 obj_16)
        (pred_5 obj_16 obj_08)
        (pred_5 obj_04 obj_18)
        (pred_5 obj_01 obj_16)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_16 obj_01)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_01 obj_14)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_17 obj_05)
        (pred_5 obj_18 obj_10)
        (pred_5 obj_17 obj_02)
        (pred_2 obj_12 obj_05)
        (pred_2 obj_06 obj_04)
        (pred_1 obj_06)
    )

    (:goal
        (pred_2 obj_12 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_06 obj_04) (pred_2 obj_06 obj_01))) (not (and (pred_3 obj_06 obj_01) (pred_2 obj_06 obj_04)))))
  )
)

