
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1485395477)
    (:domain delivery)

    (:objects
        obj_10 obj_09 obj_11 obj_08 obj_07 obj_02 obj_03 obj_01 obj_06 - type_4
        obj_04 - type_3
        obj_05 - type_1
    )

    (:init
        (pred_1 obj_07 obj_08)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_09 obj_10)
        (pred_1 obj_10 obj_08)
        (pred_1 obj_08 obj_03)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_09 obj_11)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_08 obj_10)
        (pred_1 obj_03 obj_08)
        (pred_1 obj_11 obj_09)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_10 obj_09)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_04 obj_06)
        (pred_4 obj_05)
    )

    (:goal
        (pred_5 obj_04 obj_08)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_05 obj_08) (pred_5 obj_05 obj_07))) (not (and (pred_3 obj_05 obj_07) (pred_5 obj_05 obj_08)))))
  )
)

