
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-156704968)
    (:domain delivery)

    (:objects
        obj_12 obj_05 obj_15 obj_10 obj_08 obj_02 obj_07 obj_09 obj_11 obj_06 obj_13 obj_16 obj_17 obj_14 obj_03 obj_01 - type_3
        obj_18 - type_4
        obj_04 - type_1
    )

    (:init
        (pred_1 obj_13 obj_06)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_16 obj_09)
        (pred_1 obj_16 obj_01)
        (pred_1 obj_16 obj_13)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_06 obj_14)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_14 obj_03)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_08 obj_12)
        (pred_1 obj_15 obj_05)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_17 obj_11)
        (pred_1 obj_07 obj_15)
        (pred_1 obj_15 obj_07)
        (pred_1 obj_11 obj_08)
        (pred_1 obj_09 obj_10)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_03 obj_14)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_09 obj_16)
        (pred_1 obj_03 obj_13)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_05 obj_15)
        (pred_1 obj_08 obj_11)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_10 obj_09)
        (pred_1 obj_05 obj_02)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_12 obj_08)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_01 obj_16)
        (pred_1 obj_13 obj_03)
        (pred_1 obj_11 obj_17)
        (pred_1 obj_13 obj_16)
        (pred_5 obj_04 obj_13)
        (pred_5 obj_18 obj_15)
        (pred_4 obj_04)
    )

    (:goal
        (pred_5 obj_18 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_04 obj_05) (pred_5 obj_04 obj_02))) (not (and (pred_2 obj_04 obj_02) (pred_5 obj_04 obj_05)))))
  )
)

