
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-982670166)
    (:domain delivery)

    (:objects
        obj_11 obj_04 obj_17 obj_15 obj_16 obj_10 obj_05 obj_02 obj_03 obj_06 obj_12 obj_18 obj_07 obj_09 obj_13 obj_01 - type_2
        obj_08 - type_3
        obj_14 - type_4
    )

    (:init
        (pred_4 obj_12 obj_06)
        (pred_4 obj_03 obj_06)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_18 obj_02)
        (pred_4 obj_18 obj_01)
        (pred_4 obj_18 obj_12)
        (pred_4 obj_06 obj_03)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_09 obj_13)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_16 obj_11)
        (pred_4 obj_17 obj_04)
        (pred_4 obj_04 obj_11)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_06 obj_12)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_05 obj_17)
        (pred_4 obj_17 obj_05)
        (pred_4 obj_03 obj_16)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_12 obj_05)
        (pred_4 obj_05 obj_10)
        (pred_4 obj_13 obj_09)
        (pred_4 obj_15 obj_17)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_17 obj_15)
        (pred_4 obj_05 obj_12)
        (pred_4 obj_02 obj_18)
        (pred_4 obj_13 obj_12)
        (pred_4 obj_13 obj_01)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_11 obj_04)
        (pred_4 obj_04 obj_17)
        (pred_4 obj_16 obj_03)
        (pred_4 obj_10 obj_04)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_04 obj_10)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_11 obj_16)
        (pred_4 obj_01 obj_13)
        (pred_4 obj_10 obj_05)
        (pred_4 obj_01 obj_18)
        (pred_4 obj_12 obj_13)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_12 obj_18)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_08 obj_05)
        (pred_2 obj_14)
    )

    (:goal
        (pred_1 obj_08 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_14 obj_10) (pred_1 obj_14 obj_06))) (not (and (pred_3 obj_14 obj_06) (pred_1 obj_14 obj_10)))))
  )
)

