
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1845272899)
    (:domain delivery)

    (:objects
        obj_08 obj_10 obj_03 obj_17 obj_16 obj_04 obj_01 obj_13 obj_15 obj_14 obj_07 obj_18 obj_09 obj_05 obj_12 obj_06 - type_2
        obj_02 - type_3
        obj_11 - type_1
    )

    (:init
        (pred_3 obj_07 obj_14)
        (pred_3 obj_15 obj_14)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_18 obj_13)
        (pred_3 obj_18 obj_06)
        (pred_3 obj_18 obj_07)
        (pred_3 obj_14 obj_15)
        (pred_3 obj_14 obj_05)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_05 obj_12)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_16 obj_08)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_10 obj_08)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_05 obj_14)
        (pred_3 obj_14 obj_07)
        (pred_3 obj_09 obj_15)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_15 obj_16)
        (pred_3 obj_13 obj_17)
        (pred_3 obj_07 obj_01)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_12 obj_05)
        (pred_3 obj_17 obj_03)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_03 obj_17)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_13 obj_18)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_12 obj_06)
        (pred_3 obj_01 obj_13)
        (pred_3 obj_16 obj_04)
        (pred_3 obj_08 obj_10)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_16 obj_15)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_17 obj_13)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_04 obj_16)
        (pred_3 obj_08 obj_16)
        (pred_3 obj_06 obj_12)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_06 obj_18)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_15 obj_09)
        (pred_3 obj_07 obj_18)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_02 obj_04)
        (pred_1 obj_11)
    )

    (:goal
        (pred_4 obj_02 obj_13)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_11 obj_01) (pred_4 obj_11 obj_13))) (not (and (pred_5 obj_11 obj_13) (pred_4 obj_11 obj_01)))))
  )
)

