
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-403278457)
    (:domain delivery)

    (:objects
        obj_08 obj_04 obj_09 obj_05 obj_14 obj_02 obj_18 obj_06 obj_01 obj_12 obj_13 obj_10 obj_11 obj_16 obj_03 obj_15 - type_1
        obj_17 obj_07 - type_3
        obj_19 - type_4
    )

    (:init
        (pred_1 obj_09 obj_04)
        (pred_1 obj_18 obj_02)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_13 obj_18)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_13 obj_03)
        (pred_1 obj_13 obj_10)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_10 obj_13)
        (pred_1 obj_16 obj_03)
        (pred_1 obj_14 obj_02)
        (pred_1 obj_11 obj_16)
        (pred_1 obj_16 obj_11)
        (pred_1 obj_09 obj_18)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_12 obj_13)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_03 obj_13)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_18 obj_13)
        (pred_1 obj_18 obj_09)
        (pred_1 obj_12 obj_16)
        (pred_1 obj_06 obj_05)
        (pred_1 obj_03 obj_16)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_18 obj_06)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_14 obj_01)
        (pred_1 obj_02 obj_14)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_02 obj_18)
        (pred_1 obj_06 obj_18)
        (pred_1 obj_01 obj_14)
        (pred_1 obj_13 obj_12)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_05 obj_06)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_16 obj_12)
        (pred_3 obj_17 obj_02)
        (pred_3 obj_19 obj_16)
        (pred_3 obj_07 obj_05)
        (pred_2 obj_19)
    )

    (:goal
        (and (pred_3 obj_17 obj_05) (pred_3 obj_07 obj_05))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_19 obj_04) (pred_3 obj_19 obj_02))) (not (and (pred_4 obj_19 obj_02) (pred_3 obj_19 obj_04)))))
  )
)

