
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-513644286)
    (:domain delivery)

    (:objects
        obj_17 obj_09 obj_01 obj_08 obj_19 obj_15 obj_10 obj_04 obj_18 obj_07 obj_13 obj_16 obj_05 obj_06 obj_02 obj_12 - type_1
        obj_03 obj_14 - type_4
        obj_11 - type_2
    )

    (:init
        (pred_3 obj_01 obj_09)
        (pred_3 obj_10 obj_15)
        (pred_3 obj_18 obj_05)
        (pred_3 obj_13 obj_10)
        (pred_3 obj_17 obj_19)
        (pred_3 obj_13 obj_02)
        (pred_3 obj_13 obj_16)
        (pred_3 obj_05 obj_18)
        (pred_3 obj_01 obj_08)
        (pred_3 obj_16 obj_13)
        (pred_3 obj_06 obj_02)
        (pred_3 obj_19 obj_15)
        (pred_3 obj_05 obj_06)
        (pred_3 obj_06 obj_05)
        (pred_3 obj_01 obj_10)
        (pred_3 obj_16 obj_04)
        (pred_3 obj_07 obj_18)
        (pred_3 obj_07 obj_13)
        (pred_3 obj_12 obj_16)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_02 obj_13)
        (pred_3 obj_15 obj_09)
        (pred_3 obj_16 obj_12)
        (pred_3 obj_12 obj_02)
        (pred_3 obj_09 obj_17)
        (pred_3 obj_10 obj_13)
        (pred_3 obj_10 obj_01)
        (pred_3 obj_07 obj_06)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_02 obj_06)
        (pred_3 obj_15 obj_07)
        (pred_3 obj_08 obj_01)
        (pred_3 obj_18 obj_07)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_17 obj_09)
        (pred_3 obj_19 obj_18)
        (pred_3 obj_15 obj_19)
        (pred_3 obj_19 obj_17)
        (pred_3 obj_15 obj_10)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_18 obj_19)
        (pred_3 obj_13 obj_07)
        (pred_3 obj_04 obj_16)
        (pred_3 obj_07 obj_15)
        (pred_3 obj_02 obj_12)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_09 obj_15)
        (pred_3 obj_06 obj_07)
        (pred_5 obj_14 obj_02)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_11 obj_17)
        (pred_2 obj_11)
    )

    (:goal
        (and (pred_5 obj_03 obj_02) (pred_5 obj_14 obj_02))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_11 obj_10) (pred_5 obj_11 obj_04))) (not (and (pred_4 obj_11 obj_04) (pred_5 obj_11 obj_10)))))
  )
)

