
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1539170978)
    (:domain delivery)

    (:objects
        obj_04 obj_02 obj_14 obj_11 obj_08 obj_18 obj_03 obj_06 obj_05 obj_01 obj_09 obj_13 obj_12 obj_10 obj_15 obj_07 - type_4
        obj_16 - type_2
        obj_17 - type_1
    )

    (:init
        (pred_2 obj_09 obj_01)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_01 obj_18)
        (pred_2 obj_13 obj_06)
        (pred_2 obj_13 obj_07)
        (pred_2 obj_13 obj_09)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_10 obj_15)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_08 obj_04)
        (pred_2 obj_14 obj_02)
        (pred_2 obj_02 obj_04)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_10 obj_01)
        (pred_2 obj_01 obj_09)
        (pred_2 obj_12 obj_05)
        (pred_2 obj_03 obj_14)
        (pred_2 obj_14 obj_03)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_06 obj_11)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_03 obj_18)
        (pred_2 obj_15 obj_10)
        (pred_2 obj_11 obj_14)
        (pred_2 obj_18 obj_01)
        (pred_2 obj_14 obj_11)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_06 obj_13)
        (pred_2 obj_15 obj_09)
        (pred_2 obj_15 obj_07)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_08 obj_18)
        (pred_2 obj_04 obj_02)
        (pred_2 obj_02 obj_14)
        (pred_2 obj_08 obj_05)
        (pred_2 obj_18 obj_02)
        (pred_2 obj_11 obj_06)
        (pred_2 obj_02 obj_18)
        (pred_2 obj_18 obj_08)
        (pred_2 obj_04 obj_08)
        (pred_2 obj_07 obj_15)
        (pred_2 obj_18 obj_03)
        (pred_2 obj_07 obj_13)
        (pred_2 obj_09 obj_15)
        (pred_2 obj_05 obj_12)
        (pred_2 obj_09 obj_13)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_16 obj_11)
        (pred_1 obj_17)
    )

    (:goal
        (pred_3 obj_16 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_17 obj_14) (pred_3 obj_17 obj_11))) (not (and (pred_4 obj_17 obj_11) (pred_3 obj_17 obj_14)))))
  )
)

