
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1104660384)
    (:domain delivery)

    (:objects
        obj_09 obj_08 obj_11 obj_01 obj_05 obj_04 obj_03 obj_06 obj_10 - type_4
        obj_07 - type_1
        obj_02 - type_2
    )

    (:init
        (pred_3 obj_05 obj_01)
        (pred_3 obj_04 obj_11)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_06 obj_03)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_05 obj_04)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_06 obj_05)
        (pred_3 obj_01 obj_05)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_03 obj_06)
        (pred_3 obj_04 obj_05)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_05 obj_06)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_05 obj_08)
        (pred_3 obj_08 obj_05)
        (pred_3 obj_09 obj_08)
        (pred_5 obj_02 obj_06)
        (pred_5 obj_07 obj_10)
        (pred_2 obj_02)
    )

    (:goal
        (pred_5 obj_07 obj_09)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_02 obj_08) (pred_5 obj_02 obj_11))) (not (and (pred_4 obj_02 obj_11) (pred_5 obj_02 obj_08)))))
  )
)

