
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-223101634)
    (:domain delivery)

    (:objects
        obj_03 obj_04 obj_08 obj_17 obj_15 obj_12 obj_16 obj_07 obj_09 obj_14 obj_19 obj_06 obj_11 obj_13 obj_02 obj_10 - type_3
        obj_01 obj_05 - type_1
        obj_18 - type_2
    )

    (:init
        (pred_4 obj_08 obj_04)
        (pred_4 obj_16 obj_12)
        (pred_4 obj_09 obj_11)
        (pred_4 obj_19 obj_16)
        (pred_4 obj_03 obj_15)
        (pred_4 obj_19 obj_02)
        (pred_4 obj_19 obj_06)
        (pred_4 obj_11 obj_09)
        (pred_4 obj_08 obj_17)
        (pred_4 obj_06 obj_19)
        (pred_4 obj_13 obj_02)
        (pred_4 obj_15 obj_12)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_08 obj_16)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_14 obj_09)
        (pred_4 obj_14 obj_19)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_04 obj_08)
        (pred_4 obj_02 obj_19)
        (pred_4 obj_12 obj_04)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_04 obj_03)
        (pred_4 obj_16 obj_19)
        (pred_4 obj_16 obj_08)
        (pred_4 obj_14 obj_13)
        (pred_4 obj_07 obj_17)
        (pred_4 obj_02 obj_13)
        (pred_4 obj_12 obj_14)
        (pred_4 obj_17 obj_08)
        (pred_4 obj_09 obj_14)
        (pred_4 obj_16 obj_07)
        (pred_4 obj_03 obj_04)
        (pred_4 obj_15 obj_09)
        (pred_4 obj_12 obj_15)
        (pred_4 obj_15 obj_03)
        (pred_4 obj_12 obj_16)
        (pred_4 obj_07 obj_16)
        (pred_4 obj_09 obj_15)
        (pred_4 obj_19 obj_14)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_14 obj_12)
        (pred_4 obj_02 obj_10)
        (pred_4 obj_17 obj_07)
        (pred_4 obj_04 obj_12)
        (pred_4 obj_13 obj_14)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_18 obj_13)
        (pred_3 obj_18)
    )

    (:goal
        (and (pred_1 obj_01 obj_11) (pred_1 obj_05 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_18 obj_09) (pred_1 obj_18 obj_11))) (not (and (pred_5 obj_18 obj_11) (pred_1 obj_18 obj_09)))))
  )
)

