
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1575374835)
    (:domain delivery)

    (:objects
        obj_12 obj_10 obj_09 obj_06 obj_05 obj_08 obj_07 obj_11 obj_04 - type_2
        obj_01 obj_02 - type_3
        obj_03 - type_4
    )

    (:init
        (pred_5 obj_08 obj_04)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_09 obj_08)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_08 obj_09)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_10 obj_05)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_05 obj_08)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_04 obj_08)
        (pred_3 obj_01 obj_10)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_02 obj_11)
        (pred_1 obj_03)
    )

    (:goal
        (and (pred_3 obj_01 obj_07) (pred_3 obj_02 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_03 obj_12) (pred_3 obj_03 obj_06))) (not (and (pred_2 obj_03 obj_06) (pred_3 obj_03 obj_12)))))
  )
)

