
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1114626717)
    (:domain delivery)

    (:objects
        obj_18 obj_02 obj_15 obj_01 obj_10 obj_07 obj_13 obj_19 obj_16 obj_12 obj_11 obj_06 obj_04 obj_05 obj_09 obj_17 - type_3
        obj_14 obj_08 - type_4
        obj_03 - type_1
    )

    (:init
        (pred_4 obj_15 obj_02)
        (pred_4 obj_13 obj_07)
        (pred_4 obj_16 obj_04)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_18 obj_10)
        (pred_4 obj_11 obj_09)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_04 obj_16)
        (pred_4 obj_15 obj_01)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_10 obj_07)
        (pred_4 obj_04 obj_05)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_15 obj_13)
        (pred_4 obj_06 obj_19)
        (pred_4 obj_12 obj_16)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_17 obj_06)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_09 obj_11)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_06 obj_17)
        (pred_4 obj_17 obj_09)
        (pred_4 obj_02 obj_18)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_13 obj_15)
        (pred_4 obj_12 obj_05)
        (pred_4 obj_19 obj_01)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_07 obj_12)
        (pred_4 obj_01 obj_15)
        (pred_4 obj_16 obj_12)
        (pred_4 obj_13 obj_19)
        (pred_4 obj_18 obj_02)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_07 obj_10)
        (pred_4 obj_10 obj_18)
        (pred_4 obj_07 obj_13)
        (pred_4 obj_19 obj_13)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_19 obj_06)
        (pred_4 obj_12 obj_07)
        (pred_4 obj_09 obj_17)
        (pred_4 obj_01 obj_19)
        (pred_4 obj_02 obj_07)
        (pred_4 obj_05 obj_12)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_08 obj_18)
        (pred_1 obj_14 obj_13)
        (pred_5 obj_03)
    )

    (:goal
        (and (pred_1 obj_14 obj_04) (pred_1 obj_08 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_16) (pred_1 obj_03 obj_04))) (not (and (pred_3 obj_03 obj_04) (pred_1 obj_03 obj_16)))))
  )
)

