
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-322407604)
    (:domain delivery)

    (:objects
        obj_04 obj_07 obj_03 obj_18 obj_12 obj_14 obj_13 obj_09 obj_01 obj_17 obj_02 obj_08 obj_05 obj_15 obj_16 obj_10 - type_4
        obj_11 - type_2
        obj_06 - type_3
    )

    (:init
        (pred_4 obj_02 obj_17)
        (pred_4 obj_01 obj_17)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_08 obj_09)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_17 obj_01)
        (pred_4 obj_17 obj_15)
        (pred_4 obj_09 obj_13)
        (pred_4 obj_15 obj_16)
        (pred_4 obj_15 obj_05)
        (pred_4 obj_12 obj_04)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_05 obj_15)
        (pred_4 obj_15 obj_17)
        (pred_4 obj_17 obj_02)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_13 obj_03)
        (pred_4 obj_03 obj_13)
        (pred_4 obj_01 obj_12)
        (pred_4 obj_09 obj_18)
        (pred_4 obj_02 obj_13)
        (pred_4 obj_13 obj_14)
        (pred_4 obj_16 obj_15)
        (pred_4 obj_18 obj_03)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_03 obj_18)
        (pred_4 obj_13 obj_02)
        (pred_4 obj_09 obj_08)
        (pred_4 obj_16 obj_02)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_13 obj_09)
        (pred_4 obj_12 obj_14)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_12 obj_01)
        (pred_4 obj_14 obj_07)
        (pred_4 obj_18 obj_09)
        (pred_4 obj_07 obj_14)
        (pred_4 obj_14 obj_12)
        (pred_4 obj_04 obj_12)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_14 obj_13)
        (pred_4 obj_10 obj_08)
        (pred_4 obj_02 obj_16)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_02 obj_08)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_06 obj_12)
        (pred_2 obj_06)
    )

    (:goal
        (pred_3 obj_11 obj_12)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_06 obj_12) (pred_3 obj_06 obj_14))) (not (and (pred_1 obj_06 obj_14) (pred_3 obj_06 obj_12)))))
  )
)

