
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1835144718)
    (:domain delivery)

    (:objects
        obj_07 obj_05 obj_09 obj_04 obj_01 obj_02 obj_10 obj_06 obj_11 - type_1
        obj_08 - type_4
        obj_03 - type_2
    )

    (:init
        (pred_3 obj_01 obj_04)
        (pred_3 obj_02 obj_09)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_01 obj_02)
        (pred_3 obj_09 obj_02)
        (pred_3 obj_06 obj_01)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_02 obj_01)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_01 obj_05)
        (pred_3 obj_05 obj_01)
        (pred_3 obj_07 obj_05)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_03 obj_02)
        (pred_2 obj_03)
    )

    (:goal
        (pred_1 obj_08 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_03 obj_04) (pred_1 obj_03 obj_01))) (not (and (pred_4 obj_03 obj_01) (pred_1 obj_03 obj_04)))))
  )
)

