
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1255775006)
    (:domain delivery)

    (:objects
        obj_18 obj_19 obj_08 obj_14 obj_10 obj_02 obj_04 obj_12 obj_13 obj_03 obj_05 obj_09 obj_06 obj_11 obj_17 obj_01 - type_1
        obj_16 obj_07 - type_4
        obj_15 - type_2
    )

    (:init
        (pred_3 obj_08 obj_19)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_13 obj_06)
        (pred_3 obj_05 obj_04)
        (pred_3 obj_18 obj_10)
        (pred_3 obj_05 obj_17)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_06 obj_13)
        (pred_3 obj_08 obj_14)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_11 obj_17)
        (pred_3 obj_10 obj_02)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_09 obj_12)
        (pred_3 obj_03 obj_13)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_19 obj_08)
        (pred_3 obj_17 obj_05)
        (pred_3 obj_02 obj_19)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_01 obj_17)
        (pred_3 obj_19 obj_18)
        (pred_3 obj_04 obj_05)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_12 obj_14)
        (pred_3 obj_17 obj_11)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_14 obj_08)
        (pred_3 obj_13 obj_03)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_18 obj_19)
        (pred_3 obj_10 obj_13)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_10 obj_18)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_13 obj_10)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_12 obj_09)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_17 obj_01)
        (pred_3 obj_14 obj_12)
        (pred_3 obj_19 obj_02)
        (pred_3 obj_11 obj_03)
        (pred_5 obj_16 obj_11)
        (pred_5 obj_07 obj_19)
        (pred_5 obj_15 obj_11)
        (pred_2 obj_15)
    )

    (:goal
        (and (pred_5 obj_16 obj_03) (pred_5 obj_07 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_15 obj_19) (pred_5 obj_15 obj_02))) (not (and (pred_1 obj_15 obj_02) (pred_5 obj_15 obj_19)))))
  )
)

