
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-2004720793)
    (:domain delivery)

    (:objects
        obj_12 obj_17 obj_14 obj_08 obj_03 obj_06 obj_18 obj_05 obj_09 obj_15 obj_04 obj_07 obj_01 obj_10 obj_11 obj_16 - type_3
        obj_02 - type_1
        obj_13 - type_4
    )

    (:init
        (pred_4 obj_04 obj_15)
        (pred_4 obj_09 obj_15)
        (pred_4 obj_15 obj_06)
        (pred_4 obj_07 obj_05)
        (pred_4 obj_07 obj_16)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_15 obj_09)
        (pred_4 obj_15 obj_10)
        (pred_4 obj_05 obj_18)
        (pred_4 obj_10 obj_11)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_17 obj_12)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_15 obj_04)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_18 obj_14)
        (pred_4 obj_14 obj_18)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_05 obj_08)
        (pred_4 obj_04 obj_18)
        (pred_4 obj_18 obj_06)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_08 obj_14)
        (pred_4 obj_06 obj_15)
        (pred_4 obj_14 obj_08)
        (pred_4 obj_18 obj_04)
        (pred_4 obj_05 obj_07)
        (pred_4 obj_11 obj_04)
        (pred_4 obj_11 obj_16)
        (pred_4 obj_18 obj_05)
        (pred_4 obj_03 obj_06)
        (pred_4 obj_12 obj_17)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_06 obj_17)
        (pred_4 obj_08 obj_05)
        (pred_4 obj_17 obj_06)
        (pred_4 obj_06 obj_03)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_16 obj_11)
        (pred_4 obj_06 obj_18)
        (pred_4 obj_16 obj_07)
        (pred_4 obj_04 obj_11)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_04 obj_07)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_13 obj_08)
        (pred_1 obj_13)
    )

    (:goal
        (pred_5 obj_02 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_13 obj_18) (pred_5 obj_13 obj_05))) (not (and (pred_2 obj_13 obj_05) (pred_5 obj_13 obj_18)))))
  )
)

