
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-221970907)
    (:domain delivery)

    (:objects
        obj_01 obj_03 obj_04 obj_10 obj_17 obj_12 obj_19 obj_15 obj_09 obj_13 obj_08 obj_05 obj_11 obj_14 obj_06 obj_18 - type_2
        obj_02 obj_16 - type_3
        obj_07 - type_1
    )

    (:init
        (pred_5 obj_04 obj_03)
        (pred_5 obj_19 obj_12)
        (pred_5 obj_09 obj_11)
        (pred_5 obj_08 obj_19)
        (pred_5 obj_01 obj_17)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_11 obj_09)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_05 obj_08)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_17 obj_12)
        (pred_5 obj_11 obj_14)
        (pred_5 obj_14 obj_11)
        (pred_5 obj_04 obj_19)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_13 obj_09)
        (pred_5 obj_13 obj_08)
        (pred_5 obj_18 obj_05)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_12 obj_03)
        (pred_5 obj_05 obj_18)
        (pred_5 obj_18 obj_06)
        (pred_5 obj_03 obj_01)
        (pred_5 obj_19 obj_08)
        (pred_5 obj_19 obj_04)
        (pred_5 obj_13 obj_14)
        (pred_5 obj_15 obj_10)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_12 obj_13)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_09 obj_13)
        (pred_5 obj_19 obj_15)
        (pred_5 obj_01 obj_03)
        (pred_5 obj_17 obj_09)
        (pred_5 obj_12 obj_17)
        (pred_5 obj_17 obj_01)
        (pred_5 obj_12 obj_19)
        (pred_5 obj_15 obj_19)
        (pred_5 obj_09 obj_17)
        (pred_5 obj_08 obj_13)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_13 obj_12)
        (pred_5 obj_06 obj_18)
        (pred_5 obj_10 obj_15)
        (pred_5 obj_03 obj_12)
        (pred_5 obj_14 obj_13)
        (pred_3 obj_07 obj_18)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_16 obj_13)
        (pred_1 obj_07)
    )

    (:goal
        (and (pred_3 obj_02 obj_08) (pred_3 obj_16 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_07 obj_04) (pred_3 obj_07 obj_19))) (not (and (pred_2 obj_07 obj_19) (pred_3 obj_07 obj_04)))))
  )
)

