
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1284686454)
    (:domain delivery)

    (:objects
        obj_13 obj_16 obj_06 obj_19 obj_08 obj_05 obj_03 obj_12 obj_01 obj_04 obj_09 obj_14 obj_11 obj_10 obj_18 obj_02 - type_1
        obj_15 obj_07 - type_4
        obj_17 - type_3
    )

    (:init
        (pred_2 obj_06 obj_16)
        (pred_2 obj_03 obj_05)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_13 obj_08)
        (pred_2 obj_09 obj_18)
        (pred_2 obj_09 obj_14)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_06 obj_19)
        (pred_2 obj_14 obj_09)
        (pred_2 obj_10 obj_18)
        (pred_2 obj_08 obj_05)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_14 obj_12)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_02 obj_14)
        (pred_2 obj_16 obj_06)
        (pred_2 obj_18 obj_09)
        (pred_2 obj_05 obj_16)
        (pred_2 obj_14 obj_02)
        (pred_2 obj_02 obj_18)
        (pred_2 obj_16 obj_13)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_12 obj_19)
        (pred_2 obj_18 obj_10)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_19 obj_06)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_03 obj_12)
        (pred_2 obj_13 obj_16)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_08 obj_13)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_12 obj_03)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_12 obj_14)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_18 obj_02)
        (pred_2 obj_19 obj_12)
        (pred_2 obj_16 obj_05)
        (pred_2 obj_10 obj_04)
        (pred_3 obj_15 obj_12)
        (pred_3 obj_07 obj_06)
        (pred_3 obj_17 obj_09)
        (pred_4 obj_17)
    )

    (:goal
        (and (pred_3 obj_15 obj_14) (pred_3 obj_07 obj_14))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_17 obj_19) (pred_3 obj_17 obj_12))) (not (and (pred_1 obj_17 obj_12) (pred_3 obj_17 obj_19)))))
  )
)

