
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-541946351)
    (:domain delivery)

    (:objects
        obj_03 obj_06 obj_01 obj_05 - type_3
        obj_04 - type_1
        obj_02 - type_2
    )

    (:init
        (pred_2 obj_03 obj_01)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_06 obj_05)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_02 obj_05)
        (pred_5 obj_02)
    )

    (:goal
        (pred_3 obj_04 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_02 obj_03) (pred_3 obj_02 obj_06))) (not (and (pred_4 obj_02 obj_06) (pred_3 obj_02 obj_03)))))
  )
)

