
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1710682885)
    (:domain delivery)

    (:objects
        obj_11 obj_03 obj_01 obj_05 obj_12 obj_08 obj_04 obj_09 obj_06 - type_4
        obj_10 obj_07 - type_2
        obj_02 - type_1
    )

    (:init
        (pred_4 obj_08 obj_06)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_04 obj_05)
        (pred_4 obj_01 obj_08)
        (pred_4 obj_05 obj_12)
        (pred_4 obj_08 obj_01)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_11 obj_03)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_03 obj_11)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_12 obj_05)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_12 obj_08)
        (pred_4 obj_08 obj_12)
        (pred_4 obj_12 obj_09)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_09 obj_12)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_06 obj_08)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_10 obj_08)
        (pred_5 obj_02 obj_04)
        (pred_2 obj_02)
    )

    (:goal
        (and (pred_5 obj_10 obj_04) (pred_5 obj_07 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_02 obj_12) (pred_5 obj_02 obj_08))) (not (and (pred_3 obj_02 obj_08) (pred_5 obj_02 obj_12)))))
  )
)

