
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1010907011)
    (:domain delivery)

    (:objects
        obj_07 obj_14 obj_01 obj_10 obj_03 obj_09 obj_06 obj_17 obj_08 obj_02 obj_12 obj_05 obj_13 obj_18 obj_15 obj_16 - type_4
        obj_11 - type_2
        obj_04 - type_3
    )

    (:init
        (pred_4 obj_12 obj_02)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_02 obj_09)
        (pred_4 obj_05 obj_17)
        (pred_4 obj_05 obj_16)
        (pred_4 obj_05 obj_12)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_02 obj_18)
        (pred_4 obj_17 obj_06)
        (pred_4 obj_18 obj_15)
        (pred_4 obj_18 obj_13)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_01 obj_14)
        (pred_4 obj_14 obj_07)
        (pred_4 obj_13 obj_18)
        (pred_4 obj_18 obj_02)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_13 obj_08)
        (pred_4 obj_06 obj_01)
        (pred_4 obj_01 obj_06)
        (pred_4 obj_08 obj_03)
        (pred_4 obj_17 obj_10)
        (pred_4 obj_12 obj_06)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_15 obj_18)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_09 obj_02)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_06 obj_12)
        (pred_4 obj_17 obj_05)
        (pred_4 obj_15 obj_12)
        (pred_4 obj_15 obj_16)
        (pred_4 obj_06 obj_17)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_07 obj_14)
        (pred_4 obj_14 obj_01)
        (pred_4 obj_03 obj_08)
        (pred_4 obj_09 obj_14)
        (pred_4 obj_10 obj_17)
        (pred_4 obj_14 obj_09)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_16 obj_15)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_16 obj_05)
        (pred_4 obj_12 obj_15)
        (pred_4 obj_08 obj_13)
        (pred_4 obj_12 obj_05)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_04 obj_10)
        (pred_1 obj_04)
    )

    (:goal
        (pred_2 obj_11 obj_17)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_09) (pred_2 obj_04 obj_02))) (not (and (pred_3 obj_04 obj_02) (pred_2 obj_04 obj_09)))))
  )
)

