
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-36685338)
    (:domain delivery)

    (:objects
        obj_11 obj_13 obj_15 obj_02 obj_14 obj_01 obj_12 obj_09 obj_10 obj_04 obj_05 obj_08 obj_18 obj_16 obj_17 obj_06 - type_2
        obj_07 - type_4
        obj_03 - type_3
    )

    (:init
        (pred_5 obj_05 obj_04)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_08 obj_09)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_04 obj_16)
        (pred_5 obj_09 obj_12)
        (pred_5 obj_16 obj_17)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_14 obj_11)
        (pred_5 obj_15 obj_13)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_16 obj_04)
        (pred_5 obj_04 obj_05)
        (pred_5 obj_18 obj_10)
        (pred_5 obj_12 obj_15)
        (pred_5 obj_15 obj_12)
        (pred_5 obj_10 obj_14)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_05 obj_12)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_17 obj_16)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_12 obj_05)
        (pred_5 obj_09 obj_08)
        (pred_5 obj_17 obj_05)
        (pred_5 obj_17 obj_06)
        (pred_5 obj_12 obj_09)
        (pred_5 obj_14 obj_01)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_13 obj_15)
        (pred_5 obj_14 obj_10)
        (pred_5 obj_01 obj_13)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_13 obj_01)
        (pred_5 obj_01 obj_14)
        (pred_5 obj_11 obj_14)
        (pred_5 obj_06 obj_17)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_05 obj_17)
        (pred_5 obj_10 obj_18)
        (pred_5 obj_05 obj_08)
        (pred_1 obj_03 obj_12)
        (pred_1 obj_07 obj_16)
        (pred_4 obj_03)
    )

    (:goal
        (pred_1 obj_07 obj_12)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_03 obj_01) (pred_1 obj_03 obj_04))) (not (and (pred_2 obj_03 obj_04) (pred_1 obj_03 obj_01)))))
  )
)

