
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1829016842)
    (:domain delivery)

    (:objects
        obj_10 obj_06 obj_12 obj_02 obj_11 obj_03 obj_09 obj_07 obj_08 - type_4
        obj_01 obj_05 - type_2
        obj_04 - type_3
    )

    (:init
        (pred_3 obj_03 obj_08)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_09 obj_02)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_03 obj_12)
        (pred_3 obj_07 obj_08)
        (pred_3 obj_12 obj_06)
        (pred_3 obj_02 obj_10)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_09 obj_07)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_07 obj_09)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_02 obj_09)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_06 obj_12)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_11 obj_07)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_10 obj_02)
        (pred_3 obj_08 obj_03)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_04 obj_09)
        (pred_2 obj_04)
    )

    (:goal
        (and (pred_5 obj_01 obj_11) (pred_5 obj_05 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_04 obj_02) (pred_5 obj_04 obj_09))) (not (and (pred_4 obj_04 obj_09) (pred_5 obj_04 obj_02)))))
  )
)

