
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-621003925)
    (:domain delivery)

    (:objects
        obj_09 obj_14 obj_06 obj_04 obj_19 obj_02 obj_17 obj_16 obj_05 obj_03 obj_01 obj_07 obj_18 obj_15 obj_08 obj_11 - type_2
        obj_13 obj_10 - type_1
        obj_12 - type_4
    )

    (:init
        (pred_1 obj_06 obj_14)
        (pred_1 obj_17 obj_02)
        (pred_1 obj_05 obj_18)
        (pred_1 obj_01 obj_17)
        (pred_1 obj_09 obj_19)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_18 obj_05)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_15 obj_08)
        (pred_1 obj_19 obj_02)
        (pred_1 obj_18 obj_15)
        (pred_1 obj_15 obj_18)
        (pred_1 obj_06 obj_17)
        (pred_1 obj_07 obj_16)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_11 obj_07)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_02 obj_14)
        (pred_1 obj_07 obj_11)
        (pred_1 obj_11 obj_08)
        (pred_1 obj_14 obj_09)
        (pred_1 obj_17 obj_01)
        (pred_1 obj_17 obj_06)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_16 obj_04)
        (pred_1 obj_08 obj_15)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_17 obj_16)
        (pred_1 obj_09 obj_14)
        (pred_1 obj_19 obj_05)
        (pred_1 obj_02 obj_19)
        (pred_1 obj_19 obj_09)
        (pred_1 obj_02 obj_17)
        (pred_1 obj_16 obj_17)
        (pred_1 obj_05 obj_19)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_16 obj_07)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_08 obj_11)
        (pred_1 obj_04 obj_16)
        (pred_1 obj_14 obj_02)
        (pred_1 obj_15 obj_03)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_12 obj_02)
        (pred_2 obj_13 obj_08)
        (pred_5 obj_12)
    )

    (:goal
        (and (pred_2 obj_13 obj_16) (pred_2 obj_10 obj_16))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_12 obj_17) (pred_2 obj_12 obj_16))) (not (and (pred_3 obj_12 obj_16) (pred_2 obj_12 obj_17)))))
  )
)

