
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-801202747)
    (:domain delivery)

    (:objects
        obj_05 obj_06 obj_03 obj_10 obj_02 obj_08 obj_12 obj_11 obj_04 - type_3
        obj_01 obj_09 - type_2
        obj_07 - type_4
    )

    (:init
        (pred_1 obj_08 obj_04)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_12 obj_10)
        (pred_1 obj_03 obj_08)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_08 obj_03)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_03 obj_06)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_05 obj_06)
        (pred_1 obj_12 obj_11)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_06 obj_05)
        (pred_1 obj_10 obj_12)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_06 obj_03)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_04 obj_08)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_07 obj_12)
        (pred_5 obj_07)
    )

    (:goal
        (and (pred_3 obj_01 obj_11) (pred_3 obj_09 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_07 obj_02) (pred_3 obj_07 obj_11))) (not (and (pred_4 obj_07 obj_11) (pred_3 obj_07 obj_02)))))
  )
)

