
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-928337592)
    (:domain delivery)

    (:objects
        obj_07 obj_10 obj_02 obj_16 obj_13 obj_09 obj_04 obj_01 obj_06 obj_12 obj_19 obj_03 obj_08 obj_15 obj_05 obj_17 - type_3
        obj_18 obj_11 - type_4
        obj_14 - type_2
    )

    (:init
        (pred_1 obj_02 obj_10)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_19 obj_04)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_19 obj_05)
        (pred_1 obj_19 obj_03)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_02 obj_16)
        (pred_1 obj_03 obj_19)
        (pred_1 obj_15 obj_05)
        (pred_1 obj_13 obj_09)
        (pred_1 obj_08 obj_15)
        (pred_1 obj_15 obj_08)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_12 obj_19)
        (pred_1 obj_17 obj_03)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_05 obj_19)
        (pred_1 obj_09 obj_10)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_17 obj_05)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_04 obj_19)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_12 obj_15)
        (pred_1 obj_01 obj_16)
        (pred_1 obj_05 obj_15)
        (pred_1 obj_09 obj_12)
        (pred_1 obj_16 obj_02)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_09 obj_13)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_19 obj_12)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_12 obj_09)
        (pred_1 obj_05 obj_17)
        (pred_1 obj_16 obj_01)
        (pred_1 obj_10 obj_09)
        (pred_1 obj_15 obj_12)
        (pred_5 obj_14 obj_16)
        (pred_5 obj_18 obj_08)
        (pred_5 obj_11 obj_12)
        (pred_4 obj_14)
    )

    (:goal
        (and (pred_5 obj_18 obj_07) (pred_5 obj_11 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_14 obj_09) (pred_5 obj_14 obj_12))) (not (and (pred_3 obj_14 obj_12) (pred_5 obj_14 obj_09)))))
  )
)

