
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-61408799)
    (:domain delivery)

    (:objects
        obj_02 obj_11 obj_03 obj_19 obj_12 obj_05 obj_13 obj_04 obj_08 obj_06 obj_10 obj_18 obj_09 obj_17 obj_14 obj_01 - type_2
        obj_16 obj_07 - type_3
        obj_15 - type_4
    )

    (:init
        (pred_4 obj_03 obj_11)
        (pred_4 obj_13 obj_05)
        (pred_4 obj_08 obj_09)
        (pred_4 obj_10 obj_13)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_10 obj_14)
        (pred_4 obj_10 obj_18)
        (pred_4 obj_09 obj_08)
        (pred_4 obj_03 obj_19)
        (pred_4 obj_18 obj_10)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_12 obj_05)
        (pred_4 obj_09 obj_17)
        (pred_4 obj_17 obj_09)
        (pred_4 obj_03 obj_13)
        (pred_4 obj_18 obj_04)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_01 obj_18)
        (pred_4 obj_11 obj_03)
        (pred_4 obj_14 obj_10)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_18 obj_01)
        (pred_4 obj_01 obj_14)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_13 obj_10)
        (pred_4 obj_13 obj_03)
        (pred_4 obj_06 obj_17)
        (pred_4 obj_04 obj_19)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_19 obj_03)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_13 obj_04)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_12 obj_08)
        (pred_4 obj_05 obj_12)
        (pred_4 obj_12 obj_02)
        (pred_4 obj_05 obj_13)
        (pred_4 obj_04 obj_13)
        (pred_4 obj_08 obj_12)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_04 obj_18)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_14 obj_01)
        (pred_4 obj_19 obj_04)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_17 obj_06)
        (pred_2 obj_16 obj_04)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_15 obj_17)
        (pred_3 obj_15)
    )

    (:goal
        (and (pred_2 obj_16 obj_18) (pred_2 obj_07 obj_18))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_15 obj_19) (pred_2 obj_15 obj_04))) (not (and (pred_5 obj_15 obj_04) (pred_2 obj_15 obj_19)))))
  )
)

