
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1000143947)
    (:domain delivery)

    (:objects
        obj_04 obj_13 obj_07 obj_12 obj_09 obj_16 obj_08 obj_17 obj_11 obj_01 obj_03 obj_05 obj_10 obj_14 obj_18 obj_15 - type_4
        obj_02 - type_2
        obj_06 - type_3
    )

    (:init
        (pred_2 obj_03 obj_01)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_01 obj_16)
        (pred_2 obj_05 obj_17)
        (pred_2 obj_05 obj_15)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_01 obj_14)
        (pred_2 obj_17 obj_08)
        (pred_2 obj_14 obj_18)
        (pred_2 obj_14 obj_10)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_07 obj_13)
        (pred_2 obj_13 obj_04)
        (pred_2 obj_10 obj_14)
        (pred_2 obj_14 obj_01)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_08 obj_07)
        (pred_2 obj_07 obj_08)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_17 obj_12)
        (pred_2 obj_03 obj_08)
        (pred_2 obj_08 obj_16)
        (pred_2 obj_18 obj_14)
        (pred_2 obj_12 obj_07)
        (pred_2 obj_16 obj_01)
        (pred_2 obj_07 obj_12)
        (pred_2 obj_08 obj_03)
        (pred_2 obj_17 obj_05)
        (pred_2 obj_18 obj_03)
        (pred_2 obj_18 obj_15)
        (pred_2 obj_08 obj_17)
        (pred_2 obj_09 obj_16)
        (pred_2 obj_04 obj_13)
        (pred_2 obj_13 obj_07)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_16 obj_13)
        (pred_2 obj_12 obj_17)
        (pred_2 obj_13 obj_16)
        (pred_2 obj_16 obj_09)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_15 obj_18)
        (pred_2 obj_16 obj_08)
        (pred_2 obj_15 obj_05)
        (pred_2 obj_03 obj_18)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_03 obj_05)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_06 obj_04)
        (pred_5 obj_06)
    )

    (:goal
        (pred_4 obj_02 obj_17)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_06 obj_08) (pred_4 obj_06 obj_17))) (not (and (pred_1 obj_06 obj_17) (pred_4 obj_06 obj_08)))))
  )
)

