
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-182859895)
    (:domain delivery)

    (:objects
        obj_11 obj_07 obj_19 obj_12 obj_16 obj_04 obj_17 obj_18 obj_03 obj_15 obj_01 obj_13 obj_06 obj_14 obj_05 obj_10 - type_1
        obj_09 obj_02 - type_2
        obj_08 - type_4
    )

    (:init
        (pred_2 obj_19 obj_07)
        (pred_2 obj_17 obj_04)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_01 obj_17)
        (pred_2 obj_11 obj_16)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_01 obj_13)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_19 obj_12)
        (pred_2 obj_13 obj_01)
        (pred_2 obj_14 obj_05)
        (pred_2 obj_16 obj_04)
        (pred_2 obj_06 obj_14)
        (pred_2 obj_14 obj_06)
        (pred_2 obj_19 obj_17)
        (pred_2 obj_13 obj_18)
        (pred_2 obj_15 obj_03)
        (pred_2 obj_15 obj_01)
        (pred_2 obj_10 obj_13)
        (pred_2 obj_07 obj_19)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_13 obj_10)
        (pred_2 obj_10 obj_05)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_17 obj_01)
        (pred_2 obj_17 obj_19)
        (pred_2 obj_15 obj_14)
        (pred_2 obj_18 obj_12)
        (pred_2 obj_05 obj_14)
        (pred_2 obj_04 obj_15)
        (pred_2 obj_12 obj_19)
        (pred_2 obj_03 obj_15)
        (pred_2 obj_17 obj_18)
        (pred_2 obj_11 obj_07)
        (pred_2 obj_16 obj_03)
        (pred_2 obj_04 obj_16)
        (pred_2 obj_16 obj_11)
        (pred_2 obj_04 obj_17)
        (pred_2 obj_18 obj_17)
        (pred_2 obj_03 obj_16)
        (pred_2 obj_01 obj_15)
        (pred_2 obj_18 obj_13)
        (pred_2 obj_15 obj_04)
        (pred_2 obj_05 obj_10)
        (pred_2 obj_12 obj_18)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_14 obj_15)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_02 obj_12)
        (pred_1 obj_08)
    )

    (:goal
        (and (pred_5 obj_09 obj_07) (pred_5 obj_02 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_08 obj_12) (pred_5 obj_08 obj_18))) (not (and (pred_3 obj_08 obj_18) (pred_5 obj_08 obj_12)))))
  )
)

