
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-850791297)
    (:domain delivery)

    (:objects
        obj_15 obj_16 obj_04 obj_05 obj_18 obj_10 obj_07 obj_09 obj_17 obj_08 obj_01 obj_14 obj_03 obj_19 obj_12 obj_06 - type_3
        obj_11 obj_02 - type_1
        obj_13 - type_4
    )

    (:init
        (pred_1 obj_04 obj_16)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_17 obj_03)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_15 obj_18)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_01 obj_14)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_14 obj_01)
        (pred_1 obj_19 obj_12)
        (pred_1 obj_18 obj_10)
        (pred_1 obj_03 obj_19)
        (pred_1 obj_19 obj_03)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_14 obj_09)
        (pred_1 obj_08 obj_17)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_06 obj_14)
        (pred_1 obj_16 obj_04)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_10 obj_16)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_16 obj_15)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_08 obj_19)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_12 obj_19)
        (pred_1 obj_10 obj_08)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_17 obj_08)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_18 obj_17)
        (pred_1 obj_10 obj_18)
        (pred_1 obj_18 obj_15)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_17 obj_18)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_09 obj_14)
        (pred_1 obj_08 obj_10)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_16 obj_10)
        (pred_1 obj_19 obj_08)
        (pred_3 obj_11 obj_14)
        (pred_3 obj_02 obj_19)
        (pred_3 obj_13 obj_09)
        (pred_5 obj_13)
    )

    (:goal
        (and (pred_3 obj_11 obj_14) (pred_3 obj_02 obj_14))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_13 obj_01) (pred_3 obj_13 obj_14))) (not (and (pred_4 obj_13 obj_14) (pred_3 obj_13 obj_01)))))
  )
)

