
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1080602471)
    (:domain delivery)

    (:objects
        obj_10 obj_05 obj_11 obj_03 obj_04 obj_07 obj_01 obj_06 obj_08 - type_4
        obj_02 - type_3
        obj_09 - type_2
    )

    (:init
        (pred_5 obj_04 obj_03)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_03 obj_01)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_06 obj_04)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_01 obj_03)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_04 obj_05)
        (pred_5 obj_05 obj_04)
        (pred_5 obj_10 obj_05)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_02 obj_06)
        (pred_3 obj_09)
    )

    (:goal
        (pred_1 obj_02 obj_11)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_09 obj_04) (pred_1 obj_09 obj_06))) (not (and (pred_2 obj_09 obj_06) (pred_1 obj_09 obj_04)))))
  )
)

