
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-558540028)
    (:domain delivery)

    (:objects
        obj_18 obj_03 obj_05 obj_16 obj_09 obj_02 obj_14 obj_15 obj_04 obj_01 obj_10 obj_17 obj_07 obj_12 obj_08 obj_13 - type_4
        obj_11 - type_3
        obj_06 - type_1
    )

    (:init
        (pred_2 obj_10 obj_01)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_17 obj_15)
        (pred_2 obj_17 obj_13)
        (pred_2 obj_17 obj_10)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_15 obj_14)
        (pred_2 obj_12 obj_08)
        (pred_2 obj_12 obj_07)
        (pred_2 obj_09 obj_18)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_03 obj_18)
        (pred_2 obj_07 obj_12)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_14 obj_05)
        (pred_2 obj_05 obj_14)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_15 obj_16)
        (pred_2 obj_10 obj_14)
        (pred_2 obj_14 obj_02)
        (pred_2 obj_08 obj_12)
        (pred_2 obj_16 obj_05)
        (pred_2 obj_02 obj_01)
        (pred_2 obj_05 obj_16)
        (pred_2 obj_14 obj_10)
        (pred_2 obj_15 obj_17)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_08 obj_13)
        (pred_2 obj_14 obj_15)
        (pred_2 obj_09 obj_02)
        (pred_2 obj_18 obj_03)
        (pred_2 obj_03 obj_05)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_16 obj_15)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_02 obj_09)
        (pred_2 obj_18 obj_09)
        (pred_2 obj_13 obj_08)
        (pred_2 obj_02 obj_14)
        (pred_2 obj_13 obj_17)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_10 obj_17)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_06 obj_15)
        (pred_1 obj_06)
    )

    (:goal
        (pred_3 obj_11 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_06 obj_10) (pred_3 obj_06 obj_08))) (not (and (pred_4 obj_06 obj_08) (pred_3 obj_06 obj_10)))))
  )
)

