
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1790697645)
    (:domain delivery)

    (:objects
        obj_05 obj_18 obj_06 obj_09 obj_01 obj_04 obj_08 obj_16 obj_12 obj_07 obj_02 obj_10 obj_15 obj_03 obj_13 obj_11 - type_1
        obj_17 - type_3
        obj_14 - type_4
    )

    (:init
        (pred_4 obj_02 obj_07)
        (pred_4 obj_12 obj_07)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_10 obj_11)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_07 obj_12)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_16 obj_08)
        (pred_4 obj_03 obj_13)
        (pred_4 obj_03 obj_15)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_06 obj_18)
        (pred_4 obj_18 obj_05)
        (pred_4 obj_15 obj_03)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_15 obj_12)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_12 obj_01)
        (pred_4 obj_16 obj_09)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_08 obj_04)
        (pred_4 obj_13 obj_03)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_13 obj_02)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_08 obj_16)
        (pred_4 obj_01 obj_04)
        (pred_4 obj_05 obj_18)
        (pred_4 obj_18 obj_06)
        (pred_4 obj_01 obj_12)
        (pred_4 obj_04 obj_18)
        (pred_4 obj_09 obj_16)
        (pred_4 obj_18 obj_04)
        (pred_4 obj_04 obj_01)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_04 obj_08)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_02 obj_13)
        (pred_4 obj_12 obj_15)
        (pred_4 obj_02 obj_10)
        (pred_5 obj_14 obj_15)
        (pred_5 obj_17 obj_06)
        (pred_1 obj_14)
    )

    (:goal
        (pred_5 obj_17 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_14 obj_05) (pred_5 obj_14 obj_18))) (not (and (pred_3 obj_14 obj_18) (pred_5 obj_14 obj_05)))))
  )
)

