
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-378094160)
    (:domain delivery)

    (:objects
        obj_11 obj_08 obj_06 obj_03 obj_05 obj_01 obj_12 obj_09 obj_02 - type_4
        obj_04 obj_07 - type_3
        obj_10 - type_2
    )

    (:init
        (pred_2 obj_01 obj_02)
        (pred_2 obj_02 obj_09)
        (pred_2 obj_12 obj_03)
        (pred_2 obj_06 obj_01)
        (pred_2 obj_03 obj_05)
        (pred_2 obj_01 obj_06)
        (pred_2 obj_09 obj_02)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_03 obj_11)
        (pred_2 obj_11 obj_08)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_08 obj_05)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_08 obj_11)
        (pred_2 obj_03 obj_12)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_11 obj_03)
        (pred_2 obj_02 obj_01)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_04 obj_08)
        (pred_4 obj_07 obj_09)
        (pred_1 obj_10)
    )

    (:goal
        (and (pred_4 obj_04 obj_11) (pred_4 obj_07 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_10 obj_05) (pred_4 obj_10 obj_09))) (not (and (pred_3 obj_10 obj_09) (pred_4 obj_10 obj_05)))))
  )
)

