
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1694931589)
    (:domain delivery)

    (:objects
        obj_09 obj_07 obj_16 obj_18 obj_04 obj_12 obj_15 obj_17 obj_14 obj_03 obj_13 obj_06 obj_02 obj_08 obj_05 obj_11 - type_1
        obj_10 - type_4
        obj_01 - type_2
    )

    (:init
        (pred_3 obj_13 obj_03)
        (pred_3 obj_14 obj_03)
        (pred_3 obj_03 obj_12)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_06 obj_13)
        (pred_3 obj_03 obj_14)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_17 obj_15)
        (pred_3 obj_08 obj_05)
        (pred_3 obj_08 obj_02)
        (pred_3 obj_04 obj_09)
        (pred_3 obj_16 obj_07)
        (pred_3 obj_07 obj_09)
        (pred_3 obj_02 obj_08)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_03 obj_13)
        (pred_3 obj_02 obj_14)
        (pred_3 obj_15 obj_16)
        (pred_3 obj_16 obj_15)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_17 obj_18)
        (pred_3 obj_13 obj_15)
        (pred_3 obj_15 obj_12)
        (pred_3 obj_05 obj_08)
        (pred_3 obj_18 obj_16)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_16 obj_18)
        (pred_3 obj_15 obj_13)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_05 obj_13)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_15 obj_17)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_09 obj_07)
        (pred_3 obj_07 obj_16)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_18 obj_17)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_09 obj_04)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_12 obj_15)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_13 obj_05)
        (pred_3 obj_14 obj_02)
        (pred_3 obj_13 obj_06)
        (pred_4 obj_01 obj_06)
        (pred_4 obj_10 obj_18)
        (pred_5 obj_01)
    )

    (:goal
        (pred_4 obj_10 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_18) (pred_4 obj_01 obj_17))) (not (and (pred_1 obj_01 obj_17) (pred_4 obj_01 obj_18)))))
  )
)

