
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-196282390)
    (:domain delivery)

    (:objects
        obj_03 obj_10 obj_05 obj_14 obj_13 obj_11 obj_02 obj_08 obj_06 obj_18 obj_09 obj_07 obj_01 obj_15 obj_17 obj_04 - type_4
        obj_12 - type_3
        obj_16 - type_2
    )

    (:init
        (pred_5 obj_09 obj_18)
        (pred_5 obj_06 obj_18)
        (pred_5 obj_18 obj_11)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_07 obj_09)
        (pred_5 obj_18 obj_06)
        (pred_5 obj_18 obj_15)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_15 obj_17)
        (pred_5 obj_15 obj_01)
        (pred_5 obj_13 obj_03)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_01 obj_15)
        (pred_5 obj_15 obj_18)
        (pred_5 obj_18 obj_09)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_05 obj_02)
        (pred_5 obj_06 obj_13)
        (pred_5 obj_08 obj_14)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_17 obj_15)
        (pred_5 obj_14 obj_05)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_05 obj_14)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_17 obj_09)
        (pred_5 obj_17 obj_04)
        (pred_5 obj_02 obj_08)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_10 obj_05)
        (pred_5 obj_13 obj_06)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_14 obj_08)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_03 obj_13)
        (pred_5 obj_04 obj_17)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_09 obj_17)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_09 obj_07)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_16 obj_09)
        (pred_4 obj_16)
    )

    (:goal
        (pred_2 obj_12 obj_15)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_16 obj_18) (pred_2 obj_16 obj_15))) (not (and (pred_3 obj_16 obj_15) (pred_2 obj_16 obj_18)))))
  )
)

