
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1565140297)
    (:domain delivery)

    (:objects
        obj_05 obj_06 obj_08 obj_02 obj_10 obj_03 obj_01 obj_04 obj_09 - type_1
        obj_07 - type_4
        obj_11 - type_2
    )

    (:init
        (pred_4 obj_10 obj_02)
        (pred_4 obj_03 obj_08)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_04 obj_01)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_10 obj_03)
        (pred_4 obj_08 obj_03)
        (pred_4 obj_04 obj_10)
        (pred_4 obj_02 obj_10)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_01 obj_04)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_10 obj_04)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_05 obj_06)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_07 obj_04)
        (pred_3 obj_11)
    )

    (:goal
        (pred_1 obj_07 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_11 obj_10) (pred_1 obj_11 obj_04))) (not (and (pred_5 obj_11 obj_04) (pred_1 obj_11 obj_10)))))
  )
)

