
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-119220218)
    (:domain delivery)

    (:objects
        obj_10 obj_08 obj_07 obj_11 obj_05 obj_01 obj_02 obj_06 obj_09 - type_3
        obj_03 - type_4
        obj_04 - type_1
    )

    (:init
        (pred_1 obj_05 obj_11)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_08 obj_10)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_09 obj_01)
        (pred_1 obj_05 obj_01)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_06 obj_05)
        (pred_1 obj_11 obj_05)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_01 obj_05)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_05 obj_06)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_05 obj_08)
        (pred_1 obj_08 obj_05)
        (pred_1 obj_10 obj_08)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_03 obj_09)
        (pred_5 obj_04)
    )

    (:goal
        (pred_2 obj_03 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_01) (pred_2 obj_04 obj_09))) (not (and (pred_3 obj_04 obj_09) (pred_2 obj_04 obj_01)))))
  )
)

