
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1559278761)
    (:domain delivery)

    (:objects
        obj_13 obj_01 obj_15 obj_16 obj_04 obj_02 obj_14 obj_06 obj_08 obj_09 obj_17 obj_03 obj_12 obj_07 obj_18 obj_10 - type_3
        obj_05 - type_2
        obj_11 - type_1
    )

    (:init
        (pred_1 obj_17 obj_09)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_03 obj_06)
        (pred_1 obj_03 obj_10)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_06 obj_14)
        (pred_1 obj_07 obj_18)
        (pred_1 obj_07 obj_12)
        (pred_1 obj_04 obj_13)
        (pred_1 obj_15 obj_01)
        (pred_1 obj_01 obj_13)
        (pred_1 obj_12 obj_07)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_12 obj_08)
        (pred_1 obj_14 obj_15)
        (pred_1 obj_15 obj_14)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_06 obj_16)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_14 obj_02)
        (pred_1 obj_18 obj_07)
        (pred_1 obj_16 obj_15)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_06 obj_03)
        (pred_1 obj_18 obj_17)
        (pred_1 obj_18 obj_10)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_13 obj_01)
        (pred_1 obj_01 obj_15)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_16 obj_06)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_13 obj_04)
        (pred_1 obj_10 obj_18)
        (pred_1 obj_02 obj_14)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_17 obj_18)
        (pred_1 obj_08 obj_12)
        (pred_1 obj_17 obj_03)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_11 obj_09)
        (pred_5 obj_11)
    )

    (:goal
        (pred_2 obj_05 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_11 obj_14) (pred_2 obj_11 obj_06))) (not (and (pred_4 obj_11 obj_06) (pred_2 obj_11 obj_14)))))
  )
)

