
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1924156616)
    (:domain delivery)

    (:objects
        obj_10 obj_07 obj_05 obj_02 obj_06 obj_12 obj_16 obj_15 obj_04 obj_19 obj_01 obj_13 obj_09 obj_03 obj_18 obj_08 - type_3
        obj_14 obj_11 - type_2
        obj_17 - type_1
    )

    (:init
        (pred_1 obj_05 obj_07)
        (pred_1 obj_16 obj_12)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_01 obj_16)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_01 obj_18)
        (pred_1 obj_01 obj_13)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_05 obj_02)
        (pred_1 obj_13 obj_01)
        (pred_1 obj_03 obj_18)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_05 obj_16)
        (pred_1 obj_13 obj_15)
        (pred_1 obj_19 obj_04)
        (pred_1 obj_19 obj_01)
        (pred_1 obj_08 obj_13)
        (pred_1 obj_07 obj_05)
        (pred_1 obj_18 obj_01)
        (pred_1 obj_12 obj_07)
        (pred_1 obj_13 obj_08)
        (pred_1 obj_08 obj_18)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_16 obj_01)
        (pred_1 obj_16 obj_05)
        (pred_1 obj_19 obj_03)
        (pred_1 obj_15 obj_02)
        (pred_1 obj_18 obj_03)
        (pred_1 obj_12 obj_19)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_04 obj_19)
        (pred_1 obj_16 obj_15)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_12 obj_16)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_01 obj_19)
        (pred_1 obj_15 obj_13)
        (pred_1 obj_19 obj_12)
        (pred_1 obj_18 obj_08)
        (pred_1 obj_02 obj_15)
        (pred_1 obj_07 obj_12)
        (pred_1 obj_03 obj_19)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_14 obj_02)
        (pred_5 obj_17 obj_01)
        (pred_4 obj_17)
    )

    (:goal
        (and (pred_5 obj_14 obj_18) (pred_5 obj_11 obj_18))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_17 obj_05) (pred_5 obj_17 obj_16))) (not (and (pred_2 obj_17 obj_16) (pred_5 obj_17 obj_05)))))
  )
)

