
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-994168525)
    (:domain delivery)

    (:objects
        obj_10 obj_01 obj_04 obj_06 obj_08 obj_09 obj_05 obj_07 obj_11 - type_3
        obj_02 - type_2
        obj_03 - type_1
    )

    (:init
        (pred_2 obj_08 obj_06)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_10 obj_06)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_08 obj_09)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_07 obj_08)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_09 obj_08)
        (pred_2 obj_11 obj_07)
        (pred_2 obj_08 obj_07)
        (pred_2 obj_06 obj_10)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_10 obj_01)
        (pred_5 obj_02 obj_06)
        (pred_5 obj_03 obj_06)
        (pred_1 obj_03)
    )

    (:goal
        (pred_5 obj_02 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_10) (pred_5 obj_03 obj_01))) (not (and (pred_3 obj_03 obj_01) (pred_5 obj_03 obj_10)))))
  )
)

