
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1031634443)
    (:domain delivery)

    (:objects
        obj_19 obj_18 obj_01 obj_15 obj_05 obj_14 obj_03 obj_09 obj_08 obj_02 obj_12 obj_10 obj_07 obj_16 obj_11 obj_13 - type_2
        obj_17 obj_06 - type_1
        obj_04 - type_3
    )

    (:init
        (pred_4 obj_01 obj_18)
        (pred_4 obj_03 obj_14)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_19 obj_05)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_12 obj_10)
        (pred_4 obj_07 obj_08)
        (pred_4 obj_01 obj_15)
        (pred_4 obj_10 obj_12)
        (pred_4 obj_16 obj_11)
        (pred_4 obj_05 obj_14)
        (pred_4 obj_07 obj_16)
        (pred_4 obj_16 obj_07)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_10 obj_09)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_13 obj_10)
        (pred_4 obj_18 obj_01)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_14 obj_18)
        (pred_4 obj_10 obj_13)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_18 obj_19)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_02 obj_16)
        (pred_4 obj_09 obj_15)
        (pred_4 obj_11 obj_16)
        (pred_4 obj_14 obj_02)
        (pred_4 obj_15 obj_01)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_19 obj_18)
        (pred_4 obj_05 obj_08)
        (pred_4 obj_14 obj_05)
        (pred_4 obj_05 obj_19)
        (pred_4 obj_14 obj_03)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_08 obj_05)
        (pred_4 obj_12 obj_02)
        (pred_4 obj_09 obj_10)
        (pred_4 obj_02 obj_14)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_15 obj_09)
        (pred_4 obj_18 obj_14)
        (pred_4 obj_16 obj_02)
        (pred_5 obj_17 obj_14)
        (pred_5 obj_06 obj_09)
        (pred_5 obj_04 obj_14)
        (pred_3 obj_04)
    )

    (:goal
        (and (pred_5 obj_17 obj_10) (pred_5 obj_06 obj_10))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_04 obj_03) (pred_5 obj_04 obj_09))) (not (and (pred_1 obj_04 obj_09) (pred_5 obj_04 obj_03)))))
  )
)

