
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-749983359)
    (:domain delivery)

    (:objects
        obj_16 obj_17 obj_05 obj_12 obj_13 obj_18 obj_08 obj_14 obj_06 obj_03 obj_02 obj_09 obj_15 obj_04 obj_11 obj_07 - type_4
        obj_10 - type_2
        obj_01 - type_3
    )

    (:init
        (pred_1 obj_02 obj_03)
        (pred_1 obj_06 obj_03)
        (pred_1 obj_03 obj_18)
        (pred_1 obj_09 obj_14)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_03 obj_06)
        (pred_1 obj_03 obj_04)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_04 obj_15)
        (pred_1 obj_13 obj_16)
        (pred_1 obj_05 obj_17)
        (pred_1 obj_17 obj_16)
        (pred_1 obj_15 obj_04)
        (pred_1 obj_04 obj_03)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_15 obj_06)
        (pred_1 obj_08 obj_05)
        (pred_1 obj_05 obj_08)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_14 obj_12)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_08 obj_18)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_18 obj_03)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_14 obj_09)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_11 obj_07)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_13 obj_18)
        (pred_1 obj_16 obj_17)
        (pred_1 obj_17 obj_05)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_18 obj_17)
        (pred_1 obj_12 obj_14)
        (pred_1 obj_17 obj_18)
        (pred_1 obj_18 obj_13)
        (pred_1 obj_16 obj_13)
        (pred_1 obj_07 obj_11)
        (pred_1 obj_18 obj_08)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_06 obj_15)
        (pred_1 obj_02 obj_09)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_10 obj_04)
        (pred_2 obj_01)
    )

    (:goal
        (pred_4 obj_10 obj_14)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_01 obj_18) (pred_4 obj_01 obj_03))) (not (and (pred_3 obj_01 obj_03) (pred_4 obj_01 obj_18)))))
  )
)

