
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-274047307)
    (:domain delivery)

    (:objects
        obj_02 obj_01 obj_07 obj_06 - type_2
        obj_05 obj_04 - type_4
        obj_03 - type_3
    )

    (:init
        (pred_2 obj_06 obj_01)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_07 obj_06)
        (pred_2 obj_06 obj_07)
        (pred_2 obj_02 obj_01)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_01 obj_06)
        (pred_2 obj_02 obj_07)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_05 obj_02)
        (pred_4 obj_03)
    )

    (:goal
        (and (pred_3 obj_05 obj_06) (pred_3 obj_04 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_03 obj_01) (pred_3 obj_03 obj_06))) (not (and (pred_5 obj_03 obj_06) (pred_3 obj_03 obj_01)))))
  )
)

