
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-398743581)
    (:domain delivery)

    (:objects
        obj_01 obj_08 obj_12 obj_05 obj_02 obj_06 obj_13 obj_03 obj_18 obj_10 obj_15 obj_09 obj_04 obj_07 obj_16 obj_17 - type_2
        obj_11 - type_1
        obj_14 - type_3
    )

    (:init
        (pred_1 obj_15 obj_10)
        (pred_1 obj_18 obj_10)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_09 obj_15)
        (pred_1 obj_10 obj_18)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_03 obj_13)
        (pred_1 obj_07 obj_16)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_12 obj_08)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_04 obj_18)
        (pred_1 obj_13 obj_12)
        (pred_1 obj_12 obj_13)
        (pred_1 obj_18 obj_02)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_15 obj_13)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_16 obj_07)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_13 obj_15)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_16 obj_15)
        (pred_1 obj_16 obj_17)
        (pred_1 obj_13 obj_03)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_08 obj_12)
        (pred_1 obj_02 obj_18)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_17 obj_16)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_17 obj_09)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_18 obj_04)
        (pred_1 obj_15 obj_09)
        (pred_2 obj_14 obj_15)
        (pred_2 obj_11 obj_12)
        (pred_5 obj_14)
    )

    (:goal
        (pred_2 obj_11 obj_17)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_14 obj_05) (pred_2 obj_14 obj_03))) (not (and (pred_3 obj_14 obj_03) (pred_2 obj_14 obj_05)))))
  )
)

