
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-534659120)
    (:domain delivery)

    (:objects
        obj_17 obj_19 obj_07 obj_18 obj_02 obj_10 obj_06 obj_09 obj_04 obj_11 obj_03 obj_08 obj_12 obj_14 obj_05 obj_13 - type_4
        obj_15 obj_01 - type_2
        obj_16 - type_3
    )

    (:init
        (pred_5 obj_07 obj_19)
        (pred_5 obj_06 obj_10)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_17 obj_02)
        (pred_5 obj_03 obj_05)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_07 obj_18)
        (pred_5 obj_08 obj_03)
        (pred_5 obj_14 obj_05)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_12 obj_14)
        (pred_5 obj_14 obj_12)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_08 obj_09)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_11 obj_03)
        (pred_5 obj_13 obj_08)
        (pred_5 obj_19 obj_07)
        (pred_5 obj_05 obj_03)
        (pred_5 obj_10 obj_19)
        (pred_5 obj_08 obj_13)
        (pred_5 obj_13 obj_05)
        (pred_5 obj_19 obj_17)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_11 obj_14)
        (pred_5 obj_09 obj_18)
        (pred_5 obj_05 obj_14)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_18 obj_07)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_06 obj_09)
        (pred_5 obj_17 obj_19)
        (pred_5 obj_02 obj_04)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_02 obj_17)
        (pred_5 obj_10 obj_06)
        (pred_5 obj_09 obj_06)
        (pred_5 obj_04 obj_02)
        (pred_5 obj_03 obj_11)
        (pred_5 obj_09 obj_08)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_05 obj_13)
        (pred_5 obj_18 obj_09)
        (pred_5 obj_19 obj_10)
        (pred_5 obj_14 obj_11)
        (pred_3 obj_16 obj_11)
        (pred_3 obj_01 obj_10)
        (pred_3 obj_15 obj_06)
        (pred_4 obj_16)
    )

    (:goal
        (and (pred_3 obj_15 obj_05) (pred_3 obj_01 obj_05))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_16 obj_03) (pred_3 obj_16 obj_05))) (not (and (pred_1 obj_16 obj_05) (pred_3 obj_16 obj_03)))))
  )
)

