
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-988263078)
    (:domain delivery)

    (:objects
        obj_09 obj_11 obj_06 obj_07 obj_05 obj_12 obj_10 obj_08 obj_01 - type_1
        obj_03 obj_02 - type_4
        obj_04 - type_2
    )

    (:init
        (pred_2 obj_12 obj_01)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_12 obj_06)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_06 obj_11)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_11 obj_06)
        (pred_2 obj_05 obj_12)
        (pred_2 obj_12 obj_05)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_08 obj_05)
        (pred_2 obj_09 obj_07)
        (pred_2 obj_01 obj_12)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_02 obj_01)
        (pred_3 obj_04)
    )

    (:goal
        (and (pred_5 obj_03 obj_06) (pred_5 obj_02 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_04 obj_05) (pred_5 obj_04 obj_08))) (not (and (pred_1 obj_04 obj_08) (pred_5 obj_04 obj_05)))))
  )
)

