
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-199336821)
    (:domain delivery)

    (:objects
        obj_08 obj_11 obj_03 obj_06 obj_02 obj_07 obj_09 obj_04 obj_05 - type_2
        obj_10 - type_3
        obj_01 - type_1
    )

    (:init
        (pred_4 obj_02 obj_06)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_11 obj_08)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_11 obj_03)
        (pred_4 obj_04 obj_05)
        (pred_4 obj_05 obj_07)
        (pred_4 obj_02 obj_07)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_07 obj_05)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_03 obj_11)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_08 obj_11)
        (pred_2 obj_10 obj_03)
        (pred_2 obj_01 obj_08)
        (pred_5 obj_01)
    )

    (:goal
        (pred_2 obj_10 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_11) (pred_2 obj_01 obj_02))) (not (and (pred_1 obj_01 obj_02) (pred_2 obj_01 obj_11)))))
  )
)

