
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1418651861)
    (:domain delivery)

    (:objects
        obj_06 obj_10 obj_17 obj_07 obj_04 obj_02 obj_08 obj_16 obj_19 obj_03 obj_01 obj_12 obj_15 obj_11 obj_09 obj_05 - type_4
        obj_18 obj_14 - type_3
        obj_13 - type_2
    )

    (:init
        (pred_1 obj_17 obj_10)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_19 obj_15)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_15 obj_19)
        (pred_1 obj_17 obj_07)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_11 obj_09)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_15 obj_11)
        (pred_1 obj_11 obj_15)
        (pred_1 obj_17 obj_08)
        (pred_1 obj_12 obj_16)
        (pred_1 obj_03 obj_19)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_10 obj_17)
        (pred_1 obj_09 obj_01)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_08 obj_17)
        (pred_1 obj_03 obj_11)
        (pred_1 obj_16 obj_07)
        (pred_1 obj_09 obj_11)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_07 obj_17)
        (pred_1 obj_19 obj_03)
        (pred_1 obj_08 obj_16)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_04 obj_19)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_16 obj_08)
        (pred_1 obj_19 obj_04)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_16 obj_12)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_07 obj_16)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_11 obj_03)
        (pred_3 obj_13 obj_04)
        (pred_3 obj_18 obj_04)
        (pred_3 obj_14 obj_08)
        (pred_4 obj_13)
    )

    (:goal
        (and (pred_3 obj_18 obj_07) (pred_3 obj_14 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_13 obj_17) (pred_3 obj_13 obj_08))) (not (and (pred_2 obj_13 obj_08) (pred_3 obj_13 obj_17)))))
  )
)

