
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-293664191)
    (:domain delivery)

    (:objects
        obj_02 obj_06 obj_05 obj_01 - type_1
        obj_04 obj_03 - type_3
        obj_07 - type_2
    )

    (:init
        (pred_1 obj_01 obj_06)
        (pred_1 obj_05 obj_02)
        (pred_1 obj_05 obj_01)
        (pred_1 obj_01 obj_05)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_02 obj_05)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_04 obj_02)
        (pred_5 obj_07)
    )

    (:goal
        (and (pred_2 obj_04 obj_01) (pred_2 obj_03 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_07 obj_06) (pred_2 obj_07 obj_01))) (not (and (pred_4 obj_07 obj_01) (pred_2 obj_07 obj_06)))))
  )
)

