
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1774911611)
    (:domain delivery)

    (:objects
        obj_09 obj_02 obj_05 obj_11 obj_07 obj_03 obj_04 obj_10 obj_01 - type_1
        obj_06 - type_3
        obj_08 - type_4
    )

    (:init
        (pred_5 obj_07 obj_11)
        (pred_5 obj_03 obj_05)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_09 obj_11)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_01 obj_03)
        (pred_5 obj_07 obj_03)
        (pred_5 obj_05 obj_03)
        (pred_5 obj_10 obj_07)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_03 obj_01)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_01 obj_10)
        (pred_5 obj_07 obj_10)
        (pred_5 obj_11 obj_09)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_05 obj_02)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_09 obj_02)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_06 obj_10)
        (pred_1 obj_08)
    )

    (:goal
        (pred_2 obj_06 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_08 obj_07) (pred_2 obj_08 obj_10))) (not (and (pred_4 obj_08 obj_10) (pred_2 obj_08 obj_07)))))
  )
)

