
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1840323431)
    (:domain delivery)

    (:objects
        obj_10 obj_06 obj_08 obj_12 obj_11 obj_02 obj_01 obj_04 obj_07 - type_4
        obj_09 obj_05 - type_2
        obj_03 - type_3
    )

    (:init
        (pred_1 obj_02 obj_07)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_12 obj_11)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_12 obj_10)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_10 obj_12)
        (pred_1 obj_07 obj_02)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_03 obj_02)
        (pred_5 obj_03)
    )

    (:goal
        (and (pred_4 obj_09 obj_04) (pred_4 obj_05 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_03 obj_11) (pred_4 obj_03 obj_04))) (not (and (pred_2 obj_03 obj_04) (pred_4 obj_03 obj_11)))))
  )
)

