
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-267393145)
    (:domain delivery)

    (:objects
        obj_06 obj_04 obj_02 obj_01 obj_11 obj_03 obj_09 obj_08 obj_10 - type_4
        obj_07 - type_1
        obj_05 - type_2
    )

    (:init
        (pred_3 obj_11 obj_01)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_06 obj_01)
        (pred_3 obj_01 obj_09)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_08 obj_10)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_10 obj_08)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_09 obj_01)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_04 obj_11)
        (pred_3 obj_06 obj_04)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_05 obj_04)
        (pred_5 obj_05)
    )

    (:goal
        (pred_4 obj_07 obj_09)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_05 obj_01) (pred_4 obj_05 obj_09))) (not (and (pred_1 obj_05 obj_09) (pred_4 obj_05 obj_01)))))
  )
)

