
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-2106830674)
    (:domain delivery)

    (:objects
        obj_18 obj_01 obj_13 obj_08 obj_09 obj_02 obj_07 obj_14 obj_06 obj_10 obj_03 obj_05 obj_16 obj_11 obj_15 obj_12 - type_2
        obj_04 - type_1
        obj_17 - type_3
    )

    (:init
        (pred_1 obj_03 obj_10)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_05 obj_14)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_14 obj_07)
        (pred_1 obj_11 obj_15)
        (pred_1 obj_11 obj_16)
        (pred_1 obj_09 obj_18)
        (pred_1 obj_13 obj_01)
        (pred_1 obj_01 obj_18)
        (pred_1 obj_16 obj_11)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_16 obj_06)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_15 obj_11)
        (pred_1 obj_08 obj_13)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_13 obj_08)
        (pred_1 obj_07 obj_03)
        (pred_1 obj_14 obj_05)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_15 obj_12)
        (pred_1 obj_07 obj_14)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_18 obj_01)
        (pred_1 obj_01 obj_13)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_18 obj_09)
        (pred_1 obj_12 obj_15)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_06 obj_16)
        (pred_1 obj_03 obj_05)
        (pred_4 obj_17 obj_13)
        (pred_4 obj_04 obj_13)
        (pred_5 obj_17)
    )

    (:goal
        (pred_4 obj_04 obj_14)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_17 obj_08) (pred_4 obj_17 obj_14))) (not (and (pred_2 obj_17 obj_14) (pred_4 obj_17 obj_08)))))
  )
)

