
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1648685064)
    (:domain delivery)

    (:objects
        obj_14 obj_17 obj_11 obj_16 obj_01 obj_18 obj_06 obj_10 obj_09 obj_12 obj_15 obj_08 obj_04 obj_03 obj_07 obj_19 - type_2
        obj_02 obj_13 - type_1
        obj_05 - type_4
    )

    (:init
        (pred_2 obj_11 obj_17)
        (pred_2 obj_06 obj_18)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_15 obj_06)
        (pred_2 obj_14 obj_01)
        (pred_2 obj_15 obj_07)
        (pred_2 obj_15 obj_08)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_11 obj_16)
        (pred_2 obj_08 obj_15)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_01 obj_18)
        (pred_2 obj_04 obj_03)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_11 obj_06)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_12 obj_15)
        (pred_2 obj_19 obj_08)
        (pred_2 obj_17 obj_11)
        (pred_2 obj_07 obj_15)
        (pred_2 obj_18 obj_17)
        (pred_2 obj_08 obj_19)
        (pred_2 obj_19 obj_07)
        (pred_2 obj_17 obj_14)
        (pred_2 obj_06 obj_15)
        (pred_2 obj_06 obj_11)
        (pred_2 obj_12 obj_03)
        (pred_2 obj_10 obj_16)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_18 obj_12)
        (pred_2 obj_16 obj_11)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_06 obj_10)
        (pred_2 obj_14 obj_17)
        (pred_2 obj_01 obj_09)
        (pred_2 obj_18 obj_01)
        (pred_2 obj_01 obj_14)
        (pred_2 obj_18 obj_06)
        (pred_2 obj_10 obj_06)
        (pred_2 obj_09 obj_01)
        (pred_2 obj_15 obj_12)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_12 obj_18)
        (pred_2 obj_07 obj_19)
        (pred_2 obj_16 obj_10)
        (pred_2 obj_17 obj_18)
        (pred_2 obj_03 obj_12)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_13 obj_08)
        (pred_3 obj_05 obj_17)
        (pred_4 obj_05)
    )

    (:goal
        (and (pred_3 obj_02 obj_11) (pred_3 obj_13 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_05 obj_15) (pred_3 obj_05 obj_08))) (not (and (pred_1 obj_05 obj_08) (pred_3 obj_05 obj_15)))))
  )
)

