
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1142426307)
    (:domain delivery)

    (:objects
        obj_06 obj_08 obj_17 obj_12 obj_05 obj_11 obj_04 obj_18 obj_13 obj_02 obj_03 obj_16 obj_14 obj_10 obj_07 obj_01 - type_4
        obj_09 - type_1
        obj_15 - type_3
    )

    (:init
        (pred_5 obj_03 obj_02)
        (pred_5 obj_13 obj_02)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_16 obj_01)
        (pred_5 obj_16 obj_03)
        (pred_5 obj_02 obj_13)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_18 obj_04)
        (pred_5 obj_10 obj_07)
        (pred_5 obj_10 obj_14)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_17 obj_08)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_14 obj_10)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_02 obj_03)
        (pred_5 obj_14 obj_13)
        (pred_5 obj_04 obj_17)
        (pred_5 obj_17 obj_04)
        (pred_5 obj_13 obj_05)
        (pred_5 obj_18 obj_12)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_07 obj_10)
        (pred_5 obj_12 obj_17)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_17 obj_12)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_07 obj_03)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_04 obj_18)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_08 obj_17)
        (pred_5 obj_05 obj_13)
        (pred_5 obj_11 obj_08)
        (pred_5 obj_12 obj_18)
        (pred_5 obj_08 obj_11)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_01 obj_16)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_13 obj_14)
        (pred_5 obj_03 obj_16)
        (pred_3 obj_09 obj_03)
        (pred_3 obj_15 obj_16)
        (pred_1 obj_15)
    )

    (:goal
        (pred_3 obj_09 obj_17)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_15 obj_17) (pred_3 obj_15 obj_04))) (not (and (pred_4 obj_15 obj_04) (pred_3 obj_15 obj_17)))))
  )
)

