
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-2066653756)
    (:domain delivery)

    (:objects
        obj_06 obj_01 obj_04 obj_07 obj_11 obj_09 obj_12 obj_02 obj_03 - type_2
        obj_05 obj_08 - type_1
        obj_10 - type_4
    )

    (:init
        (pred_3 obj_09 obj_03)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_04 obj_09)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_09 obj_04)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_07 obj_06)
        (pred_3 obj_06 obj_01)
        (pred_3 obj_12 obj_02)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_02 obj_12)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_11 obj_07)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_11 obj_01)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_06 obj_07)
        (pred_3 obj_03 obj_09)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_10 obj_01)
        (pred_5 obj_10)
    )

    (:goal
        (and (pred_2 obj_05 obj_06) (pred_2 obj_08 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_10 obj_11) (pred_2 obj_10 obj_02))) (not (and (pred_1 obj_10 obj_02) (pred_2 obj_10 obj_11)))))
  )
)

