
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-365206915)
    (:domain delivery)

    (:objects
        obj_09 obj_10 obj_12 obj_18 obj_16 obj_15 obj_05 obj_17 obj_04 obj_14 obj_11 obj_01 obj_02 obj_03 obj_13 obj_07 - type_3
        obj_06 - type_2
        obj_08 - type_1
    )

    (:init
        (pred_2 obj_11 obj_14)
        (pred_2 obj_04 obj_14)
        (pred_2 obj_14 obj_15)
        (pred_2 obj_01 obj_17)
        (pred_2 obj_01 obj_07)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_14 obj_04)
        (pred_2 obj_14 obj_03)
        (pred_2 obj_17 obj_05)
        (pred_2 obj_03 obj_13)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_16 obj_09)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_10 obj_09)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_03 obj_14)
        (pred_2 obj_14 obj_11)
        (pred_2 obj_02 obj_04)
        (pred_2 obj_05 obj_12)
        (pred_2 obj_12 obj_05)
        (pred_2 obj_04 obj_16)
        (pred_2 obj_17 obj_18)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_05 obj_15)
        (pred_2 obj_13 obj_03)
        (pred_2 obj_18 obj_12)
        (pred_2 obj_15 obj_14)
        (pred_2 obj_12 obj_18)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_17 obj_01)
        (pred_2 obj_13 obj_11)
        (pred_2 obj_13 obj_07)
        (pred_2 obj_05 obj_17)
        (pred_2 obj_16 obj_15)
        (pred_2 obj_09 obj_10)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_16 obj_04)
        (pred_2 obj_15 obj_10)
        (pred_2 obj_18 obj_17)
        (pred_2 obj_10 obj_15)
        (pred_2 obj_15 obj_16)
        (pred_2 obj_09 obj_16)
        (pred_2 obj_07 obj_13)
        (pred_2 obj_15 obj_05)
        (pred_2 obj_07 obj_01)
        (pred_2 obj_11 obj_13)
        (pred_2 obj_04 obj_02)
        (pred_2 obj_11 obj_01)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_06 obj_02)
        (pred_3 obj_08)
    )

    (:goal
        (pred_5 obj_06 obj_12)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_08 obj_04) (pred_5 obj_08 obj_02))) (not (and (pred_1 obj_08 obj_02) (pred_5 obj_08 obj_04)))))
  )
)

