
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-22057207)
    (:domain delivery)

    (:objects
        obj_07 obj_10 obj_18 obj_01 obj_15 obj_02 obj_04 obj_14 obj_05 obj_11 obj_09 obj_06 obj_16 obj_03 obj_17 obj_08 - type_3
        obj_13 obj_12 - type_1
        obj_19 - type_2
    )

    (:init
        (pred_1 obj_18 obj_10)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_05 obj_16)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_07 obj_15)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_16 obj_05)
        (pred_1 obj_18 obj_01)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_15 obj_02)
        (pred_1 obj_16 obj_03)
        (pred_1 obj_03 obj_16)
        (pred_1 obj_18 obj_04)
        (pred_1 obj_06 obj_14)
        (pred_1 obj_11 obj_05)
        (pred_1 obj_11 obj_09)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_10 obj_18)
        (pred_1 obj_17 obj_09)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_08 obj_17)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_04 obj_18)
        (pred_1 obj_11 obj_03)
        (pred_1 obj_14 obj_01)
        (pred_1 obj_17 obj_03)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_01 obj_18)
        (pred_1 obj_05 obj_11)
        (pred_1 obj_04 obj_14)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_15 obj_05)
        (pred_1 obj_02 obj_15)
        (pred_1 obj_15 obj_07)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_14 obj_04)
        (pred_1 obj_05 obj_15)
        (pred_1 obj_09 obj_11)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_17 obj_08)
        (pred_1 obj_01 obj_14)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_03 obj_11)
        (pred_3 obj_19 obj_01)
        (pred_3 obj_13 obj_11)
        (pred_3 obj_12 obj_16)
        (pred_2 obj_19)
    )

    (:goal
        (and (pred_3 obj_13 obj_09) (pred_3 obj_12 obj_09))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_19 obj_05) (pred_3 obj_19 obj_16))) (not (and (pred_4 obj_19 obj_16) (pred_3 obj_19 obj_05)))))
  )
)

