
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1871195305)
    (:domain delivery)

    (:objects
        obj_13 obj_06 obj_17 obj_15 obj_04 obj_08 obj_02 obj_12 obj_18 obj_16 obj_09 obj_10 obj_14 obj_05 obj_03 obj_07 - type_3
        obj_11 - type_4
        obj_01 - type_2
    )

    (:init
        (pred_1 obj_09 obj_16)
        (pred_1 obj_18 obj_16)
        (pred_1 obj_16 obj_08)
        (pred_1 obj_10 obj_12)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_10 obj_09)
        (pred_1 obj_16 obj_18)
        (pred_1 obj_16 obj_05)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_05 obj_14)
        (pred_1 obj_04 obj_13)
        (pred_1 obj_17 obj_06)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_14 obj_05)
        (pred_1 obj_05 obj_16)
        (pred_1 obj_16 obj_09)
        (pred_1 obj_14 obj_18)
        (pred_1 obj_02 obj_17)
        (pred_1 obj_17 obj_02)
        (pred_1 obj_18 obj_04)
        (pred_1 obj_12 obj_15)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_15 obj_17)
        (pred_1 obj_08 obj_16)
        (pred_1 obj_17 obj_15)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_12 obj_10)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_06 obj_17)
        (pred_1 obj_04 obj_18)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_15 obj_12)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_13 obj_04)
        (pred_1 obj_07 obj_03)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_18 obj_14)
        (pred_1 obj_09 obj_10)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_01 obj_13)
        (pred_3 obj_01)
    )

    (:goal
        (pred_5 obj_11 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_01 obj_04) (pred_5 obj_01 obj_18))) (not (and (pred_4 obj_01 obj_18) (pred_5 obj_01 obj_04)))))
  )
)

