
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1722116920)
    (:domain delivery)

    (:objects
        obj_13 obj_10 obj_14 obj_05 obj_12 obj_01 obj_09 obj_17 obj_08 obj_15 obj_11 obj_02 obj_06 obj_03 obj_18 obj_04 - type_3
        obj_16 - type_4
        obj_07 - type_1
    )

    (:init
        (pred_5 obj_11 obj_15)
        (pred_5 obj_08 obj_15)
        (pred_5 obj_15 obj_01)
        (pred_5 obj_02 obj_17)
        (pred_5 obj_02 obj_04)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_15 obj_08)
        (pred_5 obj_15 obj_03)
        (pred_5 obj_17 obj_09)
        (pred_5 obj_03 obj_18)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_12 obj_13)
        (pred_5 obj_14 obj_10)
        (pred_5 obj_10 obj_13)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_03 obj_15)
        (pred_5 obj_15 obj_11)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_09 obj_14)
        (pred_5 obj_14 obj_09)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_17 obj_05)
        (pred_5 obj_11 obj_09)
        (pred_5 obj_09 obj_01)
        (pred_5 obj_18 obj_03)
        (pred_5 obj_05 obj_14)
        (pred_5 obj_01 obj_15)
        (pred_5 obj_14 obj_05)
        (pred_5 obj_09 obj_11)
        (pred_5 obj_17 obj_02)
        (pred_5 obj_18 obj_11)
        (pred_5 obj_18 obj_04)
        (pred_5 obj_09 obj_17)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_13 obj_10)
        (pred_5 obj_10 obj_14)
        (pred_5 obj_12 obj_08)
        (pred_5 obj_01 obj_10)
        (pred_5 obj_05 obj_17)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_13 obj_12)
        (pred_5 obj_04 obj_18)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_04 obj_02)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_11 obj_02)
        (pred_1 obj_16 obj_04)
        (pred_1 obj_07 obj_15)
        (pred_4 obj_07)
    )

    (:goal
        (pred_1 obj_16 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_07 obj_05) (pred_1 obj_07 obj_17))) (not (and (pred_3 obj_07 obj_17) (pred_1 obj_07 obj_05)))))
  )
)

