
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-2132624901)
    (:domain delivery)

    (:objects
        obj_13 obj_06 obj_09 obj_07 obj_17 obj_08 obj_19 obj_02 obj_10 obj_18 obj_15 obj_11 obj_12 obj_01 obj_04 obj_14 - type_2
        obj_05 obj_16 - type_1
        obj_03 - type_4
    )

    (:init
        (pred_2 obj_09 obj_06)
        (pred_2 obj_19 obj_08)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_15 obj_19)
        (pred_2 obj_13 obj_17)
        (pred_2 obj_15 obj_04)
        (pred_2 obj_15 obj_11)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_09 obj_07)
        (pred_2 obj_11 obj_15)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_17 obj_08)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_09 obj_19)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_18 obj_10)
        (pred_2 obj_18 obj_15)
        (pred_2 obj_14 obj_11)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_04 obj_15)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_11 obj_14)
        (pred_2 obj_14 obj_04)
        (pred_2 obj_06 obj_13)
        (pred_2 obj_19 obj_15)
        (pred_2 obj_19 obj_09)
        (pred_2 obj_18 obj_01)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_08 obj_18)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_10 obj_18)
        (pred_2 obj_19 obj_02)
        (pred_2 obj_13 obj_06)
        (pred_2 obj_17 obj_10)
        (pred_2 obj_08 obj_17)
        (pred_2 obj_17 obj_13)
        (pred_2 obj_08 obj_19)
        (pred_2 obj_02 obj_19)
        (pred_2 obj_10 obj_17)
        (pred_2 obj_15 obj_18)
        (pred_2 obj_02 obj_11)
        (pred_2 obj_18 obj_08)
        (pred_2 obj_04 obj_14)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_01 obj_18)
        (pred_4 obj_03 obj_14)
        (pred_4 obj_16 obj_13)
        (pred_4 obj_05 obj_19)
        (pred_3 obj_03)
    )

    (:goal
        (and (pred_4 obj_05 obj_08) (pred_4 obj_16 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_03 obj_06) (pred_4 obj_03 obj_08))) (not (and (pred_1 obj_03 obj_08) (pred_4 obj_03 obj_06)))))
  )
)

