
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-2109769345)
    (:domain delivery)

    (:objects
        obj_04 obj_10 obj_11 obj_07 obj_02 obj_01 obj_08 obj_06 obj_05 - type_4
        obj_09 - type_3
        obj_03 - type_2
    )

    (:init
        (pred_4 obj_02 obj_07)
        (pred_4 obj_01 obj_11)
        (pred_4 obj_10 obj_04)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_07 obj_08)
        (pred_4 obj_06 obj_08)
        (pred_4 obj_10 obj_11)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_11 obj_01)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_02 obj_10)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_04 obj_10)
        (pred_2 obj_03 obj_08)
        (pred_2 obj_09 obj_02)
        (pred_1 obj_03)
    )

    (:goal
        (pred_2 obj_09 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_01) (pred_2 obj_03 obj_05))) (not (and (pred_3 obj_03 obj_05) (pred_2 obj_03 obj_01)))))
  )
)

