
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1046662191)
    (:domain delivery)

    (:objects
        obj_07 obj_03 obj_09 obj_02 obj_11 obj_08 obj_12 obj_01 obj_10 - type_2
        obj_06 obj_04 - type_4
        obj_05 - type_3
    )

    (:init
        (pred_3 obj_08 obj_10)
        (pred_3 obj_10 obj_01)
        (pred_3 obj_12 obj_02)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_01 obj_10)
        (pred_3 obj_09 obj_03)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_07 obj_03)
        (pred_3 obj_12 obj_01)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_01 obj_12)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_02 obj_12)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_03 obj_09)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_11 obj_01)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_10 obj_08)
        (pred_2 obj_04 obj_02)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_06 obj_08)
        (pred_5 obj_05)
    )

    (:goal
        (and (pred_2 obj_06 obj_08) (pred_2 obj_04 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_05 obj_02) (pred_2 obj_05 obj_11))) (not (and (pred_4 obj_05 obj_11) (pred_2 obj_05 obj_02)))))
  )
)

