
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-817421900)
    (:domain delivery)

    (:objects
        obj_01 obj_07 obj_12 obj_19 obj_10 obj_15 obj_04 obj_02 obj_03 obj_05 obj_09 obj_06 obj_14 obj_08 obj_18 obj_16 - type_3
        obj_13 obj_17 - type_1
        obj_11 - type_4
    )

    (:init
        (pred_1 obj_12 obj_07)
        (pred_1 obj_04 obj_15)
        (pred_1 obj_03 obj_14)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_09 obj_18)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_14 obj_03)
        (pred_1 obj_12 obj_19)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_08 obj_18)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_12 obj_04)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_16 obj_06)
        (pred_1 obj_07 obj_12)
        (pred_1 obj_18 obj_09)
        (pred_1 obj_15 obj_07)
        (pred_1 obj_06 obj_16)
        (pred_1 obj_16 obj_18)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_04 obj_12)
        (pred_1 obj_05 obj_08)
        (pred_1 obj_02 obj_19)
        (pred_1 obj_18 obj_08)
        (pred_1 obj_15 obj_05)
        (pred_1 obj_19 obj_12)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_15 obj_04)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_03 obj_10)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_05 obj_15)
        (pred_1 obj_18 obj_16)
        (pred_1 obj_19 obj_02)
        (pred_1 obj_07 obj_15)
        (pred_1 obj_08 obj_05)
        (pred_3 obj_13 obj_16)
        (pred_3 obj_17 obj_03)
        (pred_3 obj_11 obj_14)
        (pred_4 obj_11)
    )

    (:goal
        (and (pred_3 obj_13 obj_07) (pred_3 obj_17 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_11 obj_15) (pred_3 obj_11 obj_05))) (not (and (pred_5 obj_11 obj_05) (pred_3 obj_11 obj_15)))))
  )
)

