
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1344620775)
    (:domain delivery)

    (:objects
        obj_12 obj_10 obj_11 obj_06 obj_04 obj_01 obj_05 obj_02 obj_03 - type_1
        obj_07 obj_09 - type_4
        obj_08 - type_3
    )

    (:init
        (pred_2 obj_01 obj_03)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_06 obj_04)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_04 obj_06)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_04 obj_02)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_02 obj_04)
        (pred_2 obj_12 obj_06)
        (pred_2 obj_03 obj_01)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_09 obj_04)
        (pred_5 obj_08 obj_05)
        (pred_1 obj_08)
    )

    (:goal
        (and (pred_5 obj_07 obj_12) (pred_5 obj_09 obj_12))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_08 obj_10) (pred_5 obj_08 obj_04))) (not (and (pred_4 obj_08 obj_04) (pred_5 obj_08 obj_10)))))
  )
)

