
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-2002891459)
    (:domain delivery)

    (:objects
        obj_05 obj_12 obj_11 obj_07 obj_10 obj_08 obj_04 obj_03 obj_06 - type_3
        obj_09 obj_02 - type_4
        obj_01 - type_2
    )

    (:init
        (pred_2 obj_08 obj_06)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_11 obj_08)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_08 obj_11)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_11 obj_12)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_05 obj_12)
        (pred_2 obj_04 obj_03)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_12 obj_05)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_12 obj_11)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_10 obj_03)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_03 obj_10)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_06 obj_08)
        (pred_3 obj_09 obj_06)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_02 obj_11)
        (pred_4 obj_01)
    )

    (:goal
        (and (pred_3 obj_09 obj_10) (pred_3 obj_02 obj_10))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_12) (pred_3 obj_01 obj_11))) (not (and (pred_1 obj_01 obj_11) (pred_3 obj_01 obj_12)))))
  )
)

