
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1053900582)
    (:domain delivery)

    (:objects
        obj_03 obj_05 obj_07 obj_10 obj_02 obj_01 obj_06 obj_08 obj_09 - type_1
        obj_04 - type_2
        obj_11 - type_4
    )

    (:init
        (pred_1 obj_02 obj_10)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_03 obj_10)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_09 obj_01)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_07 obj_05)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_05 obj_02)
        (pred_1 obj_03 obj_05)
        (pred_2 obj_04 obj_07)
        (pred_2 obj_11 obj_01)
        (pred_4 obj_11)
    )

    (:goal
        (pred_2 obj_04 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_11 obj_03) (pred_2 obj_11 obj_05))) (not (and (pred_3 obj_11 obj_05) (pred_2 obj_11 obj_03)))))
  )
)

