
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1098970929)
    (:domain delivery)

    (:objects
        obj_14 obj_18 obj_08 obj_17 obj_05 obj_01 obj_13 obj_04 obj_02 obj_16 obj_12 obj_15 obj_03 obj_11 obj_07 obj_06 - type_1
        obj_09 - type_3
        obj_10 - type_4
    )

    (:init
        (pred_3 obj_12 obj_16)
        (pred_3 obj_02 obj_16)
        (pred_3 obj_16 obj_01)
        (pred_3 obj_15 obj_04)
        (pred_3 obj_15 obj_06)
        (pred_3 obj_15 obj_12)
        (pred_3 obj_16 obj_02)
        (pred_3 obj_16 obj_11)
        (pred_3 obj_04 obj_13)
        (pred_3 obj_11 obj_07)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_05 obj_14)
        (pred_3 obj_08 obj_18)
        (pred_3 obj_18 obj_14)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_11 obj_16)
        (pred_3 obj_16 obj_12)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_13 obj_08)
        (pred_3 obj_08 obj_13)
        (pred_3 obj_02 obj_05)
        (pred_3 obj_04 obj_17)
        (pred_3 obj_12 obj_13)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_17 obj_08)
        (pred_3 obj_01 obj_16)
        (pred_3 obj_08 obj_17)
        (pred_3 obj_13 obj_12)
        (pred_3 obj_04 obj_15)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_07 obj_06)
        (pred_3 obj_13 obj_04)
        (pred_3 obj_05 obj_01)
        (pred_3 obj_14 obj_18)
        (pred_3 obj_18 obj_08)
        (pred_3 obj_05 obj_02)
        (pred_3 obj_01 obj_18)
        (pred_3 obj_17 obj_04)
        (pred_3 obj_18 obj_01)
        (pred_3 obj_01 obj_05)
        (pred_3 obj_14 obj_05)
        (pred_3 obj_06 obj_07)
        (pred_3 obj_01 obj_13)
        (pred_3 obj_06 obj_15)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_12 obj_15)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_09 obj_17)
        (pred_1 obj_10)
    )

    (:goal
        (pred_4 obj_09 obj_12)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_10 obj_08) (pred_4 obj_10 obj_17))) (not (and (pred_5 obj_10 obj_17) (pred_4 obj_10 obj_08)))))
  )
)

