
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-214840725)
    (:domain delivery)

    (:objects
        obj_04 obj_14 obj_15 obj_13 obj_18 obj_09 obj_05 obj_17 obj_03 obj_06 obj_10 obj_11 obj_01 obj_12 obj_16 obj_02 - type_2
        obj_07 obj_19 - type_1
        obj_08 - type_4
    )

    (:init
        (pred_2 obj_15 obj_14)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_10 obj_05)
        (pred_2 obj_04 obj_18)
        (pred_2 obj_10 obj_16)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_15 obj_13)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_12 obj_16)
        (pred_2 obj_18 obj_09)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_15 obj_05)
        (pred_2 obj_11 obj_17)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_06 obj_10)
        (pred_2 obj_02 obj_11)
        (pred_2 obj_14 obj_15)
        (pred_2 obj_16 obj_10)
        (pred_2 obj_09 obj_14)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_02 obj_16)
        (pred_2 obj_14 obj_04)
        (pred_2 obj_05 obj_10)
        (pred_2 obj_05 obj_15)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_17 obj_13)
        (pred_2 obj_16 obj_12)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_13 obj_15)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_05 obj_17)
        (pred_2 obj_04 obj_14)
        (pred_2 obj_18 obj_03)
        (pred_2 obj_09 obj_18)
        (pred_2 obj_18 obj_04)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_17 obj_05)
        (pred_2 obj_03 obj_18)
        (pred_2 obj_10 obj_06)
        (pred_2 obj_17 obj_11)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_16 obj_02)
        (pred_2 obj_13 obj_17)
        (pred_2 obj_14 obj_09)
        (pred_2 obj_12 obj_06)
        (pred_5 obj_07 obj_18)
        (pred_5 obj_19 obj_18)
        (pred_5 obj_08 obj_14)
        (pred_4 obj_08)
    )

    (:goal
        (and (pred_5 obj_07 obj_12) (pred_5 obj_19 obj_12))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_08 obj_09) (pred_5 obj_08 obj_06))) (not (and (pred_3 obj_08 obj_06) (pred_5 obj_08 obj_09)))))
  )
)

