
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-1133649898)
    (:domain delivery)

    (:objects
        obj_05 obj_06 obj_04 obj_01 - type_4
        obj_02 obj_07 - type_1
        obj_03 - type_2
    )

    (:init
        (pred_2 obj_01 obj_06)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_06 obj_01)
        (pred_2 obj_05 obj_04)
        (pred_1 obj_03 obj_04)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_07 obj_06)
        (pred_5 obj_03)
    )

    (:goal
        (and (pred_1 obj_02 obj_04) (pred_1 obj_07 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_03 obj_05) (pred_1 obj_03 obj_06))) (not (and (pred_4 obj_03 obj_06) (pred_1 obj_03 obj_05)))))
  )
)

