
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-292407928)
    (:domain delivery)

    (:objects
        obj_02 obj_01 obj_08 obj_06 obj_10 obj_11 obj_13 obj_14 obj_12 obj_05 obj_09 obj_15 obj_04 obj_18 obj_16 obj_17 - type_3
        obj_07 - type_1
        obj_03 - type_4
    )

    (:init
        (pred_5 obj_09 obj_05)
        (pred_5 obj_12 obj_05)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_15 obj_14)
        (pred_5 obj_15 obj_17)
        (pred_5 obj_15 obj_09)
        (pred_5 obj_05 obj_12)
        (pred_5 obj_05 obj_18)
        (pred_5 obj_14 obj_13)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_18 obj_04)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_08 obj_01)
        (pred_5 obj_01 obj_02)
        (pred_5 obj_04 obj_18)
        (pred_5 obj_18 obj_05)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_13 obj_08)
        (pred_5 obj_08 obj_13)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_09 obj_13)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_13 obj_09)
        (pred_5 obj_14 obj_15)
        (pred_5 obj_16 obj_09)
        (pred_5 obj_16 obj_17)
        (pred_5 obj_13 obj_14)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_02 obj_01)
        (pred_5 obj_01 obj_08)
        (pred_5 obj_10 obj_12)
        (pred_5 obj_11 obj_01)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_01 obj_11)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_17 obj_16)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_17 obj_15)
        (pred_5 obj_09 obj_16)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_09 obj_15)
        (pred_4 obj_07 obj_05)
        (pred_4 obj_03 obj_18)
        (pred_3 obj_03)
    )

    (:goal
        (pred_4 obj_07 obj_10)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_03 obj_11) (pred_4 obj_03 obj_05))) (not (and (pred_2 obj_03 obj_05) (pred_4 obj_03 obj_11)))))
  )
)

