
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-267868526)
    (:domain delivery)

    (:objects
        obj_10 obj_07 obj_04 obj_02 obj_06 obj_05 obj_01 obj_08 obj_09 - type_4
        obj_11 - type_1
        obj_03 - type_2
    )

    (:init
        (pred_1 obj_06 obj_02)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_06 obj_05)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_05 obj_06)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_06 obj_07)
        (pred_1 obj_07 obj_06)
        (pred_1 obj_10 obj_07)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_11 obj_01)
        (pred_4 obj_03)
    )

    (:goal
        (pred_3 obj_11 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_03 obj_02) (pred_3 obj_03 obj_01))) (not (and (pred_5 obj_03 obj_01) (pred_3 obj_03 obj_02)))))
  )
)

