
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1085318200)
    (:domain delivery)

    (:objects
        obj_06 obj_07 obj_11 obj_04 obj_03 obj_05 obj_02 obj_09 obj_10 - type_1
        obj_08 - type_2
        obj_01 - type_4
    )

    (:init
        (pred_3 obj_03 obj_04)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_07 obj_06)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_09 obj_02)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_09 obj_03)
        (pred_3 obj_04 obj_03)
        (pred_3 obj_05 obj_10)
        (pred_3 obj_02 obj_09)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_10 obj_09)
        (pred_3 obj_03 obj_09)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_11 obj_07)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_07 obj_03)
        (pred_3 obj_06 obj_07)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_08 obj_02)
        (pred_5 obj_01)
    )

    (:goal
        (pred_4 obj_08 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_01 obj_04) (pred_4 obj_01 obj_02))) (not (and (pred_2 obj_01 obj_02) (pred_4 obj_01 obj_04)))))
  )
)

