
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1641566893)
    (:domain delivery)

    (:objects
        obj_09 obj_04 obj_11 obj_18 obj_05 obj_10 obj_12 obj_06 obj_15 obj_03 obj_16 obj_02 obj_13 obj_07 obj_08 obj_01 - type_3
        obj_14 - type_1
        obj_17 - type_2
    )

    (:init
        (pred_2 obj_16 obj_03)
        (pred_2 obj_15 obj_03)
        (pred_2 obj_03 obj_10)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_02 obj_01)
        (pred_2 obj_02 obj_16)
        (pred_2 obj_03 obj_15)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_07 obj_08)
        (pred_2 obj_07 obj_13)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_11 obj_04)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_13 obj_07)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_03 obj_16)
        (pred_2 obj_13 obj_15)
        (pred_2 obj_12 obj_11)
        (pred_2 obj_11 obj_12)
        (pred_2 obj_15 obj_05)
        (pred_2 obj_06 obj_18)
        (pred_2 obj_16 obj_12)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_08 obj_07)
        (pred_2 obj_18 obj_11)
        (pred_2 obj_10 obj_03)
        (pred_2 obj_11 obj_18)
        (pred_2 obj_12 obj_16)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_08 obj_16)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_12 obj_06)
        (pred_2 obj_05 obj_10)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_04 obj_11)
        (pred_2 obj_05 obj_15)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_18 obj_06)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_10 obj_05)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_16 obj_08)
        (pred_2 obj_15 obj_13)
        (pred_2 obj_16 obj_02)
        (pred_1 obj_17 obj_11)
        (pred_1 obj_14 obj_11)
        (pred_3 obj_17)
    )

    (:goal
        (pred_1 obj_14 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_17 obj_04) (pred_1 obj_17 obj_10))) (not (and (pred_4 obj_17 obj_10) (pred_1 obj_17 obj_04)))))
  )
)

