
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-947218077)
    (:domain delivery)

    (:objects
        obj_03 obj_05 obj_06 obj_02 - type_3
        obj_04 - type_1
        obj_01 - type_2
    )

    (:init
        (pred_4 obj_03 obj_06)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_06 obj_03)
        (pred_4 obj_03 obj_05)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_05 obj_03)
        (pred_4 obj_05 obj_02)
        (pred_5 obj_04 obj_05)
        (pred_5 obj_01 obj_06)
        (pred_3 obj_01)
    )

    (:goal
        (pred_5 obj_04 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_01 obj_03) (pred_5 obj_01 obj_05))) (not (and (pred_2 obj_01 obj_05) (pred_5 obj_01 obj_03)))))
  )
)

