
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-429760718)
    (:domain delivery)

    (:objects
        obj_03 obj_01 obj_02 obj_05 - type_2
        obj_06 obj_07 - type_1
        obj_04 - type_3
    )

    (:init
        (pred_2 obj_05 obj_01)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_03 obj_02)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_06 obj_02)
        (pred_5 obj_04 obj_02)
        (pred_1 obj_04)
    )

    (:goal
        (and (pred_5 obj_06 obj_01) (pred_5 obj_07 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_03) (pred_5 obj_04 obj_01))) (not (and (pred_3 obj_04 obj_01) (pred_5 obj_04 obj_03)))))
  )
)

