
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-675696208)
    (:domain delivery)

    (:objects
        obj_12 obj_01 obj_05 obj_09 obj_07 obj_10 obj_06 obj_08 obj_04 - type_1
        obj_02 obj_03 - type_2
        obj_11 - type_3
    )

    (:init
        (pred_2 obj_10 obj_04)
        (pred_2 obj_04 obj_08)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_05 obj_10)
        (pred_2 obj_09 obj_07)
        (pred_2 obj_10 obj_05)
        (pred_2 obj_08 obj_04)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_01 obj_07)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_07 obj_08)
        (pred_2 obj_07 obj_01)
        (pred_2 obj_08 obj_07)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_04 obj_10)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_03 obj_04)
        (pred_4 obj_11)
    )

    (:goal
        (and (pred_1 obj_02 obj_04) (pred_1 obj_03 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_11 obj_10) (pred_1 obj_11 obj_04))) (not (and (pred_5 obj_11 obj_04) (pred_1 obj_11 obj_10)))))
  )
)

