
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-351124208)
    (:domain delivery)

    (:objects
        obj_04 obj_09 obj_07 obj_05 obj_01 obj_11 obj_03 obj_10 obj_06 - type_3
        obj_02 - type_2
        obj_08 - type_4
    )

    (:init
        (pred_2 obj_01 obj_05)
        (pred_2 obj_11 obj_07)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_05 obj_03)
        (pred_2 obj_10 obj_03)
        (pred_2 obj_09 obj_07)
        (pred_2 obj_10 obj_06)
        (pred_2 obj_06 obj_11)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_07 obj_11)
        (pred_2 obj_10 obj_01)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_11 obj_06)
        (pred_2 obj_03 obj_10)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_06 obj_10)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_03 obj_05)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_01 obj_09)
        (pred_2 obj_09 obj_01)
        (pred_2 obj_04 obj_09)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_08 obj_11)
        (pred_1 obj_08)
    )

    (:goal
        (pred_3 obj_02 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_08 obj_09) (pred_3 obj_08 obj_01))) (not (and (pred_5 obj_08 obj_01) (pred_3 obj_08 obj_09)))))
  )
)

