
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-556862602)
    (:domain delivery)

    (:objects
        obj_04 obj_06 obj_05 obj_07 - type_3
        obj_03 obj_02 - type_4
        obj_01 - type_2
    )

    (:init
        (pred_1 obj_07 obj_06)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_07 obj_05)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_06 obj_07)
        (pred_1 obj_04 obj_05)
        (pred_5 obj_02 obj_05)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_01 obj_07)
        (pred_4 obj_01)
    )

    (:goal
        (and (pred_5 obj_03 obj_06) (pred_5 obj_02 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_01 obj_04) (pred_5 obj_01 obj_06))) (not (and (pred_3 obj_01 obj_06) (pred_5 obj_01 obj_04)))))
  )
)

