
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-72785438)
    (:domain delivery)

    (:objects
        obj_07 obj_04 obj_01 obj_18 obj_13 obj_09 obj_08 obj_03 obj_16 obj_05 obj_10 obj_12 obj_17 obj_06 obj_15 obj_02 - type_1
        obj_14 - type_3
        obj_11 - type_4
    )

    (:init
        (pred_5 obj_10 obj_05)
        (pred_5 obj_16 obj_05)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_12 obj_03)
        (pred_5 obj_12 obj_02)
        (pred_5 obj_12 obj_10)
        (pred_5 obj_05 obj_16)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_03 obj_08)
        (pred_5 obj_06 obj_15)
        (pred_5 obj_06 obj_17)
        (pred_5 obj_13 obj_07)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_17 obj_06)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_17 obj_16)
        (pred_5 obj_08 obj_01)
        (pred_5 obj_01 obj_08)
        (pred_5 obj_16 obj_13)
        (pred_5 obj_03 obj_18)
        (pred_5 obj_10 obj_08)
        (pred_5 obj_08 obj_09)
        (pred_5 obj_15 obj_06)
        (pred_5 obj_18 obj_01)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_01 obj_18)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_03 obj_12)
        (pred_5 obj_15 obj_10)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_08 obj_03)
        (pred_5 obj_13 obj_09)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_13 obj_16)
        (pred_5 obj_09 obj_04)
        (pred_5 obj_18 obj_03)
        (pred_5 obj_04 obj_09)
        (pred_5 obj_09 obj_13)
        (pred_5 obj_07 obj_13)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_09 obj_08)
        (pred_5 obj_02 obj_12)
        (pred_5 obj_10 obj_15)
        (pred_5 obj_16 obj_17)
        (pred_5 obj_10 obj_12)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_14 obj_09)
        (pred_4 obj_11)
    )

    (:goal
        (pred_3 obj_14 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_11 obj_09) (pred_3 obj_11 obj_05))) (not (and (pred_2 obj_11 obj_05) (pred_3 obj_11 obj_09)))))
  )
)

