
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1967935042)
    (:domain delivery)

    (:objects
        obj_06 obj_02 obj_01 obj_03 obj_07 obj_08 obj_11 obj_10 obj_09 - type_3
        obj_04 - type_1
        obj_05 - type_2
    )

    (:init
        (pred_3 obj_07 obj_03)
        (pred_3 obj_08 obj_01)
        (pred_3 obj_02 obj_06)
        (pred_3 obj_06 obj_03)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_10 obj_11)
        (pred_3 obj_02 obj_01)
        (pred_3 obj_10 obj_09)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_07 obj_08)
        (pred_3 obj_01 obj_08)
        (pred_3 obj_10 obj_07)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_07 obj_10)
        (pred_3 obj_03 obj_06)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_01 obj_02)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_06 obj_02)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_05 obj_03)
        (pred_1 obj_05)
    )

    (:goal
        (pred_5 obj_04 obj_09)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_05 obj_01) (pred_5 obj_05 obj_08))) (not (and (pred_4 obj_05 obj_08) (pred_5 obj_05 obj_01)))))
  )
)

