
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1608739203)
    (:domain delivery)

    (:objects
        obj_12 obj_09 obj_11 obj_04 obj_07 obj_01 obj_02 obj_03 obj_06 - type_3
        obj_08 obj_05 - type_1
        obj_10 - type_2
    )

    (:init
        (pred_3 obj_01 obj_06)
        (pred_3 obj_06 obj_03)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_11 obj_01)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_03 obj_06)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_12 obj_09)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_09 obj_07)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_09 obj_12)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_07 obj_01)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_07 obj_03)
        (pred_3 obj_07 obj_09)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_06 obj_01)
        (pred_2 obj_08 obj_04)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_10 obj_02)
        (pred_5 obj_10)
    )

    (:goal
        (and (pred_2 obj_08 obj_11) (pred_2 obj_05 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_10 obj_09) (pred_2 obj_10 obj_07))) (not (and (pred_4 obj_10 obj_07) (pred_2 obj_10 obj_09)))))
  )
)

