
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1117399751)
    (:domain delivery)

    (:objects
        obj_02 obj_15 obj_08 obj_14 obj_17 obj_10 obj_12 obj_03 obj_06 obj_16 obj_01 obj_04 obj_07 obj_19 obj_18 obj_09 - type_4
        obj_13 obj_05 - type_3
        obj_11 - type_2
    )

    (:init
        (pred_4 obj_08 obj_15)
        (pred_4 obj_12 obj_10)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_01 obj_12)
        (pred_4 obj_02 obj_17)
        (pred_4 obj_01 obj_18)
        (pred_4 obj_01 obj_04)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_08 obj_14)
        (pred_4 obj_04 obj_01)
        (pred_4 obj_19 obj_18)
        (pred_4 obj_17 obj_10)
        (pred_4 obj_07 obj_19)
        (pred_4 obj_19 obj_07)
        (pred_4 obj_08 obj_12)
        (pred_4 obj_04 obj_03)
        (pred_4 obj_16 obj_06)
        (pred_4 obj_16 obj_01)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_15 obj_08)
        (pred_4 obj_18 obj_01)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_09 obj_18)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_12 obj_01)
        (pred_4 obj_12 obj_08)
        (pred_4 obj_16 obj_19)
        (pred_4 obj_03 obj_14)
        (pred_4 obj_18 obj_19)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_14 obj_08)
        (pred_4 obj_06 obj_16)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_17 obj_06)
        (pred_4 obj_10 obj_17)
        (pred_4 obj_17 obj_02)
        (pred_4 obj_10 obj_12)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_06 obj_17)
        (pred_4 obj_01 obj_16)
        (pred_4 obj_03 obj_04)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_18 obj_09)
        (pred_4 obj_14 obj_03)
        (pred_4 obj_15 obj_10)
        (pred_4 obj_19 obj_16)
        (pred_5 obj_11 obj_12)
        (pred_5 obj_13 obj_02)
        (pred_5 obj_05 obj_09)
        (pred_3 obj_11)
    )

    (:goal
        (and (pred_5 obj_13 obj_17) (pred_5 obj_05 obj_17))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_11 obj_12) (pred_5 obj_11 obj_03))) (not (and (pred_2 obj_11 obj_03) (pred_5 obj_11 obj_12)))))
  )
)

