
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-298608569)
    (:domain delivery)

    (:objects
        obj_05 obj_16 obj_02 obj_18 obj_01 obj_12 obj_15 obj_17 obj_06 obj_08 obj_10 obj_04 obj_03 obj_13 obj_14 obj_07 - type_1
        obj_09 - type_4
        obj_11 - type_2
    )

    (:init
        (pred_5 obj_10 obj_08)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_04 obj_17)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_08 obj_13)
        (pred_5 obj_17 obj_15)
        (pred_5 obj_13 obj_14)
        (pred_5 obj_13 obj_03)
        (pred_5 obj_01 obj_05)
        (pred_5 obj_02 obj_16)
        (pred_5 obj_16 obj_05)
        (pred_5 obj_03 obj_13)
        (pred_5 obj_13 obj_08)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_17 obj_18)
        (pred_5 obj_10 obj_15)
        (pred_5 obj_15 obj_12)
        (pred_5 obj_14 obj_13)
        (pred_5 obj_18 obj_02)
        (pred_5 obj_12 obj_08)
        (pred_5 obj_02 obj_18)
        (pred_5 obj_15 obj_10)
        (pred_5 obj_17 obj_04)
        (pred_5 obj_14 obj_10)
        (pred_5 obj_14 obj_07)
        (pred_5 obj_15 obj_17)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_05 obj_16)
        (pred_5 obj_16 obj_02)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_12 obj_16)
        (pred_5 obj_18 obj_17)
        (pred_5 obj_16 obj_12)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_07 obj_14)
        (pred_5 obj_12 obj_15)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_10 obj_14)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_10 obj_04)
        (pred_4 obj_11 obj_15)
        (pred_4 obj_09 obj_15)
        (pred_2 obj_11)
    )

    (:goal
        (pred_4 obj_09 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_11 obj_15) (pred_4 obj_11 obj_17))) (not (and (pred_1 obj_11 obj_17) (pred_4 obj_11 obj_15)))))
  )
)

