
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-222705592)
    (:domain delivery)

    (:objects
        obj_02 obj_01 obj_07 obj_05 - type_3
        obj_03 obj_06 - type_4
        obj_04 - type_2
    )

    (:init
        (pred_1 obj_05 obj_01)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_07 obj_05)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_01 obj_05)
        (pred_1 obj_02 obj_07)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_03 obj_02)
        (pred_4 obj_04)
    )

    (:goal
        (and (pred_5 obj_03 obj_05) (pred_5 obj_06 obj_05))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_04 obj_01) (pred_5 obj_04 obj_05))) (not (and (pred_2 obj_04 obj_05) (pred_5 obj_04 obj_01)))))
  )
)

