
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1529082108)
    (:domain delivery)

    (:objects
        obj_01 obj_06 obj_10 obj_08 obj_02 obj_14 obj_11 obj_04 obj_18 obj_16 obj_07 obj_12 obj_03 obj_15 obj_13 obj_17 - type_3
        obj_09 - type_4
        obj_05 - type_1
    )

    (:init
        (pred_1 obj_07 obj_16)
        (pred_1 obj_18 obj_16)
        (pred_1 obj_16 obj_14)
        (pred_1 obj_12 obj_04)
        (pred_1 obj_12 obj_17)
        (pred_1 obj_12 obj_07)
        (pred_1 obj_16 obj_18)
        (pred_1 obj_16 obj_15)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_15 obj_13)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_16 obj_07)
        (pred_1 obj_03 obj_18)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_18 obj_02)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_07 obj_11)
        (pred_1 obj_11 obj_14)
        (pred_1 obj_13 obj_15)
        (pred_1 obj_08 obj_10)
        (pred_1 obj_14 obj_16)
        (pred_1 obj_10 obj_08)
        (pred_1 obj_11 obj_07)
        (pred_1 obj_04 obj_12)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_13 obj_17)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_02 obj_14)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_02 obj_18)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_06 obj_14)
        (pred_1 obj_14 obj_02)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_17 obj_13)
        (pred_1 obj_14 obj_11)
        (pred_1 obj_17 obj_12)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_18 obj_03)
        (pred_1 obj_07 obj_12)
        (pred_3 obj_09 obj_06)
        (pred_3 obj_05 obj_14)
        (pred_2 obj_05)
    )

    (:goal
        (pred_3 obj_09 obj_17)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_05 obj_08) (pred_3 obj_05 obj_04))) (not (and (pred_5 obj_05 obj_04) (pred_3 obj_05 obj_08)))))
  )
)

