
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-2042114690)
    (:domain delivery)

    (:objects
        obj_05 obj_07 obj_15 obj_02 obj_08 obj_17 obj_14 obj_01 obj_16 obj_04 obj_09 obj_03 obj_10 obj_06 obj_18 obj_19 - type_3
        obj_13 obj_11 - type_1
        obj_12 - type_2
    )

    (:init
        (pred_4 obj_15 obj_07)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_09 obj_14)
        (pred_4 obj_05 obj_08)
        (pred_4 obj_09 obj_18)
        (pred_4 obj_09 obj_03)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_06 obj_18)
        (pred_4 obj_08 obj_17)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_15 obj_14)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_04 obj_16)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_19 obj_03)
        (pred_4 obj_07 obj_15)
        (pred_4 obj_18 obj_09)
        (pred_4 obj_17 obj_07)
        (pred_4 obj_03 obj_19)
        (pred_4 obj_19 obj_18)
        (pred_4 obj_07 obj_05)
        (pred_4 obj_14 obj_09)
        (pred_4 obj_14 obj_15)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_18 obj_06)
        (pred_4 obj_17 obj_04)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_16 obj_04)
        (pred_4 obj_14 obj_01)
        (pred_4 obj_05 obj_07)
        (pred_4 obj_08 obj_16)
        (pred_4 obj_17 obj_08)
        (pred_4 obj_08 obj_05)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_01 obj_14)
        (pred_4 obj_16 obj_08)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_04 obj_17)
        (pred_4 obj_18 obj_19)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_07 obj_17)
        (pred_4 obj_06 obj_04)
        (pred_1 obj_13 obj_17)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_12 obj_06)
        (pred_3 obj_12)
    )

    (:goal
        (and (pred_1 obj_13 obj_14) (pred_1 obj_11 obj_14))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_12 obj_16) (pred_1 obj_12 obj_10))) (not (and (pred_5 obj_12 obj_10) (pred_1 obj_12 obj_16)))))
  )
)

