
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1275510184)
    (:domain delivery)

    (:objects
        obj_12 obj_08 obj_09 obj_02 obj_11 obj_03 obj_07 obj_04 obj_06 - type_4
        obj_01 obj_05 - type_3
        obj_10 - type_1
    )

    (:init
        (pred_3 obj_03 obj_06)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_09 obj_03)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_03 obj_09)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_02 obj_12)
        (pred_3 obj_12 obj_08)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_08 obj_12)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_11 obj_03)
        (pred_3 obj_03 obj_11)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_04 obj_11)
        (pred_3 obj_12 obj_02)
        (pred_3 obj_06 obj_03)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_10 obj_11)
        (pred_2 obj_10)
    )

    (:goal
        (and (pred_4 obj_01 obj_12) (pred_4 obj_05 obj_12))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_10 obj_08) (pred_4 obj_10 obj_11))) (not (and (pred_1 obj_10 obj_11) (pred_4 obj_10 obj_08)))))
  )
)

