
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1478019682)
    (:domain delivery)

    (:objects
        obj_06 obj_04 obj_09 obj_05 obj_01 obj_02 obj_03 obj_11 obj_10 - type_4
        obj_07 - type_2
        obj_08 - type_3
    )

    (:init
        (pred_5 obj_01 obj_05)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_04 obj_06)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_05 obj_03)
        (pred_5 obj_11 obj_03)
        (pred_5 obj_04 obj_09)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_01 obj_02)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_11 obj_01)
        (pred_5 obj_05 obj_01)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_03 obj_11)
        (pred_5 obj_02 obj_01)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_01 obj_11)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_03 obj_05)
        (pred_5 obj_09 obj_04)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_06 obj_04)
        (pred_4 obj_08 obj_03)
        (pred_4 obj_07 obj_06)
        (pred_1 obj_08)
    )

    (:goal
        (pred_4 obj_07 obj_10)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_08 obj_09) (pred_4 obj_08 obj_02))) (not (and (pred_2 obj_08 obj_02) (pred_4 obj_08 obj_09)))))
  )
)

