
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1043227794)
    (:domain delivery)

    (:objects
        obj_08 obj_10 obj_01 obj_09 obj_06 obj_11 obj_07 obj_02 obj_05 - type_4
        obj_04 - type_2
        obj_03 - type_3
    )

    (:init
        (pred_1 obj_06 obj_09)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_10 obj_08)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_05 obj_11)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_11 obj_05)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_05 obj_02)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_08 obj_10)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_04 obj_09)
        (pred_2 obj_03)
    )

    (:goal
        (pred_4 obj_04 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_03 obj_06) (pred_4 obj_03 obj_02))) (not (and (pred_5 obj_03 obj_02) (pred_4 obj_03 obj_06)))))
  )
)

