
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-306366542)
    (:domain delivery)

    (:objects
        obj_03 obj_15 obj_07 obj_05 obj_18 obj_11 obj_10 obj_16 obj_13 obj_14 obj_04 obj_06 obj_02 obj_17 obj_12 obj_01 - type_3
        obj_08 - type_1
        obj_09 - type_2
    )

    (:init
        (pred_3 obj_04 obj_14)
        (pred_3 obj_13 obj_14)
        (pred_3 obj_14 obj_11)
        (pred_3 obj_06 obj_16)
        (pred_3 obj_06 obj_01)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_14 obj_13)
        (pred_3 obj_14 obj_17)
        (pred_3 obj_16 obj_10)
        (pred_3 obj_17 obj_12)
        (pred_3 obj_17 obj_02)
        (pred_3 obj_18 obj_03)
        (pred_3 obj_07 obj_15)
        (pred_3 obj_15 obj_03)
        (pred_3 obj_02 obj_17)
        (pred_3 obj_17 obj_14)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_02 obj_13)
        (pred_3 obj_10 obj_07)
        (pred_3 obj_07 obj_10)
        (pred_3 obj_13 obj_18)
        (pred_3 obj_16 obj_05)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_10 obj_11)
        (pred_3 obj_12 obj_17)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_11 obj_14)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_16 obj_06)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_12 obj_01)
        (pred_3 obj_10 obj_16)
        (pred_3 obj_18 obj_11)
        (pred_3 obj_03 obj_15)
        (pred_3 obj_15 obj_07)
        (pred_3 obj_18 obj_13)
        (pred_3 obj_11 obj_15)
        (pred_3 obj_05 obj_16)
        (pred_3 obj_15 obj_11)
        (pred_3 obj_11 obj_18)
        (pred_3 obj_03 obj_18)
        (pred_3 obj_01 obj_12)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_13 obj_02)
        (pred_3 obj_04 obj_06)
        (pred_5 obj_08 obj_11)
        (pred_5 obj_09 obj_16)
        (pred_2 obj_09)
    )

    (:goal
        (pred_5 obj_08 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_09 obj_10) (pred_5 obj_09 obj_16))) (not (and (pred_4 obj_09 obj_16) (pred_5 obj_09 obj_10)))))
  )
)

