
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-2096978741)
    (:domain delivery)

    (:objects
        obj_08 obj_01 obj_04 obj_06 obj_10 obj_05 obj_03 obj_07 obj_11 - type_2
        obj_02 - type_4
        obj_09 - type_3
    )

    (:init
        (pred_1 obj_10 obj_06)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_01 obj_08)
        (pred_1 obj_08 obj_06)
        (pred_1 obj_06 obj_03)
        (pred_1 obj_07 obj_03)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_07 obj_11)
        (pred_1 obj_11 obj_05)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_05 obj_11)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_11 obj_07)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_06 obj_08)
        (pred_1 obj_03 obj_06)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_08 obj_01)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_02 obj_11)
        (pred_4 obj_09)
    )

    (:goal
        (pred_3 obj_02 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_09 obj_07) (pred_3 obj_09 obj_11))) (not (and (pred_2 obj_09 obj_11) (pred_3 obj_09 obj_07)))))
  )
)

