
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-710812961)
    (:domain delivery)

    (:objects
        obj_04 obj_03 obj_01 obj_07 - type_2
        obj_05 obj_02 - type_1
        obj_06 - type_4
    )

    (:init
        (pred_5 obj_07 obj_03)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_03 obj_07)
        (pred_5 obj_04 obj_01)
        (pred_4 obj_06 obj_01)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_02 obj_07)
        (pred_2 obj_06)
    )

    (:goal
        (and (pred_4 obj_05 obj_04) (pred_4 obj_02 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_06 obj_03) (pred_4 obj_06 obj_07))) (not (and (pred_1 obj_06 obj_07) (pred_4 obj_06 obj_03)))))
  )
)

