
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1188429970)
    (:domain delivery)

    (:objects
        obj_19 obj_18 obj_04 obj_07 obj_17 obj_03 obj_16 obj_10 obj_05 obj_01 obj_09 obj_15 obj_14 obj_06 obj_11 obj_12 - type_4
        obj_13 obj_08 - type_1
        obj_02 - type_3
    )

    (:init
        (pred_4 obj_04 obj_18)
        (pred_4 obj_16 obj_03)
        (pred_4 obj_05 obj_14)
        (pred_4 obj_09 obj_16)
        (pred_4 obj_19 obj_17)
        (pred_4 obj_09 obj_11)
        (pred_4 obj_09 obj_15)
        (pred_4 obj_14 obj_05)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_15 obj_09)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_17 obj_03)
        (pred_4 obj_14 obj_06)
        (pred_4 obj_06 obj_14)
        (pred_4 obj_04 obj_16)
        (pred_4 obj_15 obj_10)
        (pred_4 obj_01 obj_05)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_12 obj_15)
        (pred_4 obj_18 obj_04)
        (pred_4 obj_11 obj_09)
        (pred_4 obj_03 obj_18)
        (pred_4 obj_15 obj_12)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_18 obj_19)
        (pred_4 obj_16 obj_09)
        (pred_4 obj_16 obj_04)
        (pred_4 obj_01 obj_06)
        (pred_4 obj_10 obj_07)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_05 obj_01)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_19 obj_18)
        (pred_4 obj_17 obj_05)
        (pred_4 obj_03 obj_17)
        (pred_4 obj_17 obj_19)
        (pred_4 obj_03 obj_16)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_05 obj_17)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_07 obj_10)
        (pred_4 obj_18 obj_03)
        (pred_4 obj_06 obj_01)
        (pred_1 obj_13 obj_19)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_08 obj_01)
        (pred_5 obj_02)
    )

    (:goal
        (and (pred_1 obj_13 obj_06) (pred_1 obj_08 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_02 obj_18) (pred_1 obj_02 obj_03))) (not (and (pred_3 obj_02 obj_03) (pred_1 obj_02 obj_18)))))
  )
)

