
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1621415914)
    (:domain delivery)

    (:objects
        obj_14 obj_08 obj_13 obj_09 obj_18 obj_07 obj_01 obj_16 obj_02 obj_15 obj_11 obj_19 obj_04 obj_05 obj_12 obj_17 - type_3
        obj_10 obj_03 - type_2
        obj_06 - type_1
    )

    (:init
        (pred_1 obj_13 obj_08)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_14 obj_18)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_11 obj_19)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_13 obj_09)
        (pred_1 obj_19 obj_11)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_18 obj_07)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_13 obj_01)
        (pred_1 obj_19 obj_16)
        (pred_1 obj_15 obj_02)
        (pred_1 obj_15 obj_11)
        (pred_1 obj_17 obj_19)
        (pred_1 obj_08 obj_13)
        (pred_1 obj_12 obj_11)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_19 obj_17)
        (pred_1 obj_17 obj_12)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_01 obj_13)
        (pred_1 obj_15 obj_05)
        (pred_1 obj_16 obj_09)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_07 obj_15)
        (pred_1 obj_09 obj_13)
        (pred_1 obj_02 obj_15)
        (pred_1 obj_01 obj_16)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_18 obj_02)
        (pred_1 obj_07 obj_18)
        (pred_1 obj_18 obj_14)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_16 obj_01)
        (pred_1 obj_02 obj_18)
        (pred_1 obj_11 obj_15)
        (pred_1 obj_16 obj_19)
        (pred_1 obj_15 obj_07)
        (pred_1 obj_12 obj_17)
        (pred_1 obj_09 obj_16)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_05 obj_15)
        (pred_2 obj_10 obj_15)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_06 obj_19)
        (pred_4 obj_06)
    )

    (:goal
        (and (pred_2 obj_10 obj_13) (pred_2 obj_03 obj_13))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_06 obj_07) (pred_2 obj_06 obj_15))) (not (and (pred_5 obj_06 obj_15) (pred_2 obj_06 obj_07)))))
  )
)

