
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-577180111)
    (:domain delivery)

    (:objects
        obj_03 obj_04 obj_09 obj_07 obj_06 obj_10 obj_01 obj_02 obj_11 - type_4
        obj_05 - type_3
        obj_08 - type_1
    )

    (:init
        (pred_4 obj_06 obj_07)
        (pred_4 obj_10 obj_09)
        (pred_4 obj_04 obj_03)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_07 obj_01)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_11 obj_10)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_09 obj_10)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_10 obj_11)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_01 obj_07)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_06 obj_04)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_03 obj_04)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_05 obj_06)
        (pred_2 obj_08)
    )

    (:goal
        (pred_5 obj_05 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_08 obj_07) (pred_5 obj_08 obj_01))) (not (and (pred_1 obj_08 obj_01) (pred_5 obj_08 obj_07)))))
  )
)

