
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1614069994)
    (:domain delivery)

    (:objects
        obj_08 obj_11 obj_06 obj_03 obj_04 obj_09 obj_05 obj_07 obj_02 - type_3
        obj_01 - type_4
        obj_10 - type_1
    )

    (:init
        (pred_1 obj_04 obj_03)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_11 obj_08)
        (pred_1 obj_08 obj_03)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_07 obj_05)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_03 obj_04)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_03 obj_08)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_08 obj_11)
        (pred_2 obj_01 obj_09)
        (pred_2 obj_10 obj_07)
        (pred_3 obj_10)
    )

    (:goal
        (pred_2 obj_01 obj_08)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_10 obj_08) (pred_2 obj_10 obj_11))) (not (and (pred_4 obj_10 obj_11) (pred_2 obj_10 obj_08)))))
  )
)

