
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-882708554)
    (:domain delivery)

    (:objects
        obj_17 obj_09 obj_15 obj_04 obj_14 obj_19 obj_03 obj_07 obj_02 obj_10 obj_01 obj_18 obj_16 obj_13 obj_12 obj_05 - type_1
        obj_11 obj_06 - type_3
        obj_08 - type_4
    )

    (:init
        (pred_1 obj_15 obj_09)
        (pred_1 obj_03 obj_19)
        (pred_1 obj_02 obj_16)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_01 obj_18)
        (pred_1 obj_16 obj_02)
        (pred_1 obj_15 obj_04)
        (pred_1 obj_18 obj_01)
        (pred_1 obj_13 obj_12)
        (pred_1 obj_14 obj_19)
        (pred_1 obj_16 obj_13)
        (pred_1 obj_13 obj_16)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_18 obj_07)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_05 obj_18)
        (pred_1 obj_09 obj_15)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_19 obj_09)
        (pred_1 obj_18 obj_05)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_10 obj_13)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_12 obj_13)
        (pred_1 obj_19 obj_10)
        (pred_1 obj_04 obj_15)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_17 obj_09)
        (pred_1 obj_14 obj_02)
        (pred_1 obj_19 obj_14)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_19 obj_03)
        (pred_1 obj_07 obj_03)
        (pred_1 obj_02 obj_14)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_07 obj_18)
        (pred_1 obj_10 obj_19)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_04 obj_07)
        (pred_1 obj_09 obj_19)
        (pred_1 obj_13 obj_10)
        (pred_4 obj_06 obj_03)
        (pred_4 obj_08 obj_19)
        (pred_4 obj_11 obj_12)
        (pred_5 obj_08)
    )

    (:goal
        (and (pred_4 obj_11 obj_17) (pred_4 obj_06 obj_17))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_08 obj_15) (pred_4 obj_08 obj_03))) (not (and (pred_2 obj_08 obj_03) (pred_4 obj_08 obj_15)))))
  )
)

