
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-2022182987)
    (:domain delivery)

    (:objects
        obj_02 obj_01 obj_15 obj_07 obj_19 obj_13 obj_16 obj_17 obj_05 obj_14 obj_18 obj_03 obj_09 obj_04 obj_06 obj_10 - type_1
        obj_12 obj_11 - type_3
        obj_08 - type_2
    )

    (:init
        (pred_3 obj_15 obj_01)
        (pred_3 obj_16 obj_13)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_18 obj_16)
        (pred_3 obj_02 obj_19)
        (pred_3 obj_18 obj_06)
        (pred_3 obj_18 obj_03)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_15 obj_07)
        (pred_3 obj_03 obj_18)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_19 obj_13)
        (pred_3 obj_09 obj_04)
        (pred_3 obj_04 obj_09)
        (pred_3 obj_15 obj_16)
        (pred_3 obj_03 obj_17)
        (pred_3 obj_14 obj_05)
        (pred_3 obj_14 obj_18)
        (pred_3 obj_10 obj_03)
        (pred_3 obj_01 obj_15)
        (pred_3 obj_06 obj_18)
        (pred_3 obj_13 obj_01)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_01 obj_02)
        (pred_3 obj_16 obj_18)
        (pred_3 obj_16 obj_15)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_17 obj_07)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_13 obj_14)
        (pred_3 obj_07 obj_15)
        (pred_3 obj_05 obj_14)
        (pred_3 obj_16 obj_17)
        (pred_3 obj_02 obj_01)
        (pred_3 obj_19 obj_05)
        (pred_3 obj_13 obj_19)
        (pred_3 obj_19 obj_02)
        (pred_3 obj_13 obj_16)
        (pred_3 obj_17 obj_16)
        (pred_3 obj_05 obj_19)
        (pred_3 obj_18 obj_14)
        (pred_3 obj_17 obj_03)
        (pred_3 obj_14 obj_13)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_07 obj_17)
        (pred_3 obj_01 obj_13)
        (pred_3 obj_04 obj_14)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_11 obj_03)
        (pred_5 obj_08 obj_06)
        (pred_2 obj_08)
    )

    (:goal
        (and (pred_5 obj_12 obj_03) (pred_5 obj_11 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_08 obj_18) (pred_5 obj_08 obj_03))) (not (and (pred_4 obj_08 obj_03) (pred_5 obj_08 obj_18)))))
  )
)

