
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1163240685)
    (:domain delivery)

    (:objects
        obj_07 obj_09 obj_04 obj_10 obj_03 obj_11 obj_02 obj_01 obj_06 - type_1
        obj_08 - type_4
        obj_05 - type_3
    )

    (:init
        (pred_1 obj_03 obj_10)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_03 obj_11)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_11 obj_03)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_07 obj_09)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_08 obj_03)
        (pred_5 obj_05)
    )

    (:goal
        (pred_2 obj_08 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_05 obj_09) (pred_2 obj_05 obj_03))) (not (and (pred_3 obj_05 obj_03) (pred_2 obj_05 obj_09)))))
  )
)

