
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-105535807)
    (:domain delivery)

    (:objects
        obj_14 obj_19 obj_12 obj_06 obj_02 obj_18 obj_08 obj_09 obj_11 obj_15 obj_17 obj_03 obj_10 obj_16 obj_04 obj_13 - type_1
        obj_05 obj_07 - type_2
        obj_01 - type_3
    )

    (:init
        (pred_1 obj_12 obj_19)
        (pred_1 obj_08 obj_18)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_17 obj_08)
        (pred_1 obj_14 obj_02)
        (pred_1 obj_17 obj_04)
        (pred_1 obj_17 obj_03)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_16 obj_04)
        (pred_1 obj_02 obj_18)
        (pred_1 obj_10 obj_16)
        (pred_1 obj_16 obj_10)
        (pred_1 obj_12 obj_08)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_15 obj_11)
        (pred_1 obj_15 obj_17)
        (pred_1 obj_13 obj_03)
        (pred_1 obj_19 obj_12)
        (pred_1 obj_04 obj_17)
        (pred_1 obj_18 obj_19)
        (pred_1 obj_03 obj_13)
        (pred_1 obj_13 obj_04)
        (pred_1 obj_19 obj_14)
        (pred_1 obj_08 obj_17)
        (pred_1 obj_08 obj_12)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_04 obj_16)
        (pred_1 obj_18 obj_15)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_11 obj_15)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_14 obj_19)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_18 obj_02)
        (pred_1 obj_02 obj_14)
        (pred_1 obj_18 obj_08)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_17 obj_15)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_15 obj_18)
        (pred_1 obj_04 obj_13)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_19 obj_18)
        (pred_1 obj_16 obj_15)
        (pred_5 obj_01 obj_08)
        (pred_5 obj_05 obj_14)
        (pred_5 obj_07 obj_15)
        (pred_3 obj_01)
    )

    (:goal
        (and (pred_5 obj_05 obj_08) (pred_5 obj_07 obj_08))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_01 obj_18) (pred_5 obj_01 obj_15))) (not (and (pred_2 obj_01 obj_15) (pred_5 obj_01 obj_18)))))
  )
)

