
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1154645025)
    (:domain delivery)

    (:objects
        obj_01 obj_02 obj_11 obj_04 obj_10 obj_09 obj_07 obj_06 obj_03 - type_4
        obj_05 - type_3
        obj_08 - type_2
    )

    (:init
        (pred_5 obj_10 obj_04)
        (pred_5 obj_09 obj_11)
        (pred_5 obj_02 obj_01)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_06 obj_03)
        (pred_5 obj_03 obj_09)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_11 obj_09)
        (pred_5 obj_06 obj_10)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_03 obj_06)
        (pred_5 obj_10 obj_06)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_01 obj_02)
        (pred_3 obj_08 obj_10)
        (pred_3 obj_05 obj_07)
        (pred_2 obj_08)
    )

    (:goal
        (pred_3 obj_05 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_08 obj_04) (pred_3 obj_08 obj_07))) (not (and (pred_1 obj_08 obj_07) (pred_3 obj_08 obj_04)))))
  )
)

