
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-814317121)
    (:domain delivery)

    (:objects
        obj_05 obj_18 obj_11 obj_04 obj_09 obj_16 obj_02 obj_15 obj_17 obj_14 obj_07 obj_01 obj_06 obj_10 obj_13 obj_12 - type_1
        obj_08 - type_3
        obj_03 - type_4
    )

    (:init
        (pred_1 obj_07 obj_14)
        (pred_1 obj_17 obj_14)
        (pred_1 obj_14 obj_16)
        (pred_1 obj_01 obj_15)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_14 obj_10)
        (pred_1 obj_15 obj_02)
        (pred_1 obj_10 obj_13)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_11 obj_18)
        (pred_1 obj_18 obj_05)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_10 obj_14)
        (pred_1 obj_14 obj_07)
        (pred_1 obj_06 obj_17)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_17 obj_09)
        (pred_1 obj_15 obj_04)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_02 obj_16)
        (pred_1 obj_13 obj_10)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_16 obj_14)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_15 obj_01)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_13 obj_12)
        (pred_1 obj_02 obj_15)
        (pred_1 obj_09 obj_16)
        (pred_1 obj_05 obj_18)
        (pred_1 obj_18 obj_11)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_16 obj_18)
        (pred_1 obj_04 obj_15)
        (pred_1 obj_18 obj_16)
        (pred_1 obj_16 obj_09)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_12 obj_13)
        (pred_1 obj_16 obj_02)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_17 obj_06)
        (pred_1 obj_07 obj_01)
        (pred_4 obj_08 obj_18)
        (pred_4 obj_03 obj_01)
        (pred_3 obj_03)
    )

    (:goal
        (pred_4 obj_08 obj_12)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_03 obj_04) (pred_4 obj_03 obj_15))) (not (and (pred_5 obj_03 obj_15) (pred_4 obj_03 obj_04)))))
  )
)

