
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-315899850)
    (:domain delivery)

    (:objects
        obj_01 obj_07 obj_06 obj_10 obj_11 obj_05 obj_03 obj_04 obj_12 - type_4
        obj_09 obj_02 - type_1
        obj_08 - type_3
    )

    (:init
        (pred_5 obj_05 obj_12)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_10 obj_11)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_11 obj_10)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_11 obj_07)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_01 obj_10)
        (pred_5 obj_12 obj_05)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_09 obj_01)
        (pred_2 obj_08 obj_10)
        (pred_4 obj_08)
    )

    (:goal
        (and (pred_2 obj_09 obj_04) (pred_2 obj_02 obj_04))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_08 obj_07) (pred_2 obj_08 obj_11))) (not (and (pred_1 obj_08 obj_11) (pred_2 obj_08 obj_07)))))
  )
)

