
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1685490373)
    (:domain delivery)

    (:objects
        obj_09 obj_03 obj_04 obj_05 obj_02 obj_06 obj_01 obj_07 obj_10 - type_1
        obj_11 obj_08 - type_4
        obj_12 - type_3
    )

    (:init
        (pred_2 obj_06 obj_10)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_04 obj_06)
        (pred_2 obj_05 obj_02)
        (pred_2 obj_06 obj_04)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_04 obj_03)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_01 obj_07)
        (pred_2 obj_03 obj_02)
        (pred_2 obj_07 obj_01)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_03 obj_04)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_02 obj_03)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_10 obj_06)
        (pred_4 obj_08 obj_06)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_12 obj_09)
        (pred_5 obj_12)
    )

    (:goal
        (and (pred_4 obj_11 obj_01) (pred_4 obj_08 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_12 obj_05) (pred_4 obj_12 obj_01))) (not (and (pred_1 obj_12 obj_01) (pred_4 obj_12 obj_05)))))
  )
)

