
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-416250183)
    (:domain delivery)

    (:objects
        obj_11 obj_09 obj_05 obj_16 obj_13 obj_10 obj_06 obj_08 obj_02 obj_14 obj_17 obj_04 obj_07 obj_18 obj_12 obj_03 - type_4
        obj_01 - type_2
        obj_15 - type_1
    )

    (:init
        (pred_3 obj_17 obj_14)
        (pred_3 obj_02 obj_14)
        (pred_3 obj_14 obj_10)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_04 obj_03)
        (pred_3 obj_04 obj_17)
        (pred_3 obj_14 obj_02)
        (pred_3 obj_14 obj_18)
        (pred_3 obj_08 obj_06)
        (pred_3 obj_18 obj_12)
        (pred_3 obj_18 obj_07)
        (pred_3 obj_13 obj_11)
        (pred_3 obj_05 obj_09)
        (pred_3 obj_09 obj_11)
        (pred_3 obj_07 obj_18)
        (pred_3 obj_18 obj_14)
        (pred_3 obj_14 obj_17)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_06 obj_05)
        (pred_3 obj_05 obj_06)
        (pred_3 obj_02 obj_13)
        (pred_3 obj_08 obj_16)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_12 obj_18)
        (pred_3 obj_16 obj_05)
        (pred_3 obj_10 obj_14)
        (pred_3 obj_05 obj_16)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_12 obj_17)
        (pred_3 obj_12 obj_03)
        (pred_3 obj_06 obj_08)
        (pred_3 obj_13 obj_10)
        (pred_3 obj_11 obj_09)
        (pred_3 obj_09 obj_05)
        (pred_3 obj_13 obj_02)
        (pred_3 obj_10 obj_09)
        (pred_3 obj_16 obj_08)
        (pred_3 obj_09 obj_10)
        (pred_3 obj_10 obj_13)
        (pred_3 obj_11 obj_13)
        (pred_3 obj_03 obj_12)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_03 obj_04)
        (pred_3 obj_17 obj_12)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_17 obj_04)
        (pred_5 obj_01 obj_14)
        (pred_5 obj_15 obj_06)
        (pred_4 obj_15)
    )

    (:goal
        (pred_5 obj_01 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_15 obj_17) (pred_5 obj_15 obj_04))) (not (and (pred_2 obj_15 obj_04) (pred_5 obj_15 obj_17)))))
  )
)

