
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-466045373)
    (:domain delivery)

    (:objects
        obj_11 obj_04 obj_10 obj_06 obj_02 obj_01 obj_07 obj_05 obj_09 - type_3
        obj_08 - type_1
        obj_03 - type_2
    )

    (:init
        (pred_4 obj_02 obj_06)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_04 obj_11)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_05 obj_07)
        (pred_4 obj_04 obj_10)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_09 obj_01)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_01 obj_09)
        (pred_4 obj_07 obj_05)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_10 obj_04)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_11 obj_04)
        (pred_1 obj_08 obj_11)
        (pred_1 obj_03 obj_11)
        (pred_2 obj_03)
    )

    (:goal
        (pred_1 obj_08 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_03 obj_04) (pred_1 obj_03 obj_02))) (not (and (pred_5 obj_03 obj_02) (pred_1 obj_03 obj_04)))))
  )
)

