
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-813384110)
    (:domain delivery)

    (:objects
        obj_04 obj_06 obj_11 obj_09 obj_05 obj_01 obj_02 obj_07 obj_03 - type_1
        obj_10 - type_2
        obj_08 - type_4
    )

    (:init
        (pred_2 obj_05 obj_09)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_06 obj_04)
        (pred_2 obj_04 obj_09)
        (pred_2 obj_09 obj_02)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_06 obj_11)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_05 obj_01)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_01 obj_05)
        (pred_2 obj_03 obj_07)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_09 obj_04)
        (pred_2 obj_02 obj_09)
        (pred_2 obj_11 obj_06)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_04 obj_06)
        (pred_5 obj_10 obj_01)
        (pred_5 obj_08 obj_03)
        (pred_4 obj_08)
    )

    (:goal
        (pred_5 obj_10 obj_09)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_08 obj_09) (pred_5 obj_08 obj_05))) (not (and (pred_1 obj_08 obj_05) (pred_5 obj_08 obj_09)))))
  )
)

