
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-1517489075)
    (:domain delivery)

    (:objects
        obj_11 obj_02 obj_09 obj_05 obj_07 obj_03 obj_10 obj_04 obj_08 - type_2
        obj_06 - type_1
        obj_01 - type_4
    )

    (:init
        (pred_3 obj_07 obj_05)
        (pred_3 obj_03 obj_09)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_05 obj_10)
        (pred_3 obj_04 obj_10)
        (pred_3 obj_02 obj_09)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_07 obj_03)
        (pred_3 obj_09 obj_03)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_10 obj_04)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_09 obj_02)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_11 obj_02)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_01 obj_05)
        (pred_4 obj_01)
    )

    (:goal
        (pred_2 obj_06 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_09) (pred_2 obj_01 obj_03))) (not (and (pred_1 obj_01 obj_03) (pred_2 obj_01 obj_09)))))
  )
)

