
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1759308031)
    (:domain delivery)

    (:objects
        obj_11 obj_12 obj_02 obj_15 obj_17 obj_01 obj_07 obj_06 obj_14 obj_04 obj_08 obj_18 obj_16 obj_10 obj_13 obj_03 - type_1
        obj_09 - type_4
        obj_05 - type_3
    )

    (:init
        (pred_4 obj_08 obj_04)
        (pred_4 obj_14 obj_04)
        (pred_4 obj_04 obj_01)
        (pred_4 obj_18 obj_06)
        (pred_4 obj_18 obj_03)
        (pred_4 obj_18 obj_08)
        (pred_4 obj_04 obj_14)
        (pred_4 obj_04 obj_10)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_10 obj_13)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_17 obj_11)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_10 obj_04)
        (pred_4 obj_04 obj_08)
        (pred_4 obj_16 obj_14)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_02 obj_07)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_06 obj_15)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_07 obj_01)
        (pred_4 obj_13 obj_10)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_01 obj_04)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_07 obj_08)
        (pred_4 obj_06 obj_18)
        (pred_4 obj_13 obj_08)
        (pred_4 obj_13 obj_03)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_17 obj_01)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_12 obj_02)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_01 obj_12)
        (pred_4 obj_15 obj_06)
        (pred_4 obj_12 obj_01)
        (pred_4 obj_01 obj_17)
        (pred_4 obj_11 obj_17)
        (pred_4 obj_03 obj_13)
        (pred_4 obj_01 obj_07)
        (pred_4 obj_03 obj_18)
        (pred_4 obj_08 obj_13)
        (pred_4 obj_14 obj_16)
        (pred_4 obj_08 obj_18)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_09 obj_13)
        (pred_1 obj_05)
    )

    (:goal
        (pred_3 obj_09 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_05 obj_08) (pred_3 obj_05 obj_13))) (not (and (pred_2 obj_05 obj_13) (pred_3 obj_05 obj_08)))))
  )
)

