
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1362055993)
    (:domain delivery)

    (:objects
        obj_02 obj_11 obj_05 obj_09 obj_03 obj_04 obj_10 obj_08 obj_01 obj_13 obj_15 obj_06 obj_12 obj_18 obj_16 obj_07 - type_1
        obj_17 - type_3
        obj_14 - type_4
    )

    (:init
        (pred_5 obj_15 obj_13)
        (pred_5 obj_01 obj_13)
        (pred_5 obj_13 obj_04)
        (pred_5 obj_06 obj_08)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_06 obj_15)
        (pred_5 obj_13 obj_01)
        (pred_5 obj_13 obj_18)
        (pred_5 obj_08 obj_10)
        (pred_5 obj_18 obj_16)
        (pred_5 obj_18 obj_12)
        (pred_5 obj_03 obj_02)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_12 obj_18)
        (pred_5 obj_18 obj_13)
        (pred_5 obj_13 obj_15)
        (pred_5 obj_12 obj_01)
        (pred_5 obj_10 obj_05)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_01 obj_03)
        (pred_5 obj_08 obj_09)
        (pred_5 obj_15 obj_10)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_16 obj_18)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_04 obj_13)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_10 obj_15)
        (pred_5 obj_08 obj_06)
        (pred_5 obj_16 obj_15)
        (pred_5 obj_16 obj_07)
        (pred_5 obj_10 obj_08)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_03 obj_01)
        (pred_5 obj_04 obj_11)
        (pred_5 obj_09 obj_08)
        (pred_5 obj_11 obj_04)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_02 obj_03)
        (pred_5 obj_07 obj_16)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_15 obj_16)
        (pred_5 obj_01 obj_12)
        (pred_5 obj_15 obj_06)
        (pred_4 obj_14 obj_10)
        (pred_4 obj_17 obj_12)
        (pred_3 obj_14)
    )

    (:goal
        (pred_4 obj_17 obj_10)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_14 obj_01) (pred_4 obj_14 obj_12))) (not (and (pred_1 obj_14 obj_12) (pred_4 obj_14 obj_01)))))
  )
)

