
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1728813023)
    (:domain delivery)

    (:objects
        obj_14 obj_06 obj_18 obj_11 obj_08 obj_09 obj_10 obj_15 obj_07 obj_13 obj_01 obj_12 obj_02 obj_16 obj_04 obj_05 - type_2
        obj_03 - type_1
        obj_17 - type_4
    )

    (:init
        (pred_1 obj_01 obj_13)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_13 obj_09)
        (pred_1 obj_12 obj_15)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_13 obj_16)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_16 obj_04)
        (pred_1 obj_16 obj_02)
        (pred_1 obj_08 obj_14)
        (pred_1 obj_18 obj_06)
        (pred_1 obj_06 obj_14)
        (pred_1 obj_02 obj_16)
        (pred_1 obj_16 obj_13)
        (pred_1 obj_13 obj_01)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_10 obj_18)
        (pred_1 obj_18 obj_10)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_15 obj_11)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_10 obj_09)
        (pred_1 obj_04 obj_16)
        (pred_1 obj_11 obj_18)
        (pred_1 obj_09 obj_13)
        (pred_1 obj_18 obj_11)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_15 obj_12)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_14 obj_06)
        (pred_1 obj_06 obj_18)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_11 obj_15)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_14 obj_08)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_09 obj_10)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_01 obj_12)
        (pred_3 obj_03 obj_04)
        (pred_3 obj_17 obj_16)
        (pred_2 obj_17)
    )

    (:goal
        (pred_3 obj_03 obj_14)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_17 obj_18) (pred_3 obj_17 obj_10))) (not (and (pred_5 obj_17 obj_10) (pred_3 obj_17 obj_18)))))
  )
)

