
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-997311979)
    (:domain delivery)

    (:objects
        obj_18 obj_16 obj_10 obj_05 obj_04 obj_12 obj_15 obj_14 obj_02 obj_08 obj_09 obj_13 obj_11 obj_01 obj_07 obj_06 - type_4
        obj_19 obj_03 - type_2
        obj_17 - type_1
    )

    (:init
        (pred_1 obj_10 obj_16)
        (pred_1 obj_15 obj_12)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_09 obj_15)
        (pred_1 obj_18 obj_04)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_09 obj_13)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_13 obj_09)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_04 obj_12)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_13 obj_14)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_06 obj_13)
        (pred_1 obj_16 obj_10)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_12 obj_16)
        (pred_1 obj_13 obj_06)
        (pred_1 obj_06 obj_07)
        (pred_1 obj_16 obj_18)
        (pred_1 obj_15 obj_09)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_08 obj_01)
        (pred_1 obj_14 obj_05)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_12 obj_08)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_15 obj_14)
        (pred_1 obj_18 obj_16)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_12 obj_04)
        (pred_1 obj_04 obj_18)
        (pred_1 obj_12 obj_15)
        (pred_1 obj_14 obj_15)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_14 obj_13)
        (pred_1 obj_08 obj_12)
        (pred_1 obj_07 obj_06)
        (pred_1 obj_05 obj_14)
        (pred_1 obj_16 obj_12)
        (pred_1 obj_01 obj_08)
        (pred_5 obj_19 obj_08)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_17 obj_16)
        (pred_2 obj_17)
    )

    (:goal
        (and (pred_5 obj_19 obj_16) (pred_5 obj_03 obj_16))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_17 obj_12) (pred_5 obj_17 obj_08))) (not (and (pred_3 obj_17 obj_08) (pred_5 obj_17 obj_12)))))
  )
)

