
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-567197637)
    (:domain delivery)

    (:objects
        obj_07 obj_12 obj_06 obj_17 obj_13 obj_05 obj_04 obj_14 obj_18 obj_02 obj_16 obj_11 obj_08 obj_03 obj_15 obj_10 - type_3
        obj_01 obj_09 - type_2
        obj_19 - type_1
    )

    (:init
        (pred_3 obj_06 obj_12)
        (pred_3 obj_04 obj_05)
        (pred_3 obj_18 obj_08)
        (pred_3 obj_16 obj_04)
        (pred_3 obj_07 obj_13)
        (pred_3 obj_16 obj_15)
        (pred_3 obj_16 obj_11)
        (pred_3 obj_08 obj_18)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_11 obj_16)
        (pred_3 obj_03 obj_15)
        (pred_3 obj_13 obj_05)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_11 obj_14)
        (pred_3 obj_02 obj_18)
        (pred_3 obj_02 obj_16)
        (pred_3 obj_10 obj_11)
        (pred_3 obj_12 obj_06)
        (pred_3 obj_15 obj_16)
        (pred_3 obj_05 obj_12)
        (pred_3 obj_11 obj_10)
        (pred_3 obj_10 obj_15)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_04 obj_16)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_14 obj_17)
        (pred_3 obj_15 obj_03)
        (pred_3 obj_05 obj_02)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_18 obj_02)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_13 obj_18)
        (pred_3 obj_05 obj_13)
        (pred_3 obj_13 obj_07)
        (pred_3 obj_05 obj_04)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_18 obj_13)
        (pred_3 obj_16 obj_02)
        (pred_3 obj_14 obj_11)
        (pred_3 obj_02 obj_05)
        (pred_3 obj_15 obj_10)
        (pred_3 obj_17 obj_14)
        (pred_3 obj_12 obj_05)
        (pred_3 obj_03 obj_02)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_19 obj_07)
        (pred_4 obj_01 obj_15)
        (pred_1 obj_19)
    )

    (:goal
        (and (pred_4 obj_01 obj_07) (pred_4 obj_09 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_19 obj_12) (pred_4 obj_19 obj_05))) (not (and (pred_2 obj_19 obj_05) (pred_4 obj_19 obj_12)))))
  )
)

