
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-393022219)
    (:domain delivery)

    (:objects
        obj_07 obj_18 obj_06 obj_12 obj_08 obj_04 obj_11 obj_01 obj_16 obj_10 obj_17 obj_05 obj_13 obj_15 obj_03 obj_14 - type_4
        obj_09 - type_3
        obj_02 - type_1
    )

    (:init
        (pred_1 obj_17 obj_10)
        (pred_1 obj_16 obj_10)
        (pred_1 obj_10 obj_04)
        (pred_1 obj_05 obj_01)
        (pred_1 obj_05 obj_14)
        (pred_1 obj_05 obj_17)
        (pred_1 obj_10 obj_16)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_15 obj_13)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_06 obj_18)
        (pred_1 obj_18 obj_07)
        (pred_1 obj_13 obj_15)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_10 obj_17)
        (pred_1 obj_13 obj_16)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_16 obj_08)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_17 obj_11)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_04 obj_10)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_11 obj_17)
        (pred_1 obj_01 obj_05)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_03 obj_14)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_07 obj_18)
        (pred_1 obj_18 obj_06)
        (pred_1 obj_08 obj_16)
        (pred_1 obj_04 obj_18)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_18 obj_04)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_14 obj_03)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_14 obj_05)
        (pred_1 obj_17 obj_03)
        (pred_1 obj_16 obj_13)
        (pred_1 obj_17 obj_05)
        (pred_4 obj_02 obj_16)
        (pred_4 obj_09 obj_16)
        (pred_2 obj_02)
    )

    (:goal
        (pred_4 obj_09 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_02 obj_08) (pred_4 obj_02 obj_16))) (not (and (pred_3 obj_02 obj_16) (pred_4 obj_02 obj_08)))))
  )
)

