
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-2049801514)
    (:domain delivery)

    (:objects
        obj_01 obj_11 obj_12 obj_04 obj_10 obj_09 obj_06 obj_07 obj_05 - type_4
        obj_08 obj_02 - type_3
        obj_03 - type_2
    )

    (:init
        (pred_2 obj_09 obj_05)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_06 obj_04)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_07 obj_05)
        (pred_2 obj_12 obj_11)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_06 obj_07)
        (pred_2 obj_11 obj_10)
        (pred_2 obj_07 obj_06)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_04 obj_06)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_11 obj_12)
        (pred_2 obj_10 obj_09)
        (pred_2 obj_09 obj_10)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_10 obj_11)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_05 obj_09)
        (pred_3 obj_03 obj_09)
        (pred_3 obj_02 obj_01)
        (pred_3 obj_08 obj_06)
        (pred_4 obj_03)
    )

    (:goal
        (and (pred_3 obj_08 obj_07) (pred_3 obj_02 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_03 obj_11) (pred_3 obj_03 obj_10))) (not (and (pred_1 obj_03 obj_10) (pred_3 obj_03 obj_11)))))
  )
)

