
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-960160946)
    (:domain delivery)

    (:objects
        obj_03 obj_09 obj_06 obj_08 obj_13 obj_14 obj_17 obj_16 obj_10 obj_01 obj_07 obj_05 obj_04 obj_15 obj_18 obj_11 - type_1
        obj_12 - type_2
        obj_02 - type_4
    )

    (:init
        (pred_2 obj_07 obj_01)
        (pred_2 obj_10 obj_01)
        (pred_2 obj_01 obj_14)
        (pred_2 obj_05 obj_16)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_05 obj_07)
        (pred_2 obj_01 obj_10)
        (pred_2 obj_01 obj_15)
        (pred_2 obj_16 obj_17)
        (pred_2 obj_15 obj_18)
        (pred_2 obj_15 obj_04)
        (pred_2 obj_13 obj_03)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_04 obj_15)
        (pred_2 obj_15 obj_01)
        (pred_2 obj_01 obj_07)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_17 obj_06)
        (pred_2 obj_06 obj_17)
        (pred_2 obj_10 obj_13)
        (pred_2 obj_16 obj_08)
        (pred_2 obj_07 obj_17)
        (pred_2 obj_17 obj_14)
        (pred_2 obj_18 obj_15)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_14 obj_01)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_17 obj_07)
        (pred_2 obj_16 obj_05)
        (pred_2 obj_18 obj_07)
        (pred_2 obj_18 obj_11)
        (pred_2 obj_17 obj_16)
        (pred_2 obj_13 obj_14)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_13 obj_10)
        (pred_2 obj_14 obj_09)
        (pred_2 obj_08 obj_16)
        (pred_2 obj_09 obj_14)
        (pred_2 obj_14 obj_13)
        (pred_2 obj_03 obj_13)
        (pred_2 obj_11 obj_18)
        (pred_2 obj_14 obj_17)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_07 obj_18)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_07 obj_05)
        (pred_4 obj_12 obj_14)
        (pred_4 obj_02 obj_13)
        (pred_3 obj_02)
    )

    (:goal
        (pred_4 obj_12 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_02 obj_10) (pred_4 obj_02 obj_04))) (not (and (pred_5 obj_02 obj_04) (pred_4 obj_02 obj_10)))))
  )
)

