
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-628077153)
    (:domain delivery)

    (:objects
        obj_01 obj_07 obj_02 obj_15 obj_16 obj_06 obj_12 obj_11 obj_08 obj_14 obj_04 obj_13 obj_18 obj_03 obj_10 obj_09 - type_3
        obj_05 - type_1
        obj_17 - type_4
    )

    (:init
        (pred_5 obj_04 obj_14)
        (pred_5 obj_08 obj_14)
        (pred_5 obj_14 obj_06)
        (pred_5 obj_13 obj_11)
        (pred_5 obj_13 obj_09)
        (pred_5 obj_13 obj_04)
        (pred_5 obj_14 obj_08)
        (pred_5 obj_14 obj_03)
        (pred_5 obj_11 obj_12)
        (pred_5 obj_03 obj_10)
        (pred_5 obj_03 obj_18)
        (pred_5 obj_16 obj_01)
        (pred_5 obj_02 obj_07)
        (pred_5 obj_07 obj_01)
        (pred_5 obj_18 obj_03)
        (pred_5 obj_03 obj_14)
        (pred_5 obj_14 obj_04)
        (pred_5 obj_18 obj_08)
        (pred_5 obj_12 obj_02)
        (pred_5 obj_02 obj_12)
        (pred_5 obj_08 obj_16)
        (pred_5 obj_11 obj_15)
        (pred_5 obj_04 obj_12)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_10 obj_03)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_06 obj_14)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_12 obj_04)
        (pred_5 obj_11 obj_13)
        (pred_5 obj_10 obj_04)
        (pred_5 obj_10 obj_09)
        (pred_5 obj_12 obj_11)
        (pred_5 obj_16 obj_06)
        (pred_5 obj_01 obj_07)
        (pred_5 obj_07 obj_02)
        (pred_5 obj_16 obj_08)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_15 obj_11)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_06 obj_16)
        (pred_5 obj_01 obj_16)
        (pred_5 obj_09 obj_10)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_09 obj_13)
        (pred_5 obj_04 obj_10)
        (pred_5 obj_08 obj_18)
        (pred_5 obj_04 obj_13)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_17 obj_09)
        (pred_1 obj_17)
    )

    (:goal
        (pred_4 obj_05 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_17 obj_07) (pred_4 obj_17 obj_02))) (not (and (pred_3 obj_17 obj_02) (pred_4 obj_17 obj_07)))))
  )
)

