
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-843321203)
    (:domain delivery)

    (:objects
        obj_11 obj_02 obj_09 obj_03 obj_12 obj_05 obj_07 obj_10 obj_06 - type_2
        obj_01 obj_08 - type_3
        obj_04 - type_4
    )

    (:init
        (pred_1 obj_05 obj_06)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_07 obj_03)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_03 obj_12)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_03 obj_11)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_07 obj_10)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_10 obj_07)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_12 obj_03)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_12 obj_10)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_10 obj_12)
        (pred_1 obj_11 obj_03)
        (pred_1 obj_06 obj_05)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_08 obj_12)
        (pred_5 obj_04 obj_07)
        (pred_4 obj_04)
    )

    (:goal
        (and (pred_5 obj_01 obj_09) (pred_5 obj_08 obj_09))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_04 obj_02) (pred_5 obj_04 obj_12))) (not (and (pred_3 obj_04 obj_12) (pred_5 obj_04 obj_02)))))
  )
)

