
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1496541261)
    (:domain delivery)

    (:objects
        obj_09 obj_17 obj_14 obj_12 obj_06 obj_07 obj_15 obj_13 obj_10 obj_01 obj_02 obj_11 obj_05 obj_08 obj_04 obj_18 - type_3
        obj_16 - type_2
        obj_03 - type_1
    )

    (:init
        (pred_4 obj_02 obj_01)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_01 obj_07)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_11 obj_18)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_01 obj_08)
        (pred_4 obj_13 obj_15)
        (pred_4 obj_08 obj_04)
        (pred_4 obj_08 obj_05)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_17 obj_09)
        (pred_4 obj_05 obj_08)
        (pred_4 obj_08 obj_01)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_05 obj_10)
        (pred_4 obj_15 obj_14)
        (pred_4 obj_14 obj_15)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_13 obj_12)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_15 obj_07)
        (pred_4 obj_04 obj_08)
        (pred_4 obj_12 obj_14)
        (pred_4 obj_07 obj_01)
        (pred_4 obj_14 obj_12)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_04 obj_18)
        (pred_4 obj_15 obj_13)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_09 obj_17)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_07 obj_17)
        (pred_4 obj_12 obj_13)
        (pred_4 obj_17 obj_07)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_18 obj_04)
        (pred_4 obj_07 obj_15)
        (pred_4 obj_18 obj_11)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_10 obj_05)
        (pred_4 obj_02 obj_11)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_16 obj_06)
        (pred_3 obj_03)
    )

    (:goal
        (pred_5 obj_16 obj_13)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_03 obj_15) (pred_5 obj_03 obj_13))) (not (and (pred_2 obj_03 obj_13) (pred_5 obj_03 obj_15)))))
  )
)

