
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-522203805)
    (:domain delivery)

    (:objects
        obj_09 obj_06 obj_02 obj_07 obj_11 obj_08 obj_03 obj_01 obj_04 - type_2
        obj_05 - type_1
        obj_10 - type_4
    )

    (:init
        (pred_3 obj_11 obj_07)
        (pred_3 obj_08 obj_02)
        (pred_3 obj_06 obj_09)
        (pred_3 obj_09 obj_07)
        (pred_3 obj_07 obj_03)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_06 obj_02)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_11 obj_08)
        (pred_3 obj_02 obj_08)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_08 obj_11)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_11 obj_01)
        (pred_3 obj_07 obj_09)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_02 obj_06)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_06 obj_11)
        (pred_3 obj_09 obj_06)
        (pred_1 obj_05 obj_08)
        (pred_1 obj_10 obj_08)
        (pred_5 obj_10)
    )

    (:goal
        (pred_1 obj_05 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_10 obj_07) (pred_1 obj_10 obj_03))) (not (and (pred_4 obj_10 obj_03) (pred_1 obj_10 obj_07)))))
  )
)

