
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1305794666)
    (:domain delivery)

    (:objects
        obj_10 obj_06 obj_01 obj_04 obj_08 obj_02 obj_09 obj_13 obj_03 obj_15 obj_17 obj_14 obj_16 obj_05 obj_18 obj_12 - type_4
        obj_11 - type_3
        obj_07 - type_2
    )

    (:init
        (pred_1 obj_17 obj_15)
        (pred_1 obj_03 obj_15)
        (pred_1 obj_15 obj_02)
        (pred_1 obj_14 obj_13)
        (pred_1 obj_14 obj_12)
        (pred_1 obj_14 obj_17)
        (pred_1 obj_15 obj_03)
        (pred_1 obj_15 obj_05)
        (pred_1 obj_13 obj_09)
        (pred_1 obj_05 obj_18)
        (pred_1 obj_05 obj_16)
        (pred_1 obj_08 obj_10)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_16 obj_05)
        (pred_1 obj_05 obj_15)
        (pred_1 obj_15 obj_17)
        (pred_1 obj_16 obj_03)
        (pred_1 obj_09 obj_01)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_03 obj_08)
        (pred_1 obj_13 obj_04)
        (pred_1 obj_17 obj_09)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_18 obj_05)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_02 obj_15)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_09 obj_17)
        (pred_1 obj_13 obj_14)
        (pred_1 obj_18 obj_17)
        (pred_1 obj_18 obj_12)
        (pred_1 obj_09 obj_13)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_08 obj_03)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_04 obj_13)
        (pred_1 obj_06 obj_02)
        (pred_1 obj_02 obj_08)
        (pred_1 obj_10 obj_08)
        (pred_1 obj_12 obj_18)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_12 obj_14)
        (pred_1 obj_17 obj_18)
        (pred_1 obj_03 obj_16)
        (pred_1 obj_17 obj_14)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_07 obj_08)
        (pred_3 obj_07)
    )

    (:goal
        (pred_5 obj_11 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_07 obj_06) (pred_5 obj_07 obj_02))) (not (and (pred_4 obj_07 obj_02) (pred_5 obj_07 obj_06)))))
  )
)

