
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1929334148)
    (:domain delivery)

    (:objects
        obj_11 obj_16 obj_10 obj_06 obj_01 obj_17 obj_15 obj_18 obj_02 obj_03 obj_14 obj_09 obj_12 obj_07 obj_13 obj_04 - type_1
        obj_19 obj_05 - type_3
        obj_08 - type_2
    )

    (:init
        (pred_1 obj_10 obj_16)
        (pred_1 obj_15 obj_17)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_14 obj_15)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_14 obj_13)
        (pred_1 obj_14 obj_09)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_09 obj_14)
        (pred_1 obj_07 obj_13)
        (pred_1 obj_01 obj_17)
        (pred_1 obj_12 obj_07)
        (pred_1 obj_07 obj_12)
        (pred_1 obj_10 obj_15)
        (pred_1 obj_09 obj_18)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_03 obj_14)
        (pred_1 obj_04 obj_09)
        (pred_1 obj_16 obj_10)
        (pred_1 obj_13 obj_14)
        (pred_1 obj_17 obj_16)
        (pred_1 obj_09 obj_04)
        (pred_1 obj_04 obj_13)
        (pred_1 obj_16 obj_11)
        (pred_1 obj_15 obj_14)
        (pred_1 obj_15 obj_10)
        (pred_1 obj_03 obj_07)
        (pred_1 obj_18 obj_06)
        (pred_1 obj_13 obj_07)
        (pred_1 obj_17 obj_03)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_15 obj_18)
        (pred_1 obj_11 obj_16)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_17 obj_01)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_17 obj_15)
        (pred_1 obj_18 obj_15)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_14 obj_03)
        (pred_1 obj_18 obj_09)
        (pred_1 obj_03 obj_17)
        (pred_1 obj_13 obj_04)
        (pred_1 obj_06 obj_18)
        (pred_1 obj_16 obj_17)
        (pred_1 obj_07 obj_03)
        (pred_5 obj_19 obj_14)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_08 obj_12)
        (pred_2 obj_08)
    )

    (:goal
        (and (pred_5 obj_19 obj_16) (pred_5 obj_05 obj_16))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_08 obj_16) (pred_5 obj_08 obj_10))) (not (and (pred_4 obj_08 obj_10) (pred_5 obj_08 obj_16)))))
  )
)

