
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-53624709)
    (:domain delivery)

    (:objects
        obj_18 obj_07 obj_04 obj_13 obj_14 obj_17 obj_01 obj_12 obj_06 obj_02 obj_11 obj_09 obj_05 obj_19 obj_08 obj_10 - type_2
        obj_16 obj_03 - type_3
        obj_15 - type_1
    )

    (:init
        (pred_2 obj_04 obj_07)
        (pred_2 obj_01 obj_17)
        (pred_2 obj_06 obj_05)
        (pred_2 obj_11 obj_01)
        (pred_2 obj_18 obj_14)
        (pred_2 obj_11 obj_08)
        (pred_2 obj_11 obj_09)
        (pred_2 obj_05 obj_06)
        (pred_2 obj_04 obj_13)
        (pred_2 obj_09 obj_11)
        (pred_2 obj_19 obj_08)
        (pred_2 obj_14 obj_17)
        (pred_2 obj_05 obj_19)
        (pred_2 obj_19 obj_05)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_02 obj_11)
        (pred_2 obj_10 obj_09)
        (pred_2 obj_07 obj_04)
        (pred_2 obj_08 obj_11)
        (pred_2 obj_17 obj_07)
        (pred_2 obj_09 obj_10)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_07 obj_18)
        (pred_2 obj_01 obj_11)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_02 obj_19)
        (pred_2 obj_12 obj_13)
        (pred_2 obj_08 obj_19)
        (pred_2 obj_17 obj_02)
        (pred_2 obj_13 obj_04)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_01 obj_12)
        (pred_2 obj_18 obj_07)
        (pred_2 obj_14 obj_06)
        (pred_2 obj_17 obj_14)
        (pred_2 obj_14 obj_18)
        (pred_2 obj_17 obj_01)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_06 obj_14)
        (pred_2 obj_11 obj_02)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_02 obj_17)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_13 obj_12)
        (pred_2 obj_07 obj_17)
        (pred_2 obj_19 obj_02)
        (pred_4 obj_03 obj_09)
        (pred_4 obj_16 obj_06)
        (pred_4 obj_15 obj_05)
        (pred_3 obj_15)
    )

    (:goal
        (and (pred_4 obj_16 obj_18) (pred_4 obj_03 obj_18))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_15 obj_13) (pred_4 obj_15 obj_12))) (not (and (pred_5 obj_15 obj_12) (pred_4 obj_15 obj_13)))))
  )
)

