
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-254991857)
    (:domain delivery)

    (:objects
        obj_06 obj_03 obj_01 obj_04 - type_1
        obj_05 - type_4
        obj_02 - type_3
    )

    (:init
        (pred_2 obj_06 obj_01)
        (pred_2 obj_04 obj_03)
        (pred_2 obj_01 obj_06)
        (pred_2 obj_06 obj_03)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_03 obj_06)
        (pred_2 obj_03 obj_04)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_05 obj_01)
        (pred_5 obj_02)
    )

    (:goal
        (pred_3 obj_05 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_02 obj_06) (pred_3 obj_02 obj_03))) (not (and (pred_4 obj_02 obj_03) (pred_3 obj_02 obj_06)))))
  )
)

