
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-959338426)
    (:domain delivery)

    (:objects
        obj_17 obj_13 obj_11 obj_15 obj_06 obj_19 obj_04 obj_12 obj_01 obj_03 obj_02 obj_05 obj_14 obj_18 obj_07 obj_08 - type_3
        obj_10 obj_16 - type_2
        obj_09 - type_4
    )

    (:init
        (pred_3 obj_11 obj_13)
        (pred_3 obj_04 obj_19)
        (pred_3 obj_01 obj_14)
        (pred_3 obj_02 obj_04)
        (pred_3 obj_17 obj_06)
        (pred_3 obj_02 obj_07)
        (pred_3 obj_02 obj_05)
        (pred_3 obj_14 obj_01)
        (pred_3 obj_11 obj_15)
        (pred_3 obj_05 obj_02)
        (pred_3 obj_18 obj_07)
        (pred_3 obj_06 obj_19)
        (pred_3 obj_14 obj_18)
        (pred_3 obj_18 obj_14)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_05 obj_12)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_08 obj_05)
        (pred_3 obj_13 obj_11)
        (pred_3 obj_07 obj_02)
        (pred_3 obj_19 obj_13)
        (pred_3 obj_05 obj_08)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_13 obj_17)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_04 obj_11)
        (pred_3 obj_03 obj_18)
        (pred_3 obj_12 obj_15)
        (pred_3 obj_07 obj_18)
        (pred_3 obj_19 obj_03)
        (pred_3 obj_15 obj_11)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_17 obj_13)
        (pred_3 obj_06 obj_01)
        (pred_3 obj_19 obj_06)
        (pred_3 obj_06 obj_17)
        (pred_3 obj_19 obj_04)
        (pred_3 obj_12 obj_04)
        (pred_3 obj_01 obj_06)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_12 obj_05)
        (pred_3 obj_03 obj_19)
        (pred_3 obj_07 obj_08)
        (pred_3 obj_15 obj_12)
        (pred_3 obj_13 obj_19)
        (pred_3 obj_18 obj_03)
        (pred_2 obj_10 obj_19)
        (pred_2 obj_16 obj_06)
        (pred_2 obj_09 obj_19)
        (pred_1 obj_09)
    )

    (:goal
        (and (pred_2 obj_10 obj_12) (pred_2 obj_16 obj_12))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_09 obj_04) (pred_2 obj_09 obj_12))) (not (and (pred_5 obj_09 obj_12) (pred_2 obj_09 obj_04)))))
  )
)

