
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-1185794155)
    (:domain delivery)

    (:objects
        obj_01 obj_04 obj_05 obj_07 - type_1
        obj_03 obj_06 - type_4
        obj_02 - type_2
    )

    (:init
        (pred_3 obj_07 obj_04)
        (pred_3 obj_05 obj_01)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_01 obj_05)
        (pred_2 obj_06 obj_07)
        (pred_2 obj_02 obj_05)
        (pred_2 obj_03 obj_01)
        (pred_5 obj_02)
    )

    (:goal
        (and (pred_2 obj_03 obj_01) (pred_2 obj_06 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_02 obj_04) (pred_2 obj_02 obj_07))) (not (and (pred_1 obj_02 obj_07) (pred_2 obj_02 obj_04)))))
  )
)

