
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-75913986)
    (:domain delivery)

    (:objects
        obj_18 obj_02 obj_16 obj_11 obj_01 obj_08 obj_10 obj_15 obj_14 obj_13 obj_17 obj_07 obj_06 obj_09 obj_04 obj_12 - type_1
        obj_03 - type_2
        obj_05 - type_4
    )

    (:init
        (pred_4 obj_17 obj_13)
        (pred_4 obj_14 obj_13)
        (pred_4 obj_13 obj_08)
        (pred_4 obj_07 obj_15)
        (pred_4 obj_07 obj_12)
        (pred_4 obj_07 obj_17)
        (pred_4 obj_13 obj_14)
        (pred_4 obj_13 obj_09)
        (pred_4 obj_15 obj_10)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_01 obj_18)
        (pred_4 obj_16 obj_02)
        (pred_4 obj_02 obj_18)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_09 obj_13)
        (pred_4 obj_13 obj_17)
        (pred_4 obj_06 obj_14)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_14 obj_01)
        (pred_4 obj_15 obj_11)
        (pred_4 obj_17 obj_10)
        (pred_4 obj_10 obj_08)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_11 obj_16)
        (pred_4 obj_08 obj_13)
        (pred_4 obj_16 obj_11)
        (pred_4 obj_10 obj_17)
        (pred_4 obj_15 obj_07)
        (pred_4 obj_04 obj_17)
        (pred_4 obj_04 obj_12)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_01 obj_08)
        (pred_4 obj_18 obj_02)
        (pred_4 obj_02 obj_16)
        (pred_4 obj_01 obj_14)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_11 obj_15)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_08 obj_01)
        (pred_4 obj_18 obj_01)
        (pred_4 obj_12 obj_04)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_12 obj_07)
        (pred_4 obj_17 obj_04)
        (pred_4 obj_14 obj_06)
        (pred_4 obj_17 obj_07)
        (pred_1 obj_03 obj_18)
        (pred_1 obj_05 obj_15)
        (pred_3 obj_05)
    )

    (:goal
        (pred_1 obj_03 obj_10)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_05 obj_16) (pred_1 obj_05 obj_10))) (not (and (pred_5 obj_05 obj_10) (pred_1 obj_05 obj_16)))))
  )
)

