
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-1416460545)
    (:domain delivery)

    (:objects
        obj_17 obj_04 obj_18 obj_07 obj_11 obj_05 obj_08 obj_10 obj_03 obj_09 obj_06 obj_16 obj_13 obj_12 obj_02 obj_15 - type_4
        obj_14 - type_3
        obj_01 - type_1
    )

    (:init
        (pred_2 obj_06 obj_09)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_09 obj_05)
        (pred_2 obj_16 obj_10)
        (pred_2 obj_16 obj_15)
        (pred_2 obj_16 obj_06)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_09 obj_12)
        (pred_2 obj_10 obj_08)
        (pred_2 obj_12 obj_02)
        (pred_2 obj_12 obj_13)
        (pred_2 obj_11 obj_17)
        (pred_2 obj_18 obj_04)
        (pred_2 obj_04 obj_17)
        (pred_2 obj_13 obj_12)
        (pred_2 obj_12 obj_09)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_13 obj_03)
        (pred_2 obj_08 obj_18)
        (pred_2 obj_18 obj_08)
        (pred_2 obj_03 obj_11)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_08 obj_05)
        (pred_2 obj_02 obj_12)
        (pred_2 obj_07 obj_18)
        (pred_2 obj_05 obj_09)
        (pred_2 obj_18 obj_07)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_10 obj_16)
        (pred_2 obj_02 obj_06)
        (pred_2 obj_02 obj_15)
        (pred_2 obj_08 obj_10)
        (pred_2 obj_11 obj_05)
        (pred_2 obj_17 obj_04)
        (pred_2 obj_04 obj_18)
        (pred_2 obj_11 obj_03)
        (pred_2 obj_05 obj_04)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_04 obj_05)
        (pred_2 obj_05 obj_11)
        (pred_2 obj_17 obj_11)
        (pred_2 obj_15 obj_02)
        (pred_2 obj_05 obj_08)
        (pred_2 obj_15 obj_16)
        (pred_2 obj_06 obj_02)
        (pred_2 obj_03 obj_13)
        (pred_2 obj_06 obj_16)
        (pred_1 obj_14 obj_16)
        (pred_1 obj_01 obj_05)
        (pred_5 obj_01)
    )

    (:goal
        (pred_1 obj_14 obj_02)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_01 obj_06) (pred_1 obj_01 obj_16))) (not (and (pred_4 obj_01 obj_16) (pred_1 obj_01 obj_06)))))
  )
)

