
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-505939808)
    (:domain delivery)

    (:objects
        obj_03 obj_10 obj_02 obj_11 obj_05 obj_09 obj_06 obj_04 obj_08 - type_3
        obj_01 - type_1
        obj_07 - type_2
    )

    (:init
        (pred_1 obj_05 obj_11)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_10 obj_03)
        (pred_1 obj_03 obj_11)
        (pred_1 obj_11 obj_06)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_04 obj_08)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_05 obj_09)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_11 obj_05)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_09 obj_05)
        (pred_1 obj_08 obj_04)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_11 obj_03)
        (pred_1 obj_06 obj_11)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_03 obj_10)
        (pred_5 obj_07 obj_11)
        (pred_5 obj_01 obj_08)
        (pred_2 obj_07)
    )

    (:goal
        (pred_5 obj_01 obj_03)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_07 obj_10) (pred_5 obj_07 obj_02))) (not (and (pred_4 obj_07 obj_02) (pred_5 obj_07 obj_10)))))
  )
)

