
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-641714816)
    (:domain delivery)

    (:objects
        obj_02 obj_14 obj_09 obj_08 obj_16 obj_11 obj_04 obj_06 obj_07 obj_12 obj_17 obj_10 obj_05 obj_15 obj_13 obj_19 - type_4
        obj_18 obj_01 - type_2
        obj_03 - type_1
    )

    (:init
        (pred_3 obj_09 obj_14)
        (pred_3 obj_04 obj_11)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_17 obj_04)
        (pred_3 obj_02 obj_16)
        (pred_3 obj_17 obj_13)
        (pred_3 obj_17 obj_10)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_10 obj_17)
        (pred_3 obj_15 obj_13)
        (pred_3 obj_16 obj_11)
        (pred_3 obj_05 obj_15)
        (pred_3 obj_15 obj_05)
        (pred_3 obj_09 obj_04)
        (pred_3 obj_10 obj_06)
        (pred_3 obj_12 obj_07)
        (pred_3 obj_12 obj_17)
        (pred_3 obj_19 obj_10)
        (pred_3 obj_14 obj_09)
        (pred_3 obj_13 obj_17)
        (pred_3 obj_11 obj_14)
        (pred_3 obj_10 obj_19)
        (pred_3 obj_19 obj_13)
        (pred_3 obj_14 obj_02)
        (pred_3 obj_04 obj_17)
        (pred_3 obj_04 obj_09)
        (pred_3 obj_12 obj_15)
        (pred_3 obj_06 obj_08)
        (pred_3 obj_13 obj_15)
        (pred_3 obj_11 obj_12)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_07 obj_12)
        (pred_3 obj_04 obj_06)
        (pred_3 obj_02 obj_14)
        (pred_3 obj_16 obj_07)
        (pred_3 obj_11 obj_16)
        (pred_3 obj_16 obj_02)
        (pred_3 obj_11 obj_04)
        (pred_3 obj_06 obj_04)
        (pred_3 obj_07 obj_16)
        (pred_3 obj_17 obj_12)
        (pred_3 obj_06 obj_10)
        (pred_3 obj_12 obj_11)
        (pred_3 obj_13 obj_19)
        (pred_3 obj_08 obj_06)
        (pred_3 obj_14 obj_11)
        (pred_3 obj_15 obj_12)
        (pred_4 obj_01 obj_13)
        (pred_4 obj_18 obj_02)
        (pred_4 obj_03 obj_10)
        (pred_2 obj_03)
    )

    (:goal
        (and (pred_4 obj_18 obj_06) (pred_4 obj_01 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_03 obj_08) (pred_4 obj_03 obj_06))) (not (and (pred_5 obj_03 obj_06) (pred_4 obj_03 obj_08)))))
  )
)

