
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-311279601)
    (:domain delivery)

    (:objects
        obj_04 obj_01 obj_11 obj_03 obj_07 obj_05 obj_02 obj_06 obj_08 - type_4
        obj_10 - type_3
        obj_09 - type_2
    )

    (:init
        (pred_3 obj_07 obj_03)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_01 obj_04)
        (pred_3 obj_04 obj_03)
        (pred_3 obj_03 obj_02)
        (pred_3 obj_06 obj_02)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_06 obj_08)
        (pred_3 obj_08 obj_05)
        (pred_3 obj_07 obj_05)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_06 obj_07)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_05 obj_08)
        (pred_3 obj_02 obj_06)
        (pred_3 obj_05 obj_07)
        (pred_3 obj_08 obj_06)
        (pred_3 obj_07 obj_06)
        (pred_3 obj_03 obj_04)
        (pred_3 obj_02 obj_03)
        (pred_3 obj_11 obj_01)
        (pred_3 obj_07 obj_01)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_04 obj_01)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_10 obj_01)
        (pred_5 obj_09)
    )

    (:goal
        (pred_2 obj_10 obj_08)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_09 obj_05) (pred_2 obj_09 obj_08))) (not (and (pred_1 obj_09 obj_08) (pred_2 obj_09 obj_05)))))
  )
)

