
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-866638198)
    (:domain delivery)

    (:objects
        obj_09 obj_08 obj_02 obj_06 obj_10 obj_05 obj_03 obj_01 obj_11 - type_2
        obj_04 obj_07 - type_3
        obj_12 - type_1
    )

    (:init
        (pred_4 obj_05 obj_11)
        (pred_4 obj_11 obj_01)
        (pred_4 obj_03 obj_06)
        (pred_4 obj_02 obj_05)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_05 obj_02)
        (pred_4 obj_01 obj_11)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_09 obj_08)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_08 obj_10)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_08 obj_09)
        (pred_4 obj_06 obj_03)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_10 obj_05)
        (pred_4 obj_05 obj_10)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_10 obj_08)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_11 obj_05)
        (pred_2 obj_12 obj_01)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_04 obj_08)
        (pred_5 obj_12)
    )

    (:goal
        (and (pred_2 obj_04 obj_09) (pred_2 obj_07 obj_09))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_12 obj_06) (pred_2 obj_12 obj_03))) (not (and (pred_1 obj_12 obj_03) (pred_2 obj_12 obj_06)))))
  )
)

