
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-228132619)
    (:domain delivery)

    (:objects
        obj_01 obj_03 obj_12 obj_02 obj_08 obj_13 obj_18 obj_07 obj_16 obj_11 obj_17 obj_05 obj_10 obj_15 obj_14 obj_04 - type_2
        obj_06 - type_4
        obj_09 - type_3
    )

    (:init
        (pred_4 obj_17 obj_11)
        (pred_4 obj_16 obj_11)
        (pred_4 obj_11 obj_13)
        (pred_4 obj_05 obj_07)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_05 obj_17)
        (pred_4 obj_11 obj_16)
        (pred_4 obj_11 obj_15)
        (pred_4 obj_07 obj_18)
        (pred_4 obj_15 obj_14)
        (pred_4 obj_15 obj_10)
        (pred_4 obj_08 obj_01)
        (pred_4 obj_12 obj_03)
        (pred_4 obj_03 obj_01)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_15 obj_11)
        (pred_4 obj_11 obj_17)
        (pred_4 obj_10 obj_16)
        (pred_4 obj_18 obj_12)
        (pred_4 obj_12 obj_18)
        (pred_4 obj_16 obj_08)
        (pred_4 obj_07 obj_02)
        (pred_4 obj_17 obj_18)
        (pred_4 obj_18 obj_13)
        (pred_4 obj_14 obj_15)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_13 obj_11)
        (pred_4 obj_12 obj_02)
        (pred_4 obj_18 obj_17)
        (pred_4 obj_07 obj_05)
        (pred_4 obj_14 obj_17)
        (pred_4 obj_14 obj_04)
        (pred_4 obj_18 obj_07)
        (pred_4 obj_08 obj_13)
        (pred_4 obj_01 obj_03)
        (pred_4 obj_03 obj_12)
        (pred_4 obj_08 obj_16)
        (pred_4 obj_13 obj_03)
        (pred_4 obj_02 obj_07)
        (pred_4 obj_03 obj_13)
        (pred_4 obj_13 obj_08)
        (pred_4 obj_01 obj_08)
        (pred_4 obj_04 obj_14)
        (pred_4 obj_13 obj_18)
        (pred_4 obj_04 obj_05)
        (pred_4 obj_17 obj_14)
        (pred_4 obj_16 obj_10)
        (pred_4 obj_17 obj_05)
        (pred_2 obj_06 obj_12)
        (pred_2 obj_09 obj_15)
        (pred_5 obj_09)
    )

    (:goal
        (pred_2 obj_06 obj_01)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_09 obj_01) (pred_2 obj_09 obj_03))) (not (and (pred_1 obj_09 obj_03) (pred_2 obj_09 obj_01)))))
  )
)

