
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-1-1247747029)
    (:domain delivery)

    (:objects
        obj_03 obj_01 obj_04 obj_02 - type_3
        obj_05 - type_2
        obj_06 - type_4
    )

    (:init
        (pred_1 obj_03 obj_04)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_04 obj_03)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_04 obj_02)
        (pred_1 obj_02 obj_04)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_01 obj_02)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_05 obj_01)
        (pred_3 obj_06)
    )

    (:goal
        (pred_4 obj_05 obj_04)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_06 obj_03) (pred_4 obj_06 obj_01))) (not (and (pred_5 obj_06 obj_01) (pred_4 obj_06 obj_03)))))
  )
)

