
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1112759645)
    (:domain delivery)

    (:objects
        obj_05 obj_11 obj_08 obj_12 obj_06 obj_07 obj_09 obj_04 obj_02 - type_4
        obj_03 obj_10 - type_2
        obj_01 - type_1
    )

    (:init
        (pred_4 obj_07 obj_02)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_09 obj_12)
        (pred_4 obj_08 obj_07)
        (pred_4 obj_12 obj_06)
        (pred_4 obj_07 obj_08)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_08 obj_11)
        (pred_4 obj_12 obj_05)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_09 obj_04)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_04 obj_09)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_12 obj_09)
        (pred_4 obj_06 obj_12)
        (pred_4 obj_11 obj_08)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_06 obj_04)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_04 obj_06)
        (pred_4 obj_05 obj_12)
        (pred_4 obj_02 obj_07)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_10 obj_02)
        (pred_1 obj_01)
    )

    (:goal
        (and (pred_3 obj_03 obj_11) (pred_3 obj_10 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_01 obj_11) (pred_3 obj_01 obj_08))) (not (and (pred_5 obj_01 obj_08) (pred_3 obj_01 obj_11)))))
  )
)

