
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-2039810421)
    (:domain delivery)

    (:objects
        obj_11 obj_02 obj_01 obj_04 obj_12 obj_10 obj_07 obj_06 obj_09 - type_4
        obj_08 obj_05 - type_2
        obj_03 - type_1
    )

    (:init
        (pred_4 obj_10 obj_09)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_04 obj_12)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_04 obj_11)
        (pred_4 obj_11 obj_02)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_02 obj_12)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_02 obj_11)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_12 obj_04)
        (pred_4 obj_02 obj_01)
        (pred_4 obj_12 obj_10)
        (pred_4 obj_10 obj_12)
        (pred_4 obj_12 obj_06)
        (pred_4 obj_12 obj_02)
        (pred_4 obj_06 obj_12)
        (pred_4 obj_11 obj_04)
        (pred_4 obj_09 obj_10)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_08 obj_02)
        (pred_1 obj_03 obj_10)
        (pred_5 obj_03)
    )

    (:goal
        (and (pred_1 obj_08 obj_01) (pred_1 obj_05 obj_01))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_11) (pred_1 obj_03 obj_02))) (not (and (pred_3 obj_03 obj_02) (pred_1 obj_03 obj_11)))))
  )
)

