
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-716675527)
    (:domain delivery)

    (:objects
        obj_02 obj_07 obj_01 obj_03 - type_3
        obj_06 obj_05 - type_4
        obj_04 - type_2
    )

    (:init
        (pred_2 obj_03 obj_07)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_07 obj_03)
        (pred_2 obj_02 obj_01)
        (pred_3 obj_04 obj_02)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_06 obj_02)
        (pred_4 obj_04)
    )

    (:goal
        (and (pred_3 obj_06 obj_03) (pred_3 obj_05 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_04 obj_07) (pred_3 obj_04 obj_03))) (not (and (pred_5 obj_04 obj_03) (pred_3 obj_04 obj_07)))))
  )
)

