
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-236829038)
    (:domain delivery)

    (:objects
        obj_09 obj_01 obj_10 obj_07 obj_04 obj_11 obj_02 obj_05 obj_08 - type_4
        obj_06 - type_3
        obj_03 - type_1
    )

    (:init
        (pred_1 obj_04 obj_07)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_09 obj_07)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_05 obj_02)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_05 obj_08)
        (pred_1 obj_08 obj_11)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_05 obj_04)
        (pred_1 obj_07 obj_04)
        (pred_1 obj_11 obj_08)
        (pred_1 obj_02 obj_05)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_08 obj_05)
        (pred_1 obj_04 obj_05)
        (pred_1 obj_07 obj_09)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_04 obj_01)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_09 obj_01)
        (pred_3 obj_03 obj_10)
        (pred_3 obj_06 obj_08)
        (pred_5 obj_03)
    )

    (:goal
        (pred_3 obj_06 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_03 obj_07) (pred_3 obj_03 obj_04))) (not (and (pred_2 obj_03 obj_04) (pred_3 obj_03 obj_07)))))
  )
)

