
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-712768135)
    (:domain delivery)

    (:objects
        obj_01 obj_03 obj_08 obj_10 obj_02 obj_09 obj_11 obj_12 obj_05 - type_4
        obj_04 obj_06 - type_1
        obj_07 - type_2
    )

    (:init
        (pred_1 obj_09 obj_05)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_08 obj_03)
        (pred_1 obj_10 obj_01)
        (pred_1 obj_01 obj_03)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_03 obj_02)
        (pred_1 obj_12 obj_11)
        (pred_1 obj_03 obj_01)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_03 obj_08)
        (pred_1 obj_02 obj_09)
        (pred_1 obj_09 obj_02)
        (pred_1 obj_02 obj_12)
        (pred_1 obj_02 obj_03)
        (pred_1 obj_12 obj_02)
        (pred_1 obj_01 obj_10)
        (pred_1 obj_05 obj_09)
        (pred_3 obj_04 obj_12)
        (pred_3 obj_06 obj_03)
        (pred_3 obj_07 obj_09)
        (pred_4 obj_07)
    )

    (:goal
        (and (pred_3 obj_04 obj_05) (pred_3 obj_06 obj_05))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_07 obj_08) (pred_3 obj_07 obj_09))) (not (and (pred_2 obj_07 obj_09) (pred_3 obj_07 obj_08)))))
  )
)

