
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-491527346)
    (:domain delivery)

    (:objects
        obj_03 obj_16 obj_17 obj_07 obj_10 obj_14 obj_12 obj_09 obj_13 obj_15 obj_08 obj_19 obj_06 obj_11 obj_05 obj_04 - type_4
        obj_01 obj_18 - type_1
        obj_02 - type_3
    )

    (:init
        (pred_4 obj_17 obj_16)
        (pred_4 obj_12 obj_14)
        (pred_4 obj_13 obj_06)
        (pred_4 obj_08 obj_12)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_08 obj_05)
        (pred_4 obj_08 obj_19)
        (pred_4 obj_06 obj_13)
        (pred_4 obj_17 obj_07)
        (pred_4 obj_19 obj_08)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_10 obj_14)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_17 obj_12)
        (pred_4 obj_19 obj_09)
        (pred_4 obj_15 obj_13)
        (pred_4 obj_15 obj_08)
        (pred_4 obj_04 obj_19)
        (pred_4 obj_16 obj_17)
        (pred_4 obj_05 obj_08)
        (pred_4 obj_14 obj_16)
        (pred_4 obj_19 obj_04)
        (pred_4 obj_04 obj_05)
        (pred_4 obj_16 obj_03)
        (pred_4 obj_12 obj_08)
        (pred_4 obj_12 obj_17)
        (pred_4 obj_15 obj_11)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_14 obj_15)
        (pred_4 obj_07 obj_17)
        (pred_4 obj_13 obj_15)
        (pred_4 obj_12 obj_09)
        (pred_4 obj_03 obj_16)
        (pred_4 obj_10 obj_13)
        (pred_4 obj_14 obj_10)
        (pred_4 obj_10 obj_03)
        (pred_4 obj_14 obj_12)
        (pred_4 obj_09 obj_12)
        (pred_4 obj_13 obj_10)
        (pred_4 obj_08 obj_15)
        (pred_4 obj_09 obj_19)
        (pred_4 obj_15 obj_14)
        (pred_4 obj_05 obj_04)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_16 obj_14)
        (pred_4 obj_11 obj_15)
        (pred_3 obj_02 obj_15)
        (pred_3 obj_18 obj_07)
        (pred_3 obj_01 obj_05)
        (pred_2 obj_02)
    )

    (:goal
        (and (pred_3 obj_01 obj_11) (pred_3 obj_18 obj_11))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_02 obj_16) (pred_3 obj_02 obj_14))) (not (and (pred_5 obj_02 obj_14) (pred_3 obj_02 obj_16)))))
  )
)

