
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1019662785)
    (:domain delivery)

    (:objects
        obj_10 obj_07 obj_09 obj_12 obj_02 obj_08 obj_04 obj_01 obj_03 - type_4
        obj_11 obj_06 - type_2
        obj_05 - type_3
    )

    (:init
        (pred_2 obj_08 obj_03)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_04 obj_12)
        (pred_2 obj_09 obj_08)
        (pred_2 obj_12 obj_02)
        (pred_2 obj_08 obj_09)
        (pred_2 obj_01 obj_03)
        (pred_2 obj_09 obj_07)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_10 obj_07)
        (pred_2 obj_04 obj_01)
        (pred_2 obj_07 obj_02)
        (pred_2 obj_01 obj_04)
        (pred_2 obj_07 obj_10)
        (pred_2 obj_12 obj_04)
        (pred_2 obj_02 obj_12)
        (pred_2 obj_07 obj_09)
        (pred_2 obj_02 obj_08)
        (pred_2 obj_08 obj_02)
        (pred_2 obj_02 obj_01)
        (pred_2 obj_02 obj_07)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_03 obj_08)
        (pred_1 obj_05 obj_01)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_06 obj_02)
        (pred_4 obj_05)
    )

    (:goal
        (and (pred_1 obj_11 obj_03) (pred_1 obj_06 obj_03))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_5 obj_05 obj_08) (pred_1 obj_05 obj_03))) (not (and (pred_5 obj_05 obj_03) (pred_1 obj_05 obj_08)))))
  )
)

