
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-521589505)
    (:domain delivery)

    (:objects
        obj_13 obj_10 obj_18 obj_06 obj_12 obj_05 obj_11 obj_02 obj_01 obj_03 obj_07 obj_09 obj_15 obj_08 obj_04 obj_14 - type_2
        obj_16 - type_4
        obj_17 - type_3
    )

    (:init
        (pred_3 obj_07 obj_03)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_09 obj_02)
        (pred_3 obj_09 obj_14)
        (pred_3 obj_09 obj_07)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_02 obj_11)
        (pred_3 obj_08 obj_04)
        (pred_3 obj_08 obj_15)
        (pred_3 obj_12 obj_13)
        (pred_3 obj_18 obj_10)
        (pred_3 obj_10 obj_13)
        (pred_3 obj_15 obj_08)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_03 obj_07)
        (pred_3 obj_15 obj_01)
        (pred_3 obj_11 obj_18)
        (pred_3 obj_18 obj_11)
        (pred_3 obj_01 obj_12)
        (pred_3 obj_02 obj_06)
        (pred_3 obj_07 obj_11)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_04 obj_08)
        (pred_3 obj_06 obj_18)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_18 obj_06)
        (pred_3 obj_11 obj_07)
        (pred_3 obj_02 obj_09)
        (pred_3 obj_04 obj_07)
        (pred_3 obj_04 obj_14)
        (pred_3 obj_11 obj_02)
        (pred_3 obj_12 obj_05)
        (pred_3 obj_13 obj_10)
        (pred_3 obj_10 obj_18)
        (pred_3 obj_12 obj_01)
        (pred_3 obj_05 obj_10)
        (pred_3 obj_06 obj_02)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_05 obj_12)
        (pred_3 obj_13 obj_12)
        (pred_3 obj_14 obj_04)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_14 obj_09)
        (pred_3 obj_07 obj_04)
        (pred_3 obj_01 obj_15)
        (pred_3 obj_07 obj_09)
        (pred_5 obj_17 obj_15)
        (pred_5 obj_16 obj_06)
        (pred_2 obj_17)
    )

    (:goal
        (pred_5 obj_16 obj_11)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_17 obj_18) (pred_5 obj_17 obj_06))) (not (and (pred_1 obj_17 obj_06) (pred_5 obj_17 obj_18)))))
  )
)

