
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-210100326)
    (:domain delivery)

    (:objects
        obj_01 obj_06 obj_02 obj_09 obj_05 obj_08 obj_03 obj_12 obj_11 - type_1
        obj_04 obj_10 - type_3
        obj_07 - type_4
    )

    (:init
        (pred_5 obj_08 obj_11)
        (pred_5 obj_11 obj_12)
        (pred_5 obj_03 obj_09)
        (pred_5 obj_02 obj_08)
        (pred_5 obj_09 obj_05)
        (pred_5 obj_08 obj_02)
        (pred_5 obj_12 obj_11)
        (pred_5 obj_02 obj_06)
        (pred_5 obj_09 obj_01)
        (pred_5 obj_01 obj_06)
        (pred_5 obj_03 obj_12)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_12 obj_03)
        (pred_5 obj_06 obj_01)
        (pred_5 obj_09 obj_03)
        (pred_5 obj_05 obj_09)
        (pred_5 obj_06 obj_02)
        (pred_5 obj_05 obj_08)
        (pred_5 obj_08 obj_05)
        (pred_5 obj_05 obj_12)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_12 obj_05)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_11 obj_08)
        (pred_3 obj_10 obj_08)
        (pred_3 obj_04 obj_01)
        (pred_3 obj_07 obj_01)
        (pred_4 obj_07)
    )

    (:goal
        (and (pred_3 obj_04 obj_06) (pred_3 obj_10 obj_06))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_07 obj_02) (pred_3 obj_07 obj_08))) (not (and (pred_2 obj_07 obj_08) (pred_3 obj_07 obj_02)))))
  )
)

