
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-920286616)
    (:domain delivery)

    (:objects
        obj_12 obj_16 obj_05 obj_15 obj_06 obj_13 obj_10 obj_02 obj_09 obj_01 obj_19 obj_03 obj_11 obj_18 obj_07 obj_04 - type_1
        obj_14 obj_08 - type_4
        obj_17 - type_2
    )

    (:init
        (pred_5 obj_05 obj_16)
        (pred_5 obj_10 obj_13)
        (pred_5 obj_09 obj_11)
        (pred_5 obj_19 obj_10)
        (pred_5 obj_12 obj_06)
        (pred_5 obj_19 obj_07)
        (pred_5 obj_19 obj_03)
        (pred_5 obj_11 obj_09)
        (pred_5 obj_05 obj_15)
        (pred_5 obj_03 obj_19)
        (pred_5 obj_18 obj_07)
        (pred_5 obj_06 obj_13)
        (pred_5 obj_11 obj_18)
        (pred_5 obj_18 obj_11)
        (pred_5 obj_05 obj_10)
        (pred_5 obj_03 obj_02)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_01 obj_19)
        (pred_5 obj_04 obj_03)
        (pred_5 obj_16 obj_05)
        (pred_5 obj_07 obj_19)
        (pred_5 obj_13 obj_16)
        (pred_5 obj_03 obj_04)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_16 obj_12)
        (pred_5 obj_10 obj_19)
        (pred_5 obj_10 obj_05)
        (pred_5 obj_01 obj_18)
        (pred_5 obj_02 obj_15)
        (pred_5 obj_07 obj_18)
        (pred_5 obj_13 obj_01)
        (pred_5 obj_15 obj_05)
        (pred_5 obj_09 obj_01)
        (pred_5 obj_10 obj_02)
        (pred_5 obj_12 obj_16)
        (pred_5 obj_06 obj_09)
        (pred_5 obj_13 obj_06)
        (pred_5 obj_06 obj_12)
        (pred_5 obj_13 obj_10)
        (pred_5 obj_02 obj_10)
        (pred_5 obj_09 obj_06)
        (pred_5 obj_19 obj_01)
        (pred_5 obj_02 obj_03)
        (pred_5 obj_01 obj_13)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_15 obj_02)
        (pred_5 obj_16 obj_13)
        (pred_5 obj_18 obj_01)
        (pred_4 obj_14 obj_11)
        (pred_4 obj_08 obj_11)
        (pred_4 obj_17 obj_06)
        (pred_1 obj_17)
    )

    (:goal
        (and (pred_4 obj_14 obj_02) (pred_4 obj_08 obj_02))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_17 obj_09) (pred_4 obj_17 obj_11))) (not (and (pred_2 obj_17 obj_11) (pred_4 obj_17 obj_09)))))
  )
)

