
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-703750698)
    (:domain delivery)

    (:objects
        obj_09 obj_06 obj_17 obj_05 obj_03 obj_08 obj_01 obj_14 obj_11 obj_15 obj_02 obj_18 obj_12 obj_10 obj_04 obj_13 - type_1
        obj_16 - type_4
        obj_07 - type_3
    )

    (:init
        (pred_2 obj_02 obj_15)
        (pred_2 obj_11 obj_15)
        (pred_2 obj_15 obj_08)
        (pred_2 obj_18 obj_14)
        (pred_2 obj_18 obj_13)
        (pred_2 obj_18 obj_02)
        (pred_2 obj_15 obj_11)
        (pred_2 obj_15 obj_10)
        (pred_2 obj_14 obj_01)
        (pred_2 obj_10 obj_04)
        (pred_2 obj_10 obj_12)
        (pred_2 obj_03 obj_09)
        (pred_2 obj_17 obj_06)
        (pred_2 obj_06 obj_09)
        (pred_2 obj_12 obj_10)
        (pred_2 obj_10 obj_15)
        (pred_2 obj_15 obj_02)
        (pred_2 obj_12 obj_11)
        (pred_2 obj_01 obj_17)
        (pred_2 obj_17 obj_01)
        (pred_2 obj_11 obj_03)
        (pred_2 obj_14 obj_05)
        (pred_2 obj_02 obj_01)
        (pred_2 obj_01 obj_08)
        (pred_2 obj_04 obj_10)
        (pred_2 obj_05 obj_17)
        (pred_2 obj_08 obj_15)
        (pred_2 obj_17 obj_05)
        (pred_2 obj_01 obj_02)
        (pred_2 obj_14 obj_18)
        (pred_2 obj_04 obj_02)
        (pred_2 obj_04 obj_13)
        (pred_2 obj_01 obj_14)
        (pred_2 obj_03 obj_08)
        (pred_2 obj_09 obj_06)
        (pred_2 obj_06 obj_17)
        (pred_2 obj_03 obj_11)
        (pred_2 obj_08 obj_06)
        (pred_2 obj_05 obj_14)
        (pred_2 obj_06 obj_08)
        (pred_2 obj_08 obj_03)
        (pred_2 obj_09 obj_03)
        (pred_2 obj_13 obj_04)
        (pred_2 obj_08 obj_01)
        (pred_2 obj_13 obj_18)
        (pred_2 obj_02 obj_04)
        (pred_2 obj_11 obj_12)
        (pred_2 obj_02 obj_18)
        (pred_4 obj_16 obj_06)
        (pred_4 obj_07 obj_18)
        (pred_5 obj_07)
    )

    (:goal
        (pred_4 obj_16 obj_10)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_07 obj_06) (pred_4 obj_07 obj_08))) (not (and (pred_3 obj_07 obj_08) (pred_4 obj_07 obj_06)))))
  )
)

