
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-2063632518)
    (:domain delivery)

    (:objects
        obj_08 obj_09 obj_06 obj_07 obj_11 obj_01 obj_05 obj_10 obj_02 - type_3
        obj_04 - type_4
        obj_03 - type_1
    )

    (:init
        (pred_1 obj_11 obj_07)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_08 obj_07)
        (pred_1 obj_07 obj_05)
        (pred_1 obj_10 obj_05)
        (pred_1 obj_09 obj_06)
        (pred_1 obj_10 obj_02)
        (pred_1 obj_02 obj_01)
        (pred_1 obj_11 obj_01)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_10 obj_11)
        (pred_1 obj_07 obj_11)
        (pred_1 obj_01 obj_02)
        (pred_1 obj_05 obj_10)
        (pred_1 obj_01 obj_11)
        (pred_1 obj_02 obj_10)
        (pred_1 obj_11 obj_10)
        (pred_1 obj_07 obj_08)
        (pred_1 obj_05 obj_07)
        (pred_1 obj_06 obj_09)
        (pred_1 obj_11 obj_09)
        (pred_1 obj_09 obj_11)
        (pred_1 obj_08 obj_09)
        (pred_4 obj_04 obj_07)
        (pred_4 obj_03 obj_08)
        (pred_5 obj_03)
    )

    (:goal
        (pred_4 obj_04 obj_06)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_3 obj_03 obj_08) (pred_4 obj_03 obj_09))) (not (and (pred_3 obj_03 obj_09) (pred_4 obj_03 obj_08)))))
  )
)

