
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-2x2-2-539958480)
    (:domain delivery)

    (:objects
        obj_06 obj_07 obj_02 obj_04 - type_3
        obj_05 obj_01 - type_2
        obj_03 - type_4
    )

    (:init
        (pred_4 obj_04 obj_07)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_02 obj_04)
        (pred_4 obj_04 obj_02)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_07 obj_04)
        (pred_4 obj_06 obj_02)
        (pred_3 obj_01 obj_02)
        (pred_3 obj_05 obj_02)
        (pred_3 obj_03 obj_07)
        (pred_2 obj_03)
    )

    (:goal
        (and (pred_3 obj_05 obj_07) (pred_3 obj_01 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_03 obj_06) (pred_3 obj_03 obj_07))) (not (and (pred_1 obj_03 obj_07) (pred_3 obj_03 obj_06)))))
  )
)

