
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-1749012638)
    (:domain delivery)

    (:objects
        obj_10 obj_09 obj_03 obj_04 obj_12 obj_05 obj_06 obj_01 obj_07 - type_3
        obj_11 obj_08 - type_1
        obj_02 - type_2
    )

    (:init
        (pred_1 obj_05 obj_07)
        (pred_1 obj_07 obj_01)
        (pred_1 obj_06 obj_04)
        (pred_1 obj_03 obj_05)
        (pred_1 obj_04 obj_12)
        (pred_1 obj_05 obj_03)
        (pred_1 obj_01 obj_07)
        (pred_1 obj_03 obj_09)
        (pred_1 obj_04 obj_10)
        (pred_1 obj_10 obj_09)
        (pred_1 obj_06 obj_01)
        (pred_1 obj_09 obj_12)
        (pred_1 obj_01 obj_06)
        (pred_1 obj_09 obj_10)
        (pred_1 obj_04 obj_06)
        (pred_1 obj_12 obj_04)
        (pred_1 obj_09 obj_03)
        (pred_1 obj_12 obj_05)
        (pred_1 obj_05 obj_12)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_12 obj_09)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_10 obj_04)
        (pred_1 obj_07 obj_05)
        (pred_3 obj_08 obj_10)
        (pred_3 obj_11 obj_06)
        (pred_3 obj_02 obj_06)
        (pred_2 obj_02)
    )

    (:goal
        (and (pred_3 obj_11 obj_10) (pred_3 obj_08 obj_10))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_02 obj_04) (pred_3 obj_02 obj_06))) (not (and (pred_4 obj_02 obj_06) (pred_3 obj_02 obj_04)))))
  )
)

