
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-1661753483)
    (:domain delivery)

    (:objects
        obj_05 obj_09 obj_11 obj_03 obj_06 obj_07 obj_12 obj_16 obj_10 obj_01 obj_17 obj_13 obj_15 obj_02 obj_19 obj_18 - type_3
        obj_14 obj_08 - type_4
        obj_04 - type_2
    )

    (:init
        (pred_4 obj_11 obj_09)
        (pred_4 obj_12 obj_07)
        (pred_4 obj_10 obj_15)
        (pred_4 obj_17 obj_12)
        (pred_4 obj_05 obj_06)
        (pred_4 obj_17 obj_19)
        (pred_4 obj_17 obj_13)
        (pred_4 obj_15 obj_10)
        (pred_4 obj_11 obj_03)
        (pred_4 obj_13 obj_17)
        (pred_4 obj_02 obj_19)
        (pred_4 obj_06 obj_07)
        (pred_4 obj_15 obj_02)
        (pred_4 obj_02 obj_15)
        (pred_4 obj_11 obj_12)
        (pred_4 obj_13 obj_16)
        (pred_4 obj_01 obj_10)
        (pred_4 obj_01 obj_17)
        (pred_4 obj_18 obj_13)
        (pred_4 obj_09 obj_11)
        (pred_4 obj_19 obj_17)
        (pred_4 obj_07 obj_09)
        (pred_4 obj_13 obj_18)
        (pred_4 obj_18 obj_19)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_12 obj_17)
        (pred_4 obj_12 obj_11)
        (pred_4 obj_01 obj_02)
        (pred_4 obj_16 obj_03)
        (pred_4 obj_19 obj_02)
        (pred_4 obj_07 obj_01)
        (pred_4 obj_03 obj_11)
        (pred_4 obj_10 obj_01)
        (pred_4 obj_12 obj_16)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_06 obj_10)
        (pred_4 obj_07 obj_06)
        (pred_4 obj_06 obj_05)
        (pred_4 obj_07 obj_12)
        (pred_4 obj_16 obj_12)
        (pred_4 obj_10 obj_06)
        (pred_4 obj_17 obj_01)
        (pred_4 obj_16 obj_13)
        (pred_4 obj_01 obj_07)
        (pred_4 obj_19 obj_18)
        (pred_4 obj_03 obj_16)
        (pred_4 obj_09 obj_07)
        (pred_4 obj_02 obj_01)
        (pred_5 obj_08 obj_19)
        (pred_5 obj_14 obj_15)
        (pred_5 obj_04 obj_15)
        (pred_1 obj_04)
    )

    (:goal
        (and (pred_5 obj_14 obj_05) (pred_5 obj_08 obj_05))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_04 obj_11) (pred_5 obj_04 obj_12))) (not (and (pred_2 obj_04 obj_12) (pred_5 obj_04 obj_11)))))
  )
)

