
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-2-2002982503)
    (:domain delivery)

    (:objects
        obj_08 obj_09 obj_05 obj_02 obj_06 obj_11 obj_10 obj_03 obj_07 - type_4
        obj_12 obj_04 - type_1
        obj_01 - type_3
    )

    (:init
        (pred_4 obj_11 obj_07)
        (pred_4 obj_07 obj_03)
        (pred_4 obj_10 obj_02)
        (pred_4 obj_05 obj_11)
        (pred_4 obj_02 obj_06)
        (pred_4 obj_11 obj_05)
        (pred_4 obj_03 obj_07)
        (pred_4 obj_05 obj_09)
        (pred_4 obj_02 obj_08)
        (pred_4 obj_08 obj_09)
        (pred_4 obj_10 obj_03)
        (pred_4 obj_09 obj_06)
        (pred_4 obj_03 obj_10)
        (pred_4 obj_09 obj_08)
        (pred_4 obj_02 obj_10)
        (pred_4 obj_06 obj_02)
        (pred_4 obj_09 obj_05)
        (pred_4 obj_06 obj_11)
        (pred_4 obj_11 obj_06)
        (pred_4 obj_06 obj_03)
        (pred_4 obj_06 obj_09)
        (pred_4 obj_03 obj_06)
        (pred_4 obj_08 obj_02)
        (pred_4 obj_07 obj_11)
        (pred_5 obj_01 obj_02)
        (pred_5 obj_12 obj_09)
        (pred_5 obj_04 obj_03)
        (pred_2 obj_01)
    )

    (:goal
        (and (pred_5 obj_12 obj_07) (pred_5 obj_04 obj_07))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_1 obj_01 obj_05) (pred_5 obj_01 obj_11))) (not (and (pred_1 obj_01 obj_11) (pred_5 obj_01 obj_05)))))
  )
)

