
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-3x3-1-924487418)
    (:domain delivery)

    (:objects
        obj_09 obj_01 obj_08 obj_02 obj_04 obj_07 obj_11 obj_05 obj_06 - type_3
        obj_03 - type_1
        obj_10 - type_2
    )

    (:init
        (pred_5 obj_04 obj_02)
        (pred_5 obj_07 obj_08)
        (pred_5 obj_01 obj_09)
        (pred_5 obj_09 obj_02)
        (pred_5 obj_02 obj_11)
        (pred_5 obj_05 obj_11)
        (pred_5 obj_01 obj_08)
        (pred_5 obj_05 obj_06)
        (pred_5 obj_06 obj_07)
        (pred_5 obj_04 obj_07)
        (pred_5 obj_08 obj_07)
        (pred_5 obj_05 obj_04)
        (pred_5 obj_02 obj_04)
        (pred_5 obj_07 obj_06)
        (pred_5 obj_11 obj_05)
        (pred_5 obj_07 obj_04)
        (pred_5 obj_06 obj_05)
        (pred_5 obj_04 obj_05)
        (pred_5 obj_02 obj_09)
        (pred_5 obj_11 obj_02)
        (pred_5 obj_08 obj_01)
        (pred_5 obj_04 obj_01)
        (pred_5 obj_01 obj_04)
        (pred_5 obj_09 obj_01)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_03 obj_02)
        (pred_4 obj_10)
    )

    (:goal
        (pred_1 obj_03 obj_07)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_2 obj_10 obj_02) (pred_1 obj_10 obj_04))) (not (and (pred_2 obj_10 obj_04) (pred_1 obj_10 obj_02)))))
  )
)

