
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-1-743432423)
    (:domain delivery)

    (:objects
        obj_10 obj_05 obj_11 obj_18 obj_14 obj_03 obj_01 obj_15 obj_12 obj_08 obj_07 obj_06 obj_13 obj_09 obj_17 obj_16 - type_4
        obj_02 - type_2
        obj_04 - type_3
    )

    (:init
        (pred_3 obj_07 obj_08)
        (pred_3 obj_12 obj_08)
        (pred_3 obj_08 obj_03)
        (pred_3 obj_06 obj_15)
        (pred_3 obj_06 obj_16)
        (pred_3 obj_06 obj_07)
        (pred_3 obj_08 obj_12)
        (pred_3 obj_08 obj_09)
        (pred_3 obj_15 obj_01)
        (pred_3 obj_09 obj_17)
        (pred_3 obj_09 obj_13)
        (pred_3 obj_14 obj_10)
        (pred_3 obj_11 obj_05)
        (pred_3 obj_05 obj_10)
        (pred_3 obj_13 obj_09)
        (pred_3 obj_09 obj_08)
        (pred_3 obj_08 obj_07)
        (pred_3 obj_13 obj_12)
        (pred_3 obj_01 obj_11)
        (pred_3 obj_11 obj_01)
        (pred_3 obj_12 obj_14)
        (pred_3 obj_15 obj_18)
        (pred_3 obj_07 obj_01)
        (pred_3 obj_01 obj_03)
        (pred_3 obj_17 obj_09)
        (pred_3 obj_18 obj_11)
        (pred_3 obj_03 obj_08)
        (pred_3 obj_11 obj_18)
        (pred_3 obj_01 obj_07)
        (pred_3 obj_15 obj_06)
        (pred_3 obj_17 obj_07)
        (pred_3 obj_17 obj_16)
        (pred_3 obj_01 obj_15)
        (pred_3 obj_14 obj_03)
        (pred_3 obj_10 obj_05)
        (pred_3 obj_05 obj_11)
        (pred_3 obj_14 obj_12)
        (pred_3 obj_03 obj_05)
        (pred_3 obj_18 obj_15)
        (pred_3 obj_05 obj_03)
        (pred_3 obj_03 obj_14)
        (pred_3 obj_10 obj_14)
        (pred_3 obj_16 obj_17)
        (pred_3 obj_03 obj_01)
        (pred_3 obj_16 obj_06)
        (pred_3 obj_07 obj_17)
        (pred_3 obj_12 obj_13)
        (pred_3 obj_07 obj_06)
        (pred_1 obj_02 obj_06)
        (pred_1 obj_04 obj_11)
        (pred_5 obj_04)
    )

    (:goal
        (pred_1 obj_02 obj_05)
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_04 obj_18) (pred_1 obj_04 obj_15))) (not (and (pred_4 obj_04 obj_15) (pred_1 obj_04 obj_18)))))
  )
)

