
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-4x4-2-893134183)
    (:domain delivery)

    (:objects
        obj_09 obj_01 obj_04 obj_17 obj_08 obj_12 obj_11 obj_02 obj_10 obj_06 obj_19 obj_07 obj_13 obj_16 obj_15 obj_18 - type_1
        obj_14 obj_05 - type_4
        obj_03 - type_2
    )

    (:init
        (pred_1 obj_04 obj_01)
        (pred_1 obj_11 obj_12)
        (pred_1 obj_10 obj_13)
        (pred_1 obj_19 obj_11)
        (pred_1 obj_09 obj_08)
        (pred_1 obj_19 obj_15)
        (pred_1 obj_19 obj_07)
        (pred_1 obj_13 obj_10)
        (pred_1 obj_04 obj_17)
        (pred_1 obj_07 obj_19)
        (pred_1 obj_16 obj_15)
        (pred_1 obj_08 obj_12)
        (pred_1 obj_13 obj_16)
        (pred_1 obj_16 obj_13)
        (pred_1 obj_04 obj_11)
        (pred_1 obj_07 obj_02)
        (pred_1 obj_06 obj_10)
        (pred_1 obj_06 obj_19)
        (pred_1 obj_18 obj_07)
        (pred_1 obj_01 obj_04)
        (pred_1 obj_15 obj_19)
        (pred_1 obj_12 obj_01)
        (pred_1 obj_07 obj_18)
        (pred_1 obj_18 obj_15)
        (pred_1 obj_01 obj_09)
        (pred_1 obj_11 obj_19)
        (pred_1 obj_11 obj_04)
        (pred_1 obj_06 obj_16)
        (pred_1 obj_02 obj_17)
        (pred_1 obj_15 obj_16)
        (pred_1 obj_12 obj_06)
        (pred_1 obj_17 obj_04)
        (pred_1 obj_10 obj_06)
        (pred_1 obj_11 obj_02)
        (pred_1 obj_09 obj_01)
        (pred_1 obj_08 obj_10)
        (pred_1 obj_12 obj_08)
        (pred_1 obj_08 obj_09)
        (pred_1 obj_12 obj_11)
        (pred_1 obj_02 obj_11)
        (pred_1 obj_10 obj_08)
        (pred_1 obj_19 obj_06)
        (pred_1 obj_02 obj_07)
        (pred_1 obj_06 obj_12)
        (pred_1 obj_15 obj_18)
        (pred_1 obj_17 obj_02)
        (pred_1 obj_01 obj_12)
        (pred_1 obj_16 obj_06)
        (pred_2 obj_14 obj_18)
        (pred_2 obj_03 obj_01)
        (pred_2 obj_05 obj_10)
        (pred_5 obj_03)
    )

    (:goal
        (and (pred_2 obj_14 obj_10) (pred_2 obj_05 obj_10))
    )

    
    
    

  (:constraints
    (always (and (not (and (pred_4 obj_03 obj_19) (pred_2 obj_03 obj_07))) (not (and (pred_4 obj_03 obj_07) (pred_2 obj_03 obj_19)))))
  )
)

