#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o evaluate_sft_grippers.o
#$ -pe smp 8          # Specify parallel environment and legal core size
#$ -N evaluate_sft_grippers     # Specify job name

conda activate llmstl

# 生成测试问题
python3 grippers/convert_pddl3.py grippers/all_problems/tes grippers/testing_problems3


python3 script/evaluate_llm_solver.py --model sft_model/sft_model_pddl_mistral_7b_grippers  --problems-dir grippers/testing_problems3 --domain-file grippers/domain3.pddl --max-problems 100 --output grippers_test_results.json  --results-dir grippers_mistral_planning_results


