#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o evaluate_sft_blocksworld.o
#$ -pe smp 8          # Specify parallel environment and legal core size
#$ -N evaluate_sft_blocksworld     # Specify job name

conda activate llmstl



python3 script/evaluate_llm_solver.py --model sft_model/sft_model_pddl_mistral_7b_blocksworld  --problems-dir blocksworld/testing_problems3 --domain-file blocksworld/domain3.pddl --max-problems 100 --output blocksworld_test_results.json  --results-dir blocksworld_mistral_planning_results


