#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate_sft_ferry.o
#$ -pe smp 8          # Specify parallel environment and legal core size
#$ -N evaluate_sft_ferry     # Specify job name

conda activate llmstl



python3 script/evaluate_llm_solver.py --model sft_model/sft_model_pddl_mistral_7b_ferry  --problems-dir ferry/testing_problems3 --domain-file ferry/domain3.pddl --max-problems 100 --output ferry_test_results.json  --results-dir planning_results/ferry_mistral_sft_planning_results


