#!/bin/bash

#$ -M jfan5@nd.edu
#$ -m abe
#$ -q gpu
#$ -l gpu_card=1
#$ -o job_outputs/evaluate_sft_spanner.o
#$ -pe smp 8          # Specify parallel environment and legal core size
#$ -N evaluate_sft_spanner     # Specify job name

conda activate llmstl


    
python3 script/evaluate_llm_solver.py --model sft_model/sft_model_pddl_mistral_7b_spanner  --problems-dir spanner/testing_problems3 --domain-file spanner/domain3.pddl --max-problems 100 --output spanner_test_results.json  --results-dir planning_results/spanner_mistral_sft_planning_results


