#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/generate_candidates_rovers_pddl3_gpt.o
#SBATCH --cpus-per-task=28
#SBATCH --job-name=generate_candidates_rovers_pddl3_gpt

conda activate llmstl

MODEL_PATH="sft_model/gpt_oss_20b/rovers/pddl3"
DOMAIN_FILE="rovers/domain3.pddl"
PROBLEMS_DIR="rovers/all_problems3"
PROMPT_TEMPLATE="prompt_pddl3.txt"
OUTPUT_PATH="data/dpo/gpt_oss_20b/rovers/pddl3/scored.jsonl"

python3 script/generate_score_candidate.py \
  --model "$MODEL_PATH" \
  --family auto \
  --domain-file "$DOMAIN_FILE" \
  --problems-dir "$PROBLEMS_DIR" \
  --prompt-template "$PROMPT_TEMPLATE" \
  --out "$OUTPUT_PATH"
