#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_sft_spanner_pddl2_gpt.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_sft_spanner_pddl2_gpt # Specify job name

conda activate llmstl

python3 script/evaluate_llm_solver.py --model sft_model/gpt_oss_20b/spanner/pddl2  --problems-dir spanner/all_problems --domain-file spanner/domain.pddl --max-problems 100 --output spanner_test_results_pddl2.json  --results-dir sft_results/gpt_oss_20b/spanner/pddl2



