


(define (problem gripper-11)
(:domain gripper-strips)
(:objects rooma roomb room3 room4 left ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 ball11 )
(:init
(room rooma)
(room roomb)
(room room3)
(room room4)
(gripper left)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(ball ball9)
(ball ball10)
(ball ball11)
(free left)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 rooma)
(at ball6 rooma)
(at ball7 rooma)
(at ball8 rooma)
(at ball9 rooma)
(at ball10 rooma)
(at ball11 rooma)
(at-robby rooma)
)
(:goal
(and
(at ball1 room4)
(at ball2 room4)
(at ball3 room4)
(at ball4 room4)
(at ball5 room4)
(at ball6 room4)
(at ball7 room4)
(at ball8 room4)
(at ball9 room4)
(at ball10 room4)
(at ball11 room4)
)
)
)


