


(define (problem gripper-10)
(:domain gripper-strips)
(:objects rooma roomb room3 room4 left right ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 ball10 )
(:init
(room rooma)
(room roomb)
(room room3)
(room room4)
(gripper left)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(ball ball9)
(ball ball10)
(free left)
(free right)
(at ball1 rooma)
(at ball2 roomb)
(at ball3 roomb)
(at ball4 roomb)
(at ball5 room3)
(at ball6 room3)
(at ball7 room3)
(at ball8 room4)
(at ball9 room4)
(at ball10 room4)
(at-robby rooma)
)
(:goal
(and
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 roomb)
(at ball6 roomb)
(at ball7 room3)
(at ball8 room3)
(at ball9 room3)
(at ball10 room4)
)
)
)


