#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_blocksworld_all_testing_models_gpt.o
#SBATCH --cpus-per-task=28
#SBATCH --job-name=evaluate_blocksworld_all_testing_models_gpt

conda activate llmstl

# PDDL2 fine-tuned model
python3 script/evaluate_llm_solver.py \
  --model sft_model/gpt_oss_20b/blocksworld/pddl2 \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_pddl2.json \
  --results-dir planning_results/blocksworld_pddl2_all_testing

# PDDL3 fine-tuned model evaluated on PDDL2 testing set
python3 script/evaluate_llm_solver.py \
  --model sft_model/gpt_oss_20b/blocksworld/pddl3 \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_pddl3.json \
  --results-dir planning_results/blocksworld_pddl3_all_testing

# Baseline unsloth model
python3 script/evaluate_llm_solver.py \
  --model unsloth/gpt-oss-20b-unsloth-bnb-4bit \
  --problems-dir blocksworld/all_problems3/testing \
  --domain-file blocksworld/domain3.pddl \
  --output blocksworld_all_testing_baseline.json \
  --results-dir planning_results/blocksworld_baseline_all_testing
