#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_sft_blocksworld_pddl3_gpt.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_sft_blocksworld_pddl3_gpt # Specify job name

conda activate llmstl

python3 script/evaluate_llm_solver.py --model sft_model/gpt_oss_20b/blocksworld/pddl3  --problems-dir blocksworld/all_problems3 --domain-file blocksworld/domain3.pddl --max-problems 100 --output blocksworld_test_results_pddl3.json  --results-dir sft_results/gpt_oss_20b/blocksworld/pddl3



