#!/bin/bash

#SBATCH --mail-user=jfan5@nd.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --output=job_outputs/evaluate_sft_delivery_pddl2.o
#SBATCH --cpus-per-task=28 # Specify parallel environment and legal core size
#SBATCH --job-name=evaluate_sft_delivery_pddl2 # Specify job name

conda activate llmstl

python3 script/evaluate_llm_solver.py --model sft_model/mistral_7b/delivery/pddl2  --problems-dir delivery/all_problems_test --domain-file delivery/domain.pddl --max-problems 100 --output delivery_test_results_pddl2.json  --results-dir sft_results/mistral_7b/delivery/pddl2



