; Domain designed by Yannis Dimopoulos, Alfonso Gerevini and Alessandro Saetti
; This file has been automatically generated by the generator available from
; http://zeus.ing.unibs.it/ipc-5/generators/index.html

(define (problem truck-1)
(:domain Trucks)
(:objects
	truck1 - truck
	package1 - package
	l1 - location
	l2 - location
	t0 - time
	t1 - time
	t2 - time
	a1 - truckarea)

(:init
	(at truck1 l2)
	(free a1 truck1)
	(at package1 l1)
	(connected l1 l2)
	(connected l2 l1)
	(time-now t0)
	(le t1 t1)
	(le t1 t2)
	(le t2 t2)
	(next t0 t1)
	(next t1 t2))

(:goal (and 
	(at-destination package1 l2)))



)
